### ISSUE TITLE
addComponent chaining vs returning component added

### ISSUE THREAD

**Issue by Async0x42** [prime31/Nez#10]
This is kind of a discussion for opinions, but personally I think addComponent should return the component being added.

My reason for this at least, is say for entity definitions, we can simply

```
_spriteAnimations = addComponent(new Sprite<AnimationEnums>(_____));

vs

_spriteAnimations = new Sprite<AnimationEnums>(____);
addComponent(_spriteAnimations);
```

The chaining seems handy for quick prototyping (such as in the example scenes), but this feels like a more natural way to do it. Any thoughts on this? I'm open to differing opinions, if there's a real benefit to chaining that I just don't know about, I'd be interested!

**Comment by prime31** [comment]
I go back and forth on this one 10 times per day! addRenderer, addEntity and addPostProcessor all return the item added so it definitely makes sense for addComponent to do the same. The chaining is great for quickly thrown together stuff but it isn't the best for other things like configuring components.

On the flip side is the fact that components can have their public properties initialized all in one line:

'''
blah.addComponent( new Thing()
{
   thing = 6,
   other = 9
}
'''

It's a tough call and in reality either way is totally useable so it doesn't matter too much. I'm kind of leaning towards returning the component to match the other methods at this point.

**Comment by Async0x42** [comment]
Initializing them on the same line is actually kind of nice, but if the other methods are returning the item added and this is the only one that doesn't, I definitely vote in favour of making them consistent! (I didn't realize yet that the others worked that way, and it might also be the 'expected' result for newcomers to Nez when they use it)
