### ISSUE TITLE
Is not being able to add other entities in onAddedToScene() by design?

### ISSUE THREAD

**Issue by OctarineSorcerer** [prime31/Nez#100]
If you add an entity (called rootEntity from here) to a scene, if you attempt to add any other entities to the scene in rootEntity's onAddedToScene, the 'children' actually don't get added to the scene by the EntityList.

This is to do with this section of code in EntityList:
```
// now that all entities are added to the scene, we loop through again and call onAddedToScene
				for( var i = 0; i < _entitiesToAdd.Count; i++ )
					_entitiesToAdd[i].onAddedToScene();

				_entitiesToAdd.Clear();
```

It doesn't recheck to see if the entitiesToAdd size has changed at all, and so any entities added upon addition to scene are cleared from the list before they are ever added to the scene.

I'd modify it myself, but I wasn't sure whether this was a bug or by design.

**Comment by prime31** [comment]
It is definitely a bug. The lists will need some double buffering to handle onAddedToScene and onRemovedFromScene properly. Changes incoming.
