### ISSUE TITLE
Update Nez UI functions with consistent style

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#102]
It might be a good idea to change getter and setter methods to C#'s very nice way of handing properties.  That way, we can deprecate duplicate methods like `cell.setColor` and `cell.getColor` and replace it with just `cell.color`, like the rest of the library.
I'm guessing these are just artifacts from porting the library from Java.

**Comment by prime31** [comment]
The UI code was a port from libGDX UI so it has some oddities compared to the rest of Nez. I don't know when it will be changed or what the plan of attack is for it. By keeping it the way it is libGDX UI documentation is all still valid which is a big benefit.

All that being said the code will definitely not be moving to C# properties. The rest of Nez is moving to only getter properties and then set* chainable methods. This is for two reasons:

1. I am not a fan of hiding heavy code (which setters can often be) in properties. It isn't clear without looking at the source whereas a proper method call is.
2. setters are often used for configuration. If each set* method returns this it makes it possible to chain them for clean, clear configuration.
