### ISSUE TITLE
EntityList.addToTagList is very slow

### ISSUE THREAD

**Issue by Avataren** [prime31/Nez#103]
When adding a large number of entities to a scene, it takes a very long time to complete. I traced this down to EntityList.addToTagList being the main culprit.

The code below takes 28.25 seconds to run, but if I add "if (entity.tag == 0) return;" as the first line of code in EntityList.addToTagList, the time taken is 0.69 seconds on my system.

I tried initializing the tag list with 10000 elements, but it still took 28.16 seconds.

It would be very nice if this could be made more efficient.

            scene = Scene.createWithDefaultRenderer();
            Stopwatch sw = Stopwatch.StartNew();
            for (int i=0;i<10000;i++)
            {
                scene.createEntity("test");
            }
            base.Update(new GameTime());
            Debug.log($"Added 10000 entities in {sw.elapsed.TotalSeconds:f2} seconds");

**Comment by prime31** [comment]
Are you testing with a debug build? If so, that would explain the slowness. Debug builds will do a List.Contains for every add which is a very slow operation as the list size grows.

**Comment by Avataren** [comment]
Yes, that's indeed in a debug build, but it still takes a long time in release. I'm on a different system now that's a bit slower, and I get 32 seconds in debug vs 14 seconds in release. 

I realize that adding 10k entities at once is probably not a very common use case, and the case I'm currently working on is probably better off using the tiles system anyway, if I can find a good way to sort a tile-layer together with sprites efficiently without reimplementing too much of the rendering pipeline.

**Comment by prime31** [comment]
Do you have to use Entities with your system? Could you get away with one (or a few) Entities with more Components instead?

The main loop of Nez is pretty well optimized at this point so the only thing that would work on a case like this would be a toggle to turn off the Entity tag system altogether.

**Comment by Avataren** [comment]
I can actually get away with one Entity for this, and a bunch of components! I tried this earlier, but couldnt get it to render properly, and I just discovered why.

 The reason was that I was using component.transform.setLocalPosition to place them, instead of setting component.setLocalOffset. This runs in an instant.

**Comment by prime31** [comment]
Perfecto! This is exactly why the local offset was added. It lets you stick a pile of Renderables on one Component if needed.
