### ISSUE TITLE
Having trouble tweening properties

### ISSUE THREAD

**Issue by ismyhc** [prime31/Nez#104]
I'm having a hell of a time with trying to tween. Ive tried multiple things with no success.

I have a simple entity with a sprite component.

```
entity.transform.tweenScaleTo(4.0f);

entity.transform.tweenScaleTo(new Vector2(4.0f, 4.0f);

PropertyTweens.vector2PropertyTo(entity.transform, "scale", new Vector2(4.0f, 4.0f), 1.0f).start();

PropertyTweens.floatPropertyTo(this, "scale", 4.0f, 1.0f).start();
```

None of the above work. I may be missing something glaringly obvious...

Thanks,
Jacob

**Comment by ifmcmaster** [comment]
For your first two examples, you just need to call 'start()' on the tween object returned by 'tweenScaleTo()'. That should do the trick.

**Comment by ismyhc** [comment]
oh man.. thanks for that!
