### ISSUE TITLE
DeferredLightingRenderer renderlayers are rendered in reverse order from DefaultRenderer

### ISSUE THREAD

**Issue by Avataren** [prime31/Nez#105]
There might be a good reason for this, but when adding several renderlayers to a DeferredLightingRenderer, they are rendered in the opposite order of the DefaultRenderer.

	_lightLayer = lightLayer;
	Array.Sort( renderLayers );
        Array.Reverse(renderLayers); //this will make them render in the same order as DefaultRenderer

**Comment by Avataren** [comment]
I can of course add them in opposite order to correct it, but it seems most intuitive to add them from low to high.

**Comment by prime31** [comment]
You are indeed correct. All fixed now.
