### ISSUE TITLE
Can't specify style fields in a skin.json file

### ISSUE THREAD

**Issue by OctarineSorcerer** [prime31/Nez#106]
SelectBoxStyle requires specification of an already declared style to be constructed properly - a scrollStyle and a listStyle.
However, in a skin file I'm using, with both styles created and seemingly instantiated correctly, SelectBox creation will throw an exception, as the style's listStyle and scrollStyle fields are null. Further investigation seems to show that skin loading will only look for colors, fonts and drawables? 

It looks like using skin files alone will not allow the declaration of any style where the fields contain further styles. Is that the case? If so, I can get around it, but if not, there's nothing in the documentation to demonstrate how to deal with these cases in a skin file and I'd appreciate being shown how it's done.

From what I can see the only styles that are affected by this are SelectBoxStyle and TextTooltipStyle. 

I've attached the relevant section of the skin file I'm using (though you will need to change the font fields if you plan on using this section)  - thanks in advance.
```
ScrollPaneStyle: 
	{
		'default': { background:'default-round', corner:'default-round', hScroll: 'default-slider', hScrollKnob: 'default-slider-knob', vScroll: 'default-slider', vScrollKnob: 'default-round-large' }
	},
	ListBoxStyle: 
	{
		'default': { font: 'Fonts/Minion20/minion20', selection: 'default-round'},
	},
	SelectBoxStyle: 
	{
		'default': { font: 'Fonts/Minion20/minion20', fontColor: 'white', background: 'default-round', scrollStyle: 'default', listStyle: 'default'}
	},
```

**Comment by prime31** [comment]
I just pushed a change that allows specifying a style in the json config. Note that it did require changing TextTooltipStyle.label to TextTooltipStyle.labelStyle to match the naming conventions of the rest of the UI system.
