### ISSUE TITLE
TexturePackerAtlas SpriteAnimation Generation

### ISSUE THREAD

**Issue by Eendhoorn** [prime31/Nez#109]
I prefer using TexturePacker for all my sprite atlas needs, but now I'm missing out on the automatic SpriteAnimation generation from the TextureAtlasProcressor, which is quite nice. 

I was thinking that the same thing could be implemented for the TexturePackerAtlas, where the "filename" metadata in the texturepacker json file can be used to distinguish the animations.
By default texturepacker neatly appends each "filename" node with the frame number ("mario_walk_0001"), so the string should be easy to split there.

Adding a bool in the content processor would make this whole process optional for people who'd rather use their own method to supply animation data.

Is this something you'd like to see or do you wish to separate sprite atlas and animation data from each other?

**Comment by prime31** [comment]
I don't see any reason why not. If you want to send over a PR feel free.

**Comment by prime31** [comment]
PR merged
