### ISSUE TITLE
Allow parameter-less construction on Sprite/Sprite<T>

### ISSUE THREAD

**Issue by Async0x42** [prime31/Nez#11]
For example, it's fairly intuitive to do

```
var xx = new Sprite<AnimationEnums>();

<get all animations from some loader>
<loop through and add them to the sprite>
```

rather than
```
<get all animations from some loader>
var xx = new Sprite<AnimationEnums>(AnimationEnums.WalkLeft, AnimationLoader.Load<xxWalkLeft>();

<loop through the rest of the animations and add them to the sprite>
```

Parameter-less constructors open up some simpler-style possibilities with reflection and dynamically creating entities/components (At least, I think!) -> I don't really see a reason to force the texture on creation, as if it throws an error, we'll know we didn't set a texture.

For Sprite<T> we can check if any animations exist, and if it's the first one being added, then set the subtexture to animation.frames[0].subtexture.

Any thoughts on this?

**Comment by prime31** [comment]
The big issue with a parameterless SpriteT is when dealing with Colliders. If there is no Subtexture available automatic collider sizing can't happen. One possible solution would be to have a parameterless constructor and just fail loudly in the case where there is an auto-sizing collider added no Subtexture set yet.
