### ISSUE TITLE
SelectBox can cause array oob errors when containing windows are moved

### ISSUE THREAD

**Issue by ellisonch** [prime31/Nez#111]
I have a `SelectBox` inside of a `Window`.  If I open the `SelectBox`, and then move the window, this sometimes causes array out of bound errors in Group.cs at the following place:

```.cs
public void drawChildren( Graphics graphics, float parentAlpha )
...
children[i].x = cx + offsetX;
children[i].y = cy + offsetY;
// if children[i] refers to a SelectBoxList, then the following call is problematic
children[i].draw( graphics, parentAlpha );
// because the above draw() call may have deleted that element
// so at this point, children[i] might be out of bounds or refer to a different element entirely
children[i].x = cx;
children[i].y = cy;
```

The problem is caused when `SelectBoxList`'s `draw()` method calls `hide()`, which happens for me when I try moving the window around.  It may happen in other circumstances, but it's pretty easy to trigger when I wiggle the window.
```.cs
public override void draw( Graphics graphics, float parentAlpha ) {
  var temp = _selectBox.localToStageCoordinates( Vector2.Zero );
  if( temp != _screenPosition )
    hide();
```

I didn't look, but if there are other places that may be referring to `SelectBoxList`'s `draw()`, then the same bug may exist there.

It seems the implicit assumption is that a call to `draw()` shouldn't change the hierarchy, but this is being violated.  If this is happening elsewhere, then this kind of bug may exist in those places too.

**Comment by prime31** [comment]
It looks like this might have been a forgotten call to delay the hide call. If you change the 'hide' line to the following does it fix the issue for you?

    Core.schedule( 0f, t => hide() );

**Comment by ellisonch** [comment]
Yes, that appears to fix it.  Thanks!
