### ISSUE TITLE
code re title bar in Window's hit() seems broken

### ISSUE THREAD

**Issue by ellisonch** [prime31/Nez#112]
So I ran into a weird issue where a window was becoming unresponsive when I positioned it in a certain part of the screen.  I traced it down and found that the problem lies in `Window`'s `hit()` method.  I'm not entirely sure I understand the method, which is why I'm writing this up instead of submitting a pull request.  I'm nearly sure there is a bug, I'm just sure what the code is supposed to do.

The following if-statement in `hit()` seems to be incorrect:

``` .cs
if( y <= height && y >= height - getPadTop() && x >= 0 && x <= getWidth() )
{
    // Hit the title bar, don't use the hit child if it is in the Window's table.
    Element current = hit;
    while( current.getParent() != this )
        current = current.getParent();

    if( getCell( current ) != null )
        return this;
}
```

I believe the code is meant to detect when the click hits the window's title bar.  As written, it appears to prevent _any_ hits inside of windows that live in a specific band on the screen.  It seems as though there are two errors here:

First, `x` and `y` refer to the `x` and `y` coordinates of the Window itself, not where the user clicked.  I believe `x` and `y` should be `point.X` and `point.Y` respectively.

Second, heights get bigger as you go down the window, so I think it should be

``` .cs
if( point.Y >= 0 && point.Y <= getPadTop() && x >= 0 && x <= getWidth() )
```

or perhaps with `<` on the two upperbounds.

Also, is it safe to assume that the height of the title bar is equal to `getPadTop()`?  A few quick 

``` .cs
getTitleTable().row();
getTitleTable().add(new Label("foobar"));
```

makes the titlebar taller without updating `_padTop`. 

Finally, I'm not sure I understand what the body of the `if` is meant to do, so I'm not sure if the above is correct.  I understand the comment to mean that if you hit something on the title bar, don't use it if it's an element of the Window.  I'm not entirely sure this makes sense.  If I put a close button on my title bar, I still want to be able to hit it.  Luckily, even with the bounds corrected, this code does not seem to prevent that, so I'm not sure it's working as intended either.  Considering the guard was incorrect so this code never running when it was meant to, perhaps this code simply isn't needed?

**Comment by prime31** [comment]
The UI code for Nez was a port of libGDX Scene2D UI. It has a bunch of changes mostly in the more common stuff like buttons, checkboxes, etc but for the most part the code was written to be as close as possible to libGDX so that docs/examples would be easy to port.

That being said, I do believe you are correct in that the comparisons are backwards for y. It is indeed quite possible that the entire code block can be tossed. I'll have to give it a good look when I get a spare moment. I haven't had a need to use the Window since it was created so I am rusty on it's purpose and personality.

**Comment by brandc87** [comment]
I'm not sure it's the hit function... If you drag a window past the stage the image/background stays in but the actual bounds of the window continues to move.

You can see this with debugAll() running. Some screenshots:
When game loads the windows bounds are correct,
![screen shot 2018-01-25 at 16 30 33](https://user-images.githubusercontent.com/11300674/35399881-42149bb2-01ed-11e8-9911-c8a8f9aea5fb.png)

Here I've tried to drag the window off screen to the left the image stays in but the bounding box continues moving.
![screen shot 2018-01-25 at 16 30 42](https://user-images.githubusercontent.com/11300674/35399882-423ea3da-01ed-11e8-90c3-6d9f0021022b.png)

**Comment by Vanit** [comment]
I believe this can be closed (@brandc87 created a new issue for his specific bug).
