### ISSUE TITLE
SelectBoxList update() doesn't handle clicks correctly

### ISSUE THREAD

**Issue by ellisonch** [prime31/Nez#114]
The recent commit a739a5e861d7c04f97633da76aab757d0fc6e3e3 seems to fix some hardcoded magic constants in SelectBoxList's update function.  However, it appears that it is still not correct.  It uses `height` instead of `_selectBox.height`, and it doesn't take into consideration the fact that SelectBoxLists can flow upwards from the SelectBox, e.g., when the SelectBox is near the bottom of the screen.

Here is the code from the previous commit:
```.cs
var point = stage.getMousePosition();
point = screenToLocalCoordinates( point );
if( point.X < 0 || point.X > width || point.Y < -height || point.Y > 0 )
	Core.schedule( 0f, t => hide() );
```
I believe the below code implements the correct logic:
```.cs
var point = stage.getMousePosition();
// close the SelectBoxList if a user clicks outside of it or the SelectBox
// assumes the selectBox and the selectBoxList have the same widths
if (y <= _selectBox.y) { // SelectBoxList flows up from SelectBox
	if (point.X < x || point.X > x + width || point.Y < y || point.Y > y + height + _selectBox.height)
		Core.schedule(0f, t => hide());
} else { // SelectBoxList flows down from SelectBox
	if (point.X < x || point.X > x + width || point.Y < y - _selectBox.height || point.Y > y + height)
		Core.schedule(0f, t => hide());
}
```
This is ugly and it all feels incredibly fragile, so let me know if you'd like to do something different.  It could be greatly simplified to just checking if the user clicks outside the SelectBoxList, if only this code didn't execute when you click the SelectBoxList to begin with (you don't want to close it immediately).  I don't know if that's a possible change.

**Comment by ellisonch** [comment]
Correction.  In my code above, I assumed all the `.x` and `.y`s were screen coordinates.  This seems true for SelectBoxList.  However, it appears that `_selectBox.y` is a relative offset.  I'm not sure why SelectBoxList and SelectBox differ in this regard, but it makes my check for flowing up or down incorrect.  Perhaps they're always meant to be relative but they have different parents?

At any rate, my code needs to further make sure it uses screen coordinates or be properly relative-ized.

**Comment by prime31** [comment]
OK. So I gave this a look and I believe I've got a solution. The code below makes sure the bounds that it checks includes the select box and the select box list regardless of if it is above or below. See if that does the trick for you.

```csharp
		protected override void update()
		{
			if( Input.isKeyPressed( Keys.Escape ) )
			{
				Core.schedule( 0f, false, this, t => ( (SelectBoxList<T>)t.context ).hide() );
				return;
			}

			if( Input.leftMouseButtonPressed )
			{
				var point = stage.getMousePosition();
				point = screenToLocalCoordinates( point );

				float yMin = 0, yMax = height;

				// we need to include the list and the select box for our click checker. if the list is above the select box we expand the
				// height to include it. If the list is below we check for positions up to -_selectBox.height
				if( y > _selectBox.y ) // select box above list
					yMin -= _selectBox.height;
				else
					yMax += _selectBox.height;
				
				if( point.X < 0 || point.X > width || point.Y > yMax || point.Y < yMin )
					Core.schedule( 0f, false, this, t => ( (SelectBoxList<T>)t.context ).hide() );
			}
			
			base.update();
			toFront();
		}
```

**Comment by ellisonch** [comment]
I think your solution still suffers from the problem I mentioned in my second comment.  That is, `y` is a screen position, while `_selectbox.y` is a position relative to the SelectBox's container.  This makes the check for above/below incorrect.

Perhaps the easiest thing to do would be to make the `below` local variable in `show()` an instance variable (maybe call it `_positionedBelowBox` or whatever), and then you can simply use it instead of the incorrect `y > _selectBox.y`.  Such a bool might come in useful in other places as well.

I've tested your code with that change and it seems to work for me.

I guess the other option would be to convert `y` to a position relative to the SelectBox, or vice versa, and I'm not sure how to do that.

Can you explain the change to from ` t => hide()` to `t => ( (SelectBoxList<T>)t.context ).hide()`?  Is it possible for the context to change in the meantime?

**Comment by prime31** [comment]
Do you have an example that illustrates an issue with above and below SelectBoxes? I can't produce an example that fails with the above code sticking SelectBoxes all over the screen extents.

Both `y` and `_selectBox.y` are globals, not relatives. You can confirm by sticking a log in there and adding one SelectBox at the top of the screen and one at the bottom. The logs end up looking like this:

```
Log: y: 34, _selectBox.y: 20
Log: y: 460, _selectBox.y: 700
```


The change in the Core.schedule call is just a little C# trick to avoid an allocation when passing around an Action. The first example below creates an Action on the fly that references `this` because it is calling the `hide` method. That makes the Action a closure and it has to allocate a little class to keep a reference to `this`.

The second example uses the extra `context

```csharp
Core.schedule( 0f, t => hide() );

Core.schedule( 0f, false, this, t => ( (SelectBoxList<T>)t.context ).hide() );
```

**Comment by ellisonch** [comment]
The SelectBox's x&y is definitely relative to its container.  Mine lives inside a window.  As I move the window down the screen, I get the following:
```
y: 161, _selectBox.y: 111
y: 258, _selectBox.y: 111
y: 407, _selectBox.y: 111
y: 552, _selectBox.y: 111
```

Because the SelectBox stays at the same place relative to the window, its `.y` doesn't change.  However, the SelectBoxList's `.y` definitely does.

My SelectBox's parent is a Window, while my SelectBoxList's parent is a Group that contains all of my Windows.  I can't figure out where this gets set, but that's how it is.

Because the SelectBoxList is not placed inside the same container, it has a more global x&y.  Perhaps another way to fix this would be to place the SelectBoxList in the same container as the SelectBox when it is created.  It seems like there may be annoying problems with this as well (e.g., if the box changes parents, you'd have to keep the list synced).

Thanks for the info about the allocations!

**Comment by prime31** [comment]
Ah, yes. I completely forgot that Groups will end up with relative children. I'll let the draw method decide which path the code should take since it knows with 100% certainty. Push coming shortly.

**Comment by ellisonch** [comment]
Works great!  Thanks!
