### ISSUE TITLE
cannot chain deferred light methods correctly?

### ISSUE THREAD

**Issue by grumpyoldman1066** [prime31/Nez#115]
Should it be possible to method chain AreaLight method SetDirection?  Also, shouldn't it be possible to change intensity?  No method exists for that at all.

>arealight.addComponent(new AreaLight(100,400)).setRenderLayer(LIGHT_LAYER).setEnabled(true);

works but

>Component  alight = new AreaLight(100,400).setRenderLayer(LIGHT_LAYER).setEnabled(true).setDirection(new Vector3(100,0,0));
         
doesn't and at the same time I can't do 

>Component alight = new AreaLight(100, 400);
>alight.setRenderLayer(LIGHT_LAYER);
>alight.setEnabled(true);
>alight.setDirection(100, 100, 100);

>arealight.addComponent(alight);

Is explicit casting like in the Deferred Lighting Sample DeferredLightingController.cs necessary?

>var alight2=alight as AreaLight

doesn't give access to the necessary methods either.

I'm missing something here, I think.

**Comment by prime31** [comment]
When you use method chaining in something like AreaLight you have to order your chaining top-down. For example, AreaLight's class hierarchy is:

    AreaLight -> DeferredLight -> RenderableComponent -> Component

That means when you chain you have to chain first AreaLight methods, then DeferredLight methods, then RenderableComponent methods, etc. The reason for this is that C# doesn't provide a proper "instanceof" return type so we are all stuck with either ordering method calls top-down or implementing every set* method in every subclass.

**Comment by grumpyoldman1066** [comment]
I wasn't aware of that, thank you!
