### ISSUE TITLE
ArgumentException in FastList::sort

### ISSUE THREAD

**Issue by Avataren** [prime31/Nez#116]
I keep getting an ArgumentException in FastList::sort in my scene, it has thousands of components, and a fair amount of them moving around, all being sorted on both layer and layerDepth. The exception happens randomly, and I'm not able to reproduce it without waiting until it happens.

The exception message is "Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different".

I have not been able to get the exception to trigger if I comment out the material sorting in RenderableComponent::CompareTo, but I don't change any of the materials after the scene starts running, and the code looks ok to me, so I'm not really sure what's going on.

**Comment by Avataren** [comment]
I just ran the code for 15 minutes with no exception with the material sorting commented out, and no problems. When I re-enabled it the exception came in about 15 seconds..

Oh, and the call stack is as follows:

	Nez.dll!Nez.FastList<Nez.RenderableComponent>.sort() Line 119	C#
 	Nez.dll!Nez.RenderableComponentList.updateLists() Line 108	C#
 	Nez.dll!Nez.Scene.update() Line 384	C#
 	Nez.dll!Nez.Core.Update(Microsoft.Xna.Framework.GameTime gameTime) Line 220	C#
 	GameEngine.exe!GameEngine.GameEngine.Update(Microsoft.Xna.Framework.GameTime gameTime) Line 59	C#

**Comment by prime31** [comment]
That's an odd one. Is [this](https://github.com/prime31/Nez/blob/master/Nez-PCL/ECS/Components/Renderables/RenderableComponent.cs#L414) the line you commented out? The [Material.CompareTo](https://github.com/prime31/Nez/blob/master/Nez-PCL/Graphics/Material.cs#L316) is a super simple and just aims to get identical Materials sorted next to each other.

Are you using a ton of different Materials? I am trying to figure out how I can attempt to repro this locally.

One other thing you can try: in the Material.CompareTo method make the first if statement return -1 and the final line return 1 (just flip the signs). Let me know if that takes care of the issue.

**Comment by Avataren** [comment]
That is indeed the line I commented out.
Curently I'm using only one material, but about 2/3 of the components share one instance, and the rest has their own instance of it.

**Comment by prime31** [comment]
Now that is very interesting. Maybe the default comparer doesnt soft nulls to the top after all. Can you try replacing the RenderableComponent CompareTo method with the following? It will end up not using the Material.CompareTo at all, instead handling the sorting entirely itself.


```
		public int CompareTo( RenderableComponent other )
		{
			var res = other.renderLayer.CompareTo( renderLayer );
			if( res == 0 )
			{
				res = other.layerDepth.CompareTo( layerDepth );
				if( res == 0 )
				{
					// both null or equal
					if( ReferenceEquals( material, other.material ) )
						return 0;

					if( other.material == null )
						return -1;
					
					return 1;
				}
			}

			return res;
		}
```

**Comment by Avataren** [comment]
Yeah, this seem to run rock stable.
