### ISSUE TITLE
Visual Studio 2012 (C# 5) support?

### ISSUE THREAD

**Issue by raizam** [prime31/Nez#117]
Hi, 

This project looks great and very useful, but in order to give it a try, I would have to install visual studio 2015 (c# 6) to get it compiled, which is too bloated to me.
C# 6 surely has some very useful feature, but I want to keep Visual Studio 2012, which is a lot lighter than 2015...  Any chance to have a C# 5 version, using preprocessors switches?

Thanks

**Comment by prime31** [comment]
There are no plans to support C# 5. I try to avoid #ifdefs as much as possible and attempting to hide the liberal usage of the AggressiveInlining attributes would make the code a mess to say the least. I'm already looking forward to C# 7 with it's ValueTuple, ref returns and multiple value returns of which there is no way to support C# 5 at all once they are in.
