### ISSUE TITLE
Need help for TexturePackerAtlas 

### ISSUE THREAD

**Issue by selimanac** [prime31/Nez#119]
I'm trying to import TexturePacker json using TexturePackerAtlas. 

```c#
var kingTexture = scene.contentManager.Load<TexturePackerAtlas>("Knight");
var kingAnim = kingTexture.getSpriteAnimation("Attack"); //returns null
```

But TexturePackerAtlas returns `spriteAnimationDetails = null`. Looks like `TexturePackerAtlasReader` doesn't return spriteAnimationDetails.  Am I missing something?

![screen shot 2016-10-03 at 13 59 23](https://cloud.githubusercontent.com/assets/1324635/19035485/59ad539e-8972-11e6-9817-ac665ff7f8fd.png)

Json file looks like this:

```json
{"frames": [
{
	"filename": "Attack-1.png",
	"frame": {"x":1,"y":1,"w":117,"h":141},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":117,"h":141},
	"sourceSize": {"w":117,"h":141},
	"pivot": {"x":0.5,"y":0.5}
},
{
	"filename": "Attack-2.png",
	"frame": {"x":120,"y":1,"w":117,"h":141},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":117,"h":141},
	"sourceSize": {"w":117,"h":141},
	"pivot": {"x":0.5,"y":0.5}
}],
"meta": {
	"app": "http://www.codeandweb.com/texturepacker",
	"version": "1.0",
	"image": "KnightTexture.png",
	"format": "RGBA8888",
	"size": {"w":476,"h":476},
	"scale": "0.2",
	"smartupdate": "$TexturePacker:SmartUpdate:cf1965faf6018f1fc30400fc425a028a:b8b508b30fd4d39fda538b64242190d1:afba9547de3d35d833846978fb7adcb4$"
}
}
```

**Comment by selimanac** [comment]
That is my fault. On pipeline tool, TexturePackerProcessor's parseAnimation is default False. When I chance it to True, it works. 

But there is an other problem. spriteAnimationDetails's Key values are diffent then filename.
In this case, "frames" key value is "Atta" and "meta"  key value is "Attac"

![screen shot 2016-10-03 at 15 18 26](https://cloud.githubusercontent.com/assets/1324635/19037047/cd08c076-897c-11e6-8954-d8bc7cabeb9e.png)

**Comment by prime31** [comment]
Something looks fishy with your animation names. TexturePacker by default automatically names animations with 4 digits at the end of the filename (like [this](https://www.codeandweb.com/texturepacker/tutorials/spritekit-animations-and-textureatlases)). Your filenames only have 1. If you rename them to have 4 digits it should parse them correctly.

**Comment by selimanac** [comment]
silly me. thanks a lot.
