### ISSUE TITLE
Strange behaviour Polygon Collider

### ISSUE THREAD

**Issue by salvadorbs** [prime31/Nez#121]
In these days, I'm trying Polygon Collider and I have this situation:

![2016-10-06_18-36-05](https://cloud.githubusercontent.com/assets/3731721/19161365/cc38b90c-8bf3-11e6-9fc3-4b5a1e958a3f.png)

Why in the first polygon collider, two vertices are inverted each other? It is same code, but the vertices are mirrored. Bug or my fault?

I make a sample project with hardcode values. If you want, try it.
[Test_PolygonCollider.zip](https://github.com/prime31/Nez/files/514349/Test_PolygonCollider.zip)

**Comment by prime31** [comment]
When dealing with polygons, the winding order always matters. As you can see [from this demo](https://vid.me/7kzT), one of your polygons is ordered correctly while the other is not.

**Comment by salvadorbs** [comment]
Ok thanks. 👍
