### ISSUE TITLE
Why Scene class has not virtual Update() method?

### ISSUE THREAD

**Issue by salvadorbs** [prime31/Nez#125]
As the title, I can subclass Entity and Component class and override their update() method, instead in Scene class I can't. Why this development choice?

**Comment by prime31** [comment]
The Scene lifecycle methods were made internal for 2 reasons:

1. to avoid them being called accidentally from user code
2. to ensure that they are always called

All of the Scene lifecycle methods (begin, end, update, preRender, render, postRender) perform important high-level operations that if called at the incorrect time (or not at all) could create very hard to track down bugs.

What is your use case for needing to override any of them? If you just need a tick each frame you can use the TimerManager via Core.schedule. All scheduled timers are called immediately before Scene.update.

**Comment by salvadorbs** [comment]
Ah ok. Perfect. It was just curiosity. :D

**Comment by RUSshy** [comment]
maybe make the internal update call a virtual or abstract method called postUdapte or preUpdate, so the user is feel to override it or no without worrying about update not called :p
