### ISSUE TITLE
PolygonCollider and ScrollingSprite

### ISSUE THREAD

**Issue by salvadorbs** [prime31/Nez#127]
Hello again, I'm making a Flappy Bird clone with Nez. This time I have an issue with ScrollingSprite and PolygonCollider. In short words, PolygonCollider doesn't follow ScrollingSprite, but while ScrollingSprite is moving, the collider doesn't move. See the example:
![2016-10-17_20-35-28](https://cloud.githubusercontent.com/assets/3731721/19450463/d179add6-94a9-11e6-854f-434d7d146e5f.gif)

Code (very simple :) ):
```
var _sprite = new ScrollingSprite(scene.content.Load<Texture2D>(Content.Terrain.groundGrass))
{
  scrollSpeedX = Constants.TerrainSpeed
};
addComponent(_sprite);
var collider = addCollider(new PolygonCollider(GetArrayVertices()));
```

Did I miss something? Did should I update manually collider position (!?) ?

Thank you very much for your patience

**Comment by prime31** [comment]
That is all how things are supposed to work. The ScrollingSprite is just modifying the UV coordinates of the image. It is meant for scrolling backgrounds and other such trickery. 

You'll actually want to move your Sprites and Colliders for your specific use case and perhaps use a ScrollingSprite for the background and have it scroll a bit slower than your foreground Entities.

**Comment by salvadorbs** [comment]
> You'll actually want to move your Sprites and Colliders for your specific use case and perhaps use a ScrollingSprite for the background and have it scroll a bit slower than your foreground Entities.
Mmm... no. I'm using two entities (with ScrollingSprite as sprite component) for background and terrain, respectively. Terrain entity must have a polygon collider because its shape :| . 

Anyway I fixed this issue using two polygon colliders in Terrain and set their local offset in method entity's update based of ScrollingSprite.scrollX. Maybe it isn't best solution, but it is simple and it works for simple and stupid game like mine.

**Comment by prime31** [comment]
That solution works as well. There are always lots of ways to solve any problem!
