### ISSUE TITLE
Verlet composites and how to render them / do collision detection

### ISSUE THREAD

**Issue by ThomasZeman** [prime31/Nez#128]
I am doing a few experiments with the verlet physics systems and cannot get my head around two (and a half) things:

- As far as I understood the composites and their particles are only visible due to debug rendering. What would be a reasonable way to render composites with e.g. textures or at least a solid color? How to add them as an entity?
- How can I make composites collide with each other? It seems to me they only collide with colliders which are attached to entities.
- What is the difference between or how do they complement each other: composites and the arcade rigid body simulation? Is it right to say the latter is a subset of the verlet simulation?

**Comment by prime31** [comment]
- that is correct. Verlet does not have any intrinsic rendering besides the debug rendering. It's purpose is for the simulation factor so it doesn't do any specific rendering. How you do your rendering will vary a lot with Verlet. The three most common examples I use are:
   - Verlet ball: display a circular Sprite that just updates its transform.position to match the Verlet Particle each frame.
   - Verlet ragdoll: the same concept but multiple Textures this time. The ball-head gets a texture, arms and legs and feet all get textures, etc. Using the arm as an example, the texture is just displayed at the midpoint between the shoulder and elbow and its rotation is set to the angle of the upper arm.
   - Verlet tire or other voluminous shape: you can grab the outside Verlet Particles and use the Mesh or PolygonMesh to display it. If the object is squishy you would need to update the verts each frame to match.
The general gist of it is to have a RenderableComponent subclass that understands the Composite and how it should be displayed. Something like below (with the details not filled in obviously):

```csharp
public class VerletThing : RenderableComponent, IUpdatable
{
	Composite _composite;
	
	public VerletThing( Composite composite )
	{
		_composite = composite;
	}
	
	public void update()
	{
		// grab info on positions from the Composite here that are needed for rendering
	}
	
	public override void render( Graphics graphics, Camera, camera )
	{
		// render any Textures required here
	}
}
```

- Composites dont collide with each other. That was a design decision made from the start of creating the Verlet system. I experimented with colliding Verlet bodies but the code was just prototype quality and there was a lot of work to get Verlet-to-Verlet and normal Collider-to-Verlet both working together seamlessly so it got dropped for now and just Verlet-to-Collider was left in place.

If approximated collisions are enough for you one thing you can do is just have a bounding circle for each Composite (circles are super fast and easy to collide) and when one circle overlaps another add a force in the opposite direction to all the Particles via the addForce method.

- The ArcadeRigidBody is indeed a Verlet-like collision under the covers just in rigid fashion. That is really the only similarity between them. The ArcadeRigidBody is there mainly for stuff like powerups that bounce around or a brick breaking with some debris that fades away after a second, etc.

**Comment by ThomasZeman** [comment]
Wow! Thank you for the detailed explanation! 

So:
- Verlet does not collide with Verlet
- Verlet does collide with normal Colliders
- Colliders do not collide with Verlets, rather, Verlets "move out of their way". So an ArcadeRigidBody would not be influenced by a Verlet composite.

What would be necessary to simulate some kind of trampolin then? Like a rigid body jumping on an elastic band?

Another point in the rigidbody simulation: I have noticed Transform rounds its position. When having entities with a low speed it can happen that they don't move at all because the delta of entity.transform.position += velocity * Time.deltaTime; is not greater than 0.5 in any component. What is the rational behind this decision?

**Comment by prime31** [comment]
Correct on all three counts. As for trampolines, how to implement them will vary based on the rest of your Entity movement code but the two most common ways I have used are:
- if you manage a velocity for your Entity, when you hit a trampoline apply an upward velocity in the normal fashion (something like sqrt 2 * desiredJumpHeight * gravity)
- if you don't store a velocity then just apply upward speed with an appropriate EaseType to simulate slowing down at the top and calculate with `Lerps.ease`.

If you want to fully simulate something bouncing on a trampoline over and over again without input then plain old Euler equations do the trick. 

By default Transform will round to int but you can override that behavior by just setting `Transform.shouldRoundPosition = false`. I considered managing the subpixel movement in there automatically but I feared it might have unintended consequences so tossed that idea out. I usually handle subpixel movement in my actual movers now. See the `TiledMapMover.CollisionState` for an example if you need that kind of thing.

**Comment by ThomasZeman** [comment]
Yes, I saw the static shouldRoundPosition. I wonder whether it would make sense to consider the transform position as exact position (Model) and then let the Renderer (View) decide what to take/render in regards to the actual output device - just as an idea.

However thank you so much for clarifying my questions. Maybe it's worth setting up a dicussion board?

**Comment by prime31** [comment]
At some point there will at least be a Gitter chat. That might be able to double as a discussion board but Gitter isn't great at history so it might not work.
