### ISSUE TITLE
NullReferenceException in EffectsResource.getMonoGameEmbeddedResourceBytes

### ISSUE THREAD

**Issue by BMStrom** [prime31/Nez#129]
When I try to run my game, I get a NullReferenceException in EffectsResource, as shown:

```
internal static byte[] getMonoGameEmbeddedResourceBytes( string name )
		{
			#if FNA
			name = name.Replace( ".ogl.mgfxo", ".fxb" );
			#endif

			var assembly = ReflectionUtils.getAssembly( typeof( MathHelper ) );
			using( var stream = assembly.GetManifestResourceStream( name ) )
			{
				using( var ms = new MemoryStream() )
				{
					stream.CopyTo( ms ); // this causes a NullReferenceException, because "stream" is null
					return ms.ToArray();
				}
			}
		}
```

Why is this happening?

**Comment by prime31** [comment]
Are you using an OpenGL/DesktopGL project? Nez only supports OpenGL and it will only attempt to load OpenGL shaders. Did you step through in the debugger to see where the NRE is occurring?

**Comment by BMStrom** [comment]
I just started an OpenGL project, and now it works. Thanks. For some reason I didn't realise that was required.

**Comment by cshiel** [comment]
Downside is there seems to be no way to build 64 with OpenGL.
