### ISSUE TITLE
Invalid Code in Wiki

### ISSUE THREAD

**Issue by Melon-Bread** [prime31/Nez#13]
Step one in the wiki has you passing in textures & entities to the wrong scene. You should be passing them into the **myScene** Scene you create rather than the Scene you get from **Core.scene**.  I was unable to compile the code in the wiki using the latest commit or the release version, until making this change.
  
Here is a image of the changes needed:  
![alt text](https://i.imgur.com/maMyVMD.png)  
  
(My apologies if I did not submit this correctly. I have no clue how to submit a pull request to a GitHub wiki.)

**Comment by prime31** [comment]
Good spot! All fixed now.
