### ISSUE TITLE
window.toFront() kills contained tooltips

### ISSUE THREAD

**Issue by ellisonch** [prime31/Nez#133]
The following code added to the bottom of SampleScene's constructor in Nez.Samples creates a small window with a button with a tooltip:

``` .cs
TooltipManager.getInstance().animations = false;

var window = new Window("window", Skin.createDefaultSkin().get<WindowStyle>());
window.pad(20, 5, 5, 5);
canvas.stage.addElement(window);

var table = new Table();
window.add(table);

var button1 = new CheckBox("name1", Skin.createDefaultSkin().get<CheckBoxStyle>());
table.add(button1);

var tt1 = new TextTooltip("name1", button1, Skin.createDefaultSkin().get<TextTooltipStyle>());
tt1.setInstant(true);
canvas.stage.addElement(tt1);
```

So far, everything works fine.  However, moving the window to the front with `window.toFront();` after the tooltip has been created causes the tooltip to stop working.  I tried looking into the code, but I couldn't figure out why this should affect tooltips.

**Comment by Vanit** [comment]
As tooltip isn't a child of window, `window.toFront()` causes it to be covered by the window. In this scenario you'd just need to call `tooltip.toFront()` afterwards to put it back in front:

~~~
window.toFront();
tt1.toFront();
~~~

I believe this issue can be closed :)

**Comment by ellisonch** [comment]
Doesn't it make sense for this to be done automatically?  It seems strange to require the user to bring all of a window's tooltips to the front manually whenever windows get moved to the front.

I don't have to move all of my buttons to the front just because I move a windows containing buttons to the front.  Etc.

**Comment by Vanit** [comment]
Oh it does work that way, but you need to make the tooltip a child of the window instead of the stage, then it will stay infront:

~~~
var tt1 = new TextTooltip( "name1", button1, Skin.createDefaultSkin().get<TextTooltipStyle>() );
tt1.setInstant( true );
window.addElement( tt1 );
~~~
