### ISSUE TITLE
Scaling TiledSprites

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#136]
Is it possible to scale a `TiledSprite` independently of the gameobject? 

I have created a simple parallax background that set its width, height, and origin based on the viewport

```cs
background.width = Core.graphicsDevice.Viewport.Width;
background.height = Core.graphicsDevice.Viewport.Height;
background.origin = new Vector2(background.width / 2, background.height / 2);
```

However, I would like to scale the tiled background to get a nicer parallax effect.  Unfortunately I can't do something like `transform.scale = 0.5f`, as it messes with my code above and makes the entire object smaller, and not fullscreen.

![image](https://cloud.githubusercontent.com/assets/8846211/19834935/8734ffa4-9e4b-11e6-800a-b0e2806c8ed8.png)

Is there a way to accomplish this in Nez save making separate PNGs at different scales or modifying / saving the Texture2D?  ([Here's the full class I'm working with](https://gist.github.com/piedoom/c3585b9f4e021466192a45e0ae9140b8)).

**Comment by prime31** [comment]
Try out the latest commit. It has some changes to TiledSprite and ScrollingSprite that let you set the textureScale.
