### ISSUE TITLE
mgfxo / deferred lighting problems

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#137]
I'm currently using Monogame 3.5 (like what was used in the samples repository) and I'm having trouble getting deferred lighting working while following [this tutorial](https://github.com/prime31/Nez/blob/master/FAQs/DeferredLighting.md).

I'll run through everything I've tried thus far and the results - 

First,  I copied the DeferredSprite / Lighting .fx source file from [here](https://github.com/prime31/Nez/tree/master/DefaultContentSource/effects).  I added it to my monogame pipeline, and set it to build an effect.

However, instead of an `mgfxo` file in my bin folder, i got a generic `xnb` file and received an exception.  

I then tried downloading the built fx files from the DefaultContent folder - just the MGFXO files already made.  However, the game ran and told me that the MGFX files are for an outdated version of monogame, and I needed to recompile.

I then tried using the 2MGFX tool monogame provides.  That got me further.  I was able to see a light glowing, but I first had to comment out lines 75 and 108 of [DeferredSpriteEffect.cs](https://github.com/prime31/Nez/blob/622178a05e967b32222e244120e4007a40a7de8d/Nez-PCL/Graphics/DeferredLighting/Effects/DeferredSpriteEffect.cs) because I was getting null references for an unknown reason.  I guess those were important because although I could see the point light, I could not see anything that was supposed to be rendered.

I think I did everything correctly - here's the pertinent code from the object I want to illuminate - 

```cs
Sprite = new Sprite(Core.content.Load<Texture2D>("ships/overwatch"));
Sprite.material = new DeferredSpriteMaterial(Core.content.Load<Texture2D>("ships/overwatch-normal"));
entity.addComponent(Sprite);
Sprite.renderLayer = Settings.Globals.OBJECT_LAYER;
```

and here's the scene -

```cs
addRenderer(new DeferredLightingRenderer(1, Settings.Globals.LIGHT_LAYER, Settings.Globals.OBJECT_LAYER));
var lightEntity = createEntity("point-light");
lightEntity.addComponent(new PointLight(Color.Red))
                .setRenderLayer(Settings.Globals.LIGHT_LAYER);
```

**Comment by prime31** [comment]
You shouldnt ever compile the shaders to xnb files. They are all OpenGL and will only work if they are compiled as such, placed in the correct folders and named exactly as Nez names them. It is much easier to just use the precompiled versions.

If you fetch the Nez.Samples repo it has a simple deferred lighting example that you can use to play around with and see how the Scene is composed. It uses only the precompiled effects linked directly from the repo to the project folders.

**Comment by piedoom** [comment]
Found the problem - 
For whatever reason, the MGFXO files will be "outdated" when referencing the monogame binaries created when using the Visual Studio installer on the Monogame site.  When I use Nuget instead, the files work correctly.  Not sure why, but hey, at least it's working now.
