### ISSUE TITLE
Running simulation without Renderer

### ISSUE THREAD

**Issue by ThomasZeman** [prime31/Nez#139]
I am working with Nez on some kind of networked multiplayer game and started thinking what would be necessary to run the simulation (entities, physics...) without a renderer? Would it just work to setup a scene, not add any renderer and have a running simulation in, for example, a console app?

**Comment by prime31** [comment]
I don't think you can run MonoGame at all in a console app without changing the source quite a bit. It always creates a Window at startup. The minimum viable Scene in Nez does require a Renderer but it can be a Renderer that doesn't actually render anything. If you don't have any RenderableComponents in your Scene it won't render anything at all. You can also just add a Renderer that renders a renderLayer you don't use like int.MaxValue or int.MinValue.
