### ISSUE TITLE
FollowCamera component doesn't work if Screen size is bigger than Scene size

### ISSUE THREAD

**Issue by rsredsq** [prime31/Nez#141]
FollowCamera component doesn't work properly if `Screen` size is bigger than `Scene` size. So with LockOn mode it gave incorrect camera position(entity wasn't centered), it should be dependent on scale.

**Comment by rsredsq** [comment]
it can be fixed by setting correct x,y position to deadzone. 
Like if we have Screen size twice bigger than a Scene size, we should divide x,y coordinates by 4(2*`scalesize`)
https://github.com/prime31/Nez/blob/master/Nez-PCL/ECS/Components/FollowCamera.cs#L199

**Comment by prime31** [comment]
The deadzone is already public and designed to be set from the outside. You can set it to whatever you would like.
