### ISSUE TITLE
Scene/UI/Camera/Sprite without ECS

### ISSUE THREAD

**Issue by RUSshy** [prime31/Nez#143]
Hello

Can you show me an example for using these stuff without ECS pls ?

I tried but each time i get some entity NullReferenceException :/

Thanks!

**Comment by RUSshy** [comment]
I'm porting libgdx game but i don't want to rewrite everything for ecs

**Comment by RUSshy** [comment]
it looks like everything is made for ECS, so your param ``enableEntitySystems`` is completly useless...

i don't think u should have made everything ECS, pls do like libgdx or monogame, let me make ecs or no, don't force

**Comment by RUSshy** [comment]
this is what i want to do: (pseudo code)

It is possible?

```c#
class game: Core
{
   init()
   {
     ..transition..to..scene..new Transition() .. new myScene()
   }	
}

class myScene : Scene
{

	var spriteBatch
	var camera
	var sprite
    
    var stage

	void init
	{
		camera = new Camera()
		spriteBatch = new SpriteBatch()
		
		sprite = new Sprite()
		sprite.position = 50,50
	
		stage = new Stage()
		stage.addElement(new Button("a button"))
	}

	void update
	{
        camera.position = sprite.position
        stage.act()
	}

	void render
	{
		spriteBatch.begin(view: camera.viewmatrix)
  		
  		sprite.draw(spriteBatch)

		spriteBatch.end()
	
		stage.render()
	}

}



```

**Comment by prime31** [comment]
The `enableEntitySystems` is most definitely not useless. If you took a few minutes to actually look at the source code you would find that it is used to enable/disable classic entity processing systems.

Nez will not work out of the box without it's entity component system. While you could manually call different Components update/render methods there are just piles of things that wouldnt work as they rely on the entity component system and Scene for various things.

If you do not want to use an entity component system or classic entity processing systems you are better off just using MonoGame directly. There is no point trying to use Nez
