### ISSUE TITLE
3D object lighting

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#144]
Is there a way to control the lighting for 3D objects, instead of the default lighting?

**Comment by prime31** [comment]
Sure. All 3D objects use the standard MG BasicEffect. You can either set the lighting manually or just replace the BasicEffect with your own custom shader and do whatever you want with the lighting.

**Comment by piedoom** [comment]
If I could bother you for some advice, what would be a good way of implementing this?  I'm still reading up on MG and Nez, but I'm a tad confused on how to use BasicEffect.

From [here](https://github.com/prime31/Nez/blob/e83235e6958492e35c93a508df413e47bffc4b1f/Nez.Portable/ECS/Components/Renderables/3D/Model3D.cs#L50) in the source code, it looks like a model is composed of meshes, and each mesh has a BasicEffect attached that dictates what to do to it. 

Would there be a way so that Nez's 2D scene lights can be mirrored by 3D lights?  Looking at this [guide](http://rbwhitaker.wikidot.com/basic-effect-lighting) it seems like BasicEffect is limited only to one light and a direction.

**Comment by prime31** [comment]
If you need a full fledged 3D lighting system there is no easy way to do it. You need to write custom shaders and make light objects with all the properties that you need and then you need to pass that data to your shaders. There is nothing in MonoGame built in for that.

**Comment by piedoom** [comment]
All right, thanks for the info.  I'll look into that!  There seems to be a few tutorials on point lights.
