### ISSUE TITLE
Just saying thank you.

### ISSUE THREAD

**Issue by wmccullough** [prime31/Nez#145]
No issues here, just stopping to say thanks for your hard work.

I've been playing with Monogame/XNA for years, but I never took any of my projects too far because I spent weeks and months getting collisions and rendering just right. Now I finally have a way to work on my project beyond having to do it all myself. I tried moving to Unity a few times, but found that the learning curve and associated issues with getting 2D tilemaps working correctly was more than I wanted to deal with.

In the span of just one hour of research and an hour of code, I have all my art, maps rendering and collision working. Nez is awesome! Keep up the good work!

**Comment by prime31** [comment]
Glad to hear Nez is working well for you! That is a ton of progress for such a short amount of time. Keep it coming!
