### ISSUE TITLE
Mesh component memory leak

### ISSUE THREAD

**Issue by james0x0A** [prime31/Nez#148]
A new instance of BasicEffect is created and cached in the NezContentManager when a Mesh is added to an entity, but that instance is never removed or unloaded.

**Comment by prime31** [comment]
Are you sure about that? Do you have some evidence to support the claim? I am seeing the BasicEffect instance not only have Dispose called but also the reference is nulled as well whenever a Scene changes. You can stick a breakpoint right [here](https://github.com/prime31/Nez/blob/master/Nez.Portable/Utils/NezContentManager.cs#L326) to see for yourself.

**Comment by james0x0A** [comment]
This naive brute force update method my scene leads to runaway growth of memory.    The cache is not cleared until the scene changes, so it will continue to accumulate unused instances of BasicEffect forever.
``` csharp
public override void update()
{
    base.update();
    Vector2[] tv = getVertices(particles: _tire.particles, subdivisions: 2);
    List<Vertices> partition = Triangulate.convexPartition(new Vertices(tv), TriangulationAlgorithm.Bayazit);
    List<PolygonMesh> meshes = tireEntity.getComponents<PolygonMesh>();
    foreach (PolygonMesh polygonMesh in meshes)
    {
        tireEntity.removeComponent(polygonMesh);
    }
    foreach (Vertices vertices in partition)
    {
        tireEntity.addComponent(new PolygonMesh(vertices.ToArray()).setColor(Color.CornflowerBlue));
    }
}
```

**Comment by prime31** [comment]
Aha! I see what you are doing. The Component wasnt designed with that use case in mind so Effect cleanup was deferred until the Scene was unloaded to avoid any garbage collection. The thought was Meshes would be created at Scene load time and not destroyed until the Scene was done. I'll push an update momentarily that will just unload the effect when the Component is removed.

**Comment by james0x0A** [comment]
Seems serviceable.   I intend to do this properly with a custom render component eventually, but for now I am just messing about, and this seemed the fastest way to get the result.
