### ISSUE TITLE
Help with correct layerDepth usage

### ISSUE THREAD

**Issue by Vanit** [prime31/Nez#150]
I can't for the life of me get this working correctly.

I have a player sprite whose layer depth I've set to 0.1f, and my custom tilemap renderable component is drawing each tile with a depth of 0.2f (once this issue is resolved the idea is to set the depth based on tile coordinates/layer, same for the player sprite, such that the overlapping is nicely handled). Both components are on the same render layer (0).

I've traced the draw calls through to the batcher and I can see the correct Z values are being assigned to _vertexInfo. I've tried adding my own renderer that changes the render material to use DepthRead as I thought that might be related.

Despite all this, I can't get my player sprite to render infront of the map unless its layerDepth is 0. What am I missing?

**Comment by Vanit** [comment]
I'm starting to suspect this feature is just missing. FNA's SpriteBatcher (https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/SpriteBatch.cs) can optionally do a sort on the Z values prior to sending them to be rendered. Nez has no sorting mechanism at all. Can this be added?

**Comment by prime31** [comment]
Sorting is indeed done at a higher up level. Sorting at the SpriteBatch layer is kind of a waste. It forces a sort for every batch and if a batch has to be flushed and another started then the entire sort will be wrong anyway!

Nez does it's sorting at the root of where the IRenderables are stored in the ComponentList. You should be able to just stick a breakpoint in there or in your renderer and have a look at the sorted list directly to ensure it is how you expect it to be.

You won't need anything depth related for the Material since everything is drawn in the order it should be rendered. SpriteBatch is backwards anyway with its 0 is in front of 1 thing so you need to depth sort in reverse with the depth buffer having a super shallow z-depth.

**Comment by Vanit** [comment]
Thanks for the reply, and I hear you on the SpriteBatcher.

In that case I'd appreciate your insight on the best "Nez" way to satisfy the use case. I want to render an isometric tilemap that correctly renders tiles in front or behind the player. Unlike regular orthogonal tilemaps I can't simply do it layer by layer, as the player will need to be in front and behind tiles in the same layer (ie when they're in a corner).

I can think of a few ways to solve this:

A) Make the tilemap component responsible for rendering the player aswell at the right time, mid map render
B) Make the tilemap split itself into multiple components that depend on regular layer sorting to be rendered around the player component (maybe 1 diagonal row per subcomponent). Could use layerDepth here as I also noticed its used for resolving competing render components in the same render layer.
C) Make a custom renderer that's renders the tilemap directly instead of a component, weaving the tiles around components in the same render layer

I'm not a fan of how A violates ECS, but it'd probably be the correct answer in a simpler engine. B seems like the easiest solution that leverages Nez, but it floods the renderable components. C seems like an acknowledgement that my usecase is fundamentally "un-Nez-like", and that's fine.

I'm leaning towards C. What are your thoughts?

**Comment by prime31** [comment]
That is indeed a very good question. I would avoid A since that will get to be a PITA with lots of moving Entities that need the same treatment. B could work but it would highly depend on how the map is layed out. It would probably be tricky to manage through. C doesn't feel ideal though it could work. It's probably the best of the bunch but still not perfect.

I'll have to give it some thought but what is jumping around in my head is to take advantage of the depth buffer for this. Have the iso tile Component render tiles with a layer depth (essentially just a z-value for the verts) that is based on the y-value of the tile. Any moving Entities would also render themselves at a z-depth based on their y-position. That would push all the work to the depth buffer when rendering to avoid having to submit tiles to the GPU in the correct order.

I'll give it some more thought and if I come up with something better I'll report back.

**Comment by Vanit** [comment]
Much appreciated! Well, the depth buffer thing was exactly what I was trying to achieve with my tilemap component setting a different depth for every tile in the batcher. Even without sorting, it seemed like it should be handled by the Z values, but for some reason I couldn't get it to work.

**Comment by Vanit** [comment]
A bit of extra information about my tilemap; it's layed out such that each layer only contains tiles that are visually on the same level, so you can use the layer index as a Z value for each tile.

**Comment by prime31** [comment]
Do you have a crew shot handy of the tile map?

**Comment by prime31** [comment]
Oops. Damn mobile autocorrect! *screenshot

**Comment by Vanit** [comment]
![untitled](https://cloud.githubusercontent.com/assets/852857/20870871/f20d3ba6-bada-11e6-9c49-5b11a387863a.png)

Yep, really basic test map.

**Comment by Vanit** [comment]
![2016-12-05_11h10_33](https://cloud.githubusercontent.com/assets/852857/20870916/9e924498-badb-11e6-92a3-193bec574d87.png)

Sorry to keep double posting, but it may be helpful if you know a bit about what I'm working on. My game converts the tilemap to a 3D representation (see the debug 3D render below), applies 3D physics (using BEPUphysics), and then transforms the 3D entities back to 2D. So my character can jump around in 3D space, climb on top of the blocks, and that shadow under him is being calculated from a 3D raycast.

**Comment by prime31** [comment]
OK. So, I assume the ground is one layer in the tilemap and the blocks are on a separate layer. Is that correct?

**Comment by Vanit** [comment]
Yep, exactly.

**Comment by prime31** [comment]
I just whipped up a small viability test for using the depth buffer and it could potentially work. I just created 2 Entities and stuck them in different renderLayers with a Material that takes depth into account (`new Material( DepthStencilState.Default )`). The layerDepth is set based on the y-position of the center of the Sprite.

If the rendered sprites are squares (ie they fill the entire quad they are rendered into) everything is peachy:

![block](https://cloud.githubusercontent.com/assets/60377/20871363/dcc61042-ba49-11e6-971a-8de59a33414a.gif)

Once we get alpha involved then we run into the issue of render order. If the front object (red in the gif) is rendered last but it is in front we run into the age old issue of sorting semi transparent objects (notice the gray obscuring the rear Sprite):

![moon](https://cloud.githubusercontent.com/assets/60377/20871384/03dc01f0-ba4a-11e6-83f3-98767f29765a.gif)

Sticking the SpriteAlphaTestEffect on the Material works around the issue just fine as long as the pixels of the Sprite are either alpha 0 or 1:

![moonfixed](https://cloud.githubusercontent.com/assets/60377/20871442/d72364f4-ba4a-11e6-9845-f28989c89f59.gif)


With some careful setting of the layerDepth it could be a viable solution. The full code for the hacky test is below:

```cs
		var effect = content.loadNezEffect<SpriteAlphaTestEffect>();
		var mat = new Material( DepthStencilState.Default, effect );
		var moon = content.Load<Texture2D>( "Images/moon" );

		createEntity( "first" )
			.addComponent( new Sprite( moon ) )
			.setMaterial( mat )
			.setRenderLayer( -2 )
			.setLayerDepth( 0.5f )
			.transform.setPosition( Screen.center );

		createEntity( "second" )
			.addComponent( new Sprite( moon ) )
			.setMaterial( mat )
			.setColor( Color.Red )
			.setLayerDepth( 0.5f )
			.addComponent( new SimpleMoonMover() )
			.transform.setPosition( Screen.center + new Vector2( 20 ) );

		Core.schedule( 0f, true, t =>
		{
			var sprite = findEntity( "second" ).getComponent<Sprite>();
			// this only sets layerDepth for Sprites in the range of 160 pixels from Screen.center!
			var depth = ( Screen.center.Y - sprite.entity.position.Y ) / 160 + 0.5f;
			sprite.setLayerDepth( depth );
			Debug.log( depth );
		});
```

**Comment by Vanit** [comment]
Thanks for getting back to me about this! I'll have a play with it and report back.

**Comment by Vanit** [comment]
Got it working partially with the material alone, but I'm having trouble loading the effect.

"OpenStream failed to find file at path: Content/nez/effects/SpriteAlphaTest.mgfxo. Did you add it to the Content folder?"

I can see the file in Nez DefaultContent folder, but is this supposed to work without my needing to move the file?

**Comment by prime31** [comment]
Nope. Any effects that you need you have to drag into your projects Content/nez/effects folder. You can just add it as a link and then set the build acton to "copy to output folder"

**Comment by Vanit** [comment]
![nez](https://cloud.githubusercontent.com/assets/852857/20874338/a83c17e6-bafc-11e6-9a72-a36830499a20.png)

Still having weird issues. Am I even in the ballpark here? I had to manually set the effect thing as by default it said missing.

**Comment by prime31** [comment]
You don't need to add the shader to the Pipeline tool. It's already compiled and ready for use. Here is the relevant snippet from the README setup section:

If you intend to use any of the built in Effects or PostProcessors you should also copy or link the DefaultContent/effects folder into your projects Content/nez/effects folder. Be sure to set the Build Action to Content and enable the "Copy to output directory" property so they get copied into your compiled game.

**Comment by Vanit** [comment]
Ah yep, finally worked it out. Thanks for bearing with me! My depth algorithm needs a bit of work, but otherwise it seems to work as advertised!

**Comment by prime31** [comment]
Excellent! Glad you've got a cleaner solution for this one than the initial 3 candidates.

**Comment by prime31** [comment]
Just remembered that Mathf.map01 would probably be a good fit for generating your layerDepths. You can feed it the map min and max and get back a value from 0-1.

**Comment by Vanit** [comment]
Appreciate the follow up! Somehow it totally slipped my mind to scale it as a percentage, I'm currently just doing 1 - depth / 10000 (where higher depth is closer to the camera).

Also after solving a few bugs that were throwing me off course, I eventually worked out that each tile's depth is simply x + y + z.

And with that I think this issue can be closed! Thanks again for your help, and for Nez of course. :)

**Comment by cshiel** [comment]
I am trying this but getting very sluggish performance in the sorting.

**Comment by Vanit** [comment]
@cshiel I ended up making a commit that allows you to do this via TiledIsometricTiledLayer.drawTile(). You need to create your own renderable component that calls it once per tile per layer. I haven't yet got around to supporting this better, but you're not the first person to ask me about it, might do something someday. :)
