### ISSUE TITLE
Deferred Rendering and entity rotation

### ISSUE THREAD

**Issue by gillesboisson** [prime31/Nez#152]
Hi,

I'm testing the deferred light rendered and I saw that entity rotation doesn't affect light direction on normal map, as data like sprite orientation normals are not sended to the shader, this is logical.
Do you plan implement that later on ? Or is there any way for to investigate on it on do pull request. 

Cheers,

**Comment by prime31** [comment]
Everything should work just fine with deferred rendering and rotated sprites. The normals are in the textures and when you draw a texture with a rotation both the diffuse texture and the normal texture are written to the g-buffer in the exact same manner.

You can see this by enabling debug rendering via the `DeferredLightingRenderer. enableDebugBufferRender` flag and sticking a couple rotating sprites in there.

**Comment by prime31** [comment]
Oh, wait a second. I see what you are saying. You want the actual normal read from the normal map to rotate. That makes sense. Basically, that would need the normal to be multiplied by the rotation matrix of the sprite after it is unpacked in the shader.

**Comment by gillesboisson** [comment]
Yes, it's quite handy for rotating object on scene, for now I hacked it a little bit by using a custom sprite with a custom effect. Use the color vector to store cos(-rotation) and sin(-rotation) and apply   rotation on normal map it seams as being the fastest solution. As I'm not an expert in nez and monogame I need to investigate more on it before doing something like a pull request. I also need drop shadow, I see what what i can do

**Comment by prime31** [comment]
That sounds like a perfectly reasonable way to handle things and as a plus it will keep batching working as expected.

**Comment by gillesboisson** [comment]
Yes definetely, I also render diffuse and normals in the same pass, it works perfectly with texture atlas when normal and diffuse are separated atlases and when atlases have the same kind of subtextures (same size, same amounts). I'll try adding drop shadow and do some perf test.

**Comment by gillesboisson** [comment]
`fx`

**Comment by Vanit** [comment]
I think its safe to close this issue.
