### ISSUE TITLE
Upgrading to new colliders with Visual Studio

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#154]
For ea8cd09c7c527caaa1ac2c6d74d43d5bfacf7a0c, I was having a few problems upgrading a current project.  I'm currently referencing the Nez csproj in my game, and I got the latest version via git.  Upon opening my project in VS, I get a few warnings -

```
[Failure] Could not find file 'C:\Users\alexa\Documents\Visual Studio 2015\Projects\Nez-Current\Nez.Portable\ECS\Components\Physics\CircleCollider.cs'.
[Failure] Could not find file 'C:\Users\alexa\Documents\Visual Studio 2015\Projects\Nez-Current\Nez.Portable\ECS\Components\Physics\CircleCollider.cs'.
[Failure] Could not find file 'C:\Users\alexa\Documents\Visual Studio 2015\Projects\Nez-Current\Nez.Portable\ECS\Components\Physics\CircleCollider.cs'.
[Failure] Could not find file 'C:\Users\alexa\Documents\Visual Studio 2015\Projects\Nez-Current\Nez.Portable\ECS\Components\Physics\BoxCollider.cs'.
[Failure] Could not find file 'C:\Users\alexa\Documents\Visual Studio 2015\Projects\Nez-Current\Nez.Portable\ECS\Components\Physics\PolygonCollider.cs'.
[Failure] Could not find file 'C:\Users\alexa\Documents\Visual Studio 2015\Projects\Nez-Current\Nez.Portable\ECS\Components\Physics\Collider.cs'.
[Failure] Could not find file 'C:\Users\alexa\Documents\Visual Studio 2015\Projects\Nez-Current\Nez.Portable\ECS\InternalUtils\ColliderList.cs'.
```

It looks like the source files for colliders has been moved into a folder named "Colliders", and the project can't find it (I also cannot seem to use things like BoxCollider etc.).   I just wanted to post this to make sure it was just an isolated issue, and that the `.csproj` file itself didn't have problems, if anyone can test it for themselves.

Looking at the csproj I actually don't see a reference to the files VS is complaining about, so perhaps I spoke too soon - probably my own project.  I'll take another look.  In either case I imagine this is a quirk VS users will run into when updating.  I'll post steps to solve once I figure it out.

**Comment by piedoom** [comment]
Update: After a bunch of cleaning and restarting VS, the problem has fixed itself.  I wish I could provide more information, but I guess either VS was being weird or I don't know how to use computers!

**Comment by prime31** [comment]
Visual Studio is sometimes a bit fiddly with csproj updates. Restarting it usually fixes the issue.
