### ISSUE TITLE
Player colliding with top of up-right slope

### ISSUE THREAD

**Issue by donkee** [prime31/Nez#155]
I started messing with Nez and followed your videos regarding tiled maps and player movement. My player is colliding on the right side at the top of a slope going up and right. If I hold the right arrow key, the player bounces back and forth against the top of the slope. My tiles and player are all 16x16 and I have the slopes' properties set at 15 top left and 0 top right. The opposite slope works perfectly. I _thought_ I followed your videos exactly but maybe not.

The image shows where the player stops moving in the right-direction.

![ss1](https://cloud.githubusercontent.com/assets/3387264/21070459/d6c97508-be4a-11e6-8ee3-7596bd6600fe.png)

PS - So far I am loving Nez!

**Comment by prime31** [comment]
This is an odd one. I'm surprised it works on the right but not the left! As just a shot in the dark try reducing your Collider size to 1 pixel less than your tile size. The TiledMapMover is still a WIP and it currently doesnt consider collisions for Colliders that are more than a tile width correctly. You can also get some debug visuals that might provide some insight by opening the TiledMapMover and uncommenting the define at the top. It displays some (sometimes) handy debug visuals.

**Comment by donkee** [comment]
Awesome, changing the player's collider to 14x14 seems to have solved it!

On a side note: do I need to be adding colliders in Tiled to all of my tiles or does Nez create them on the fly from the collision layer parameter of the TiledMapMover constructor?

**Comment by prime31** [comment]
The TiledMapMover actually doesn't use Colliders at all! It just examines the Tiled data directly to handle all collisions so you don't need to do a thing with Colliders.

On a side note, if you do need Colliders for your tilemap Nez can create them for you but it currently only optimizes full tiles (i.e. It doesn't make polygons for slopes).

**Comment by donkee** [comment]
So how would I do a sloped ceiling where the player could collide with it just like a sloped floor, but inverted?

**Comment by prime31** [comment]
Sloped ceilings should partially work out of the box. There is a hack in the TiledMapMover that just does an small offset if a ceiling collision occurs. You can follow along with the same logic as the sloped floor tile collisions to add proper sloped ceiling tile collisions.
