### ISSUE TITLE
Unable to set CircleCollider origin

### ISSUE THREAD

**Issue by drock07** [prime31/Nez#156]
With the latest version of Nez, I've noticed you've removed the constructor on `CircleCollider` that allows you to set both the radius and the origin. It also seems like you've removed the `originNormalized` property for `Collider`. I'm not sure how I can have a custom radius for a `CircleCollider` now, as the origin defaults to (0, 0) which isn't what I want. 

Is there a new way to have a custom radius circular collider?

**Comment by prime31** [comment]
You can set the localOffset and radius via the setter functions. Just pull the latest version as a bug with Circle and BoxCollider auto sizing was just fixed.

```cs
entity.addComponent<CircleCollider>()
	.setRadius( 10 )
	.setLocalOffset( new Vector2( 50, 0 ) );
```

**Comment by drock07** [comment]
Ah, there we go. Thanks!
