### ISSUE TITLE
Getting the Collider of a collision with tiled components

### ISSUE THREAD

**Issue by yaegerbomb** [prime31/Nez#158]
I have implemented a "grabbing platform" method as seen here: [https://www.youtube.com/watch?v=Ah4KtA6kwb4](https://www.youtube.com/watch?v=Ah4KtA6kwb4)

The problem with this is that I had to modify the tiled component provided by Nez to make the colliders accessible, then loop through he colliders and determine which one my collision state was bumping up against. I'd prefer to not have to modify any of the code in the project to do this though. 

Is there an easy[ier] way to get the collider my entity is bumping up against? I am using TiledComponent and TiledMapMover but reading over these two classes doesn't seem to give me an obvious way unless I am missing something?

```
var tiledEntity = scene.findEntity("tiled-map-entity");
var tileComponent = tiledEntity.getComponent<TiledMapComponent>();

//this is bad and I feel bad about it
var colliders = tileComponent._colliders;
	
foreach(var collider in colliders)
{
	if (boxCollider.bounds.right == collider.bounds.left)
	{

		if(collider.bounds.top - boxCollider.bounds.top > 0 && collider.bounds.top - boxCollider.bounds.top < forgivenessFactor)
		{
			//logic to lock player in place
		}
	}
}
```

Also - I have really enjoyed making everything so far with Nez so thank you for this awesome code contribution.

**Comment by prime31** [comment]
Glad to hear you are liking Nez so far!

The TiledMapMover actually doesn't use Colliders at all. It uses the raw data from the Tiled map to handle all collisions.

That being said, if you do ever have the need to query the world for a Collider you can use the Physics.linecast/overlapCircle/overlapRectangle/boxcast methods to fetch them.

**Comment by yaegerbomb** [comment]
I think I originally tried to do the Physics.linecast to get the collider in front of my player entity but it never seemed to hit the colliders the TiledComponent's sets up. Though I could've been missing something. I will re-implement and double check on that though since I've spent a good part of the day going over a lot of the source code to get a better understanding on how that works.

**Comment by prime31** [comment]
linecast does require that your line starts outside of a Collider to find it so that's something to look out for. For your case an overlap* is probably even easier. Just take your player Colliders bounds and shift it in the direction of the collision.

**Comment by yaegerbomb** [comment]
Overlap worked beautifully. Thanks for the help!

**Comment by prime31** [comment]
Glad to hear it worked for you! Keep plugging away!
