### ISSUE TITLE
Animations created via TextureAtlas seem to be missing a frame

### ISSUE THREAD

**Issue by meowgoocat** [prime31/Nez#16]
I have a TextureAtlas containing 8 frames, but only 7 are added to the animation created through getSpriteAnimation().

Changing the for loop from this
`for( var i = point.X; i < point.Y; i++ )
					animation.addFrame( subtextures[i] );`
to this
`for( var i = point.X; i <= point.Y; i++ )
					animation.addFrame( subtextures[i] );`

Seemed to have fixed the issue for me.

**Comment by prime31** [comment]
That should indeed be inclusive and not exclusive like it is.
