### ISSUE TITLE
System.MissingMethodException when running on OS X

### ISSUE THREAD

**Issue by parkersprouse** [prime31/Nez#162]
First off, I apologize if my issue isn't appropriate for posting here. I'd be happy to redirect it elsewhere.

So, I'm trying to make a MonoGame project using Nez on Mac that can also be worked on and shared between a Windows PC. I have MonoGame version 3.6.0.1236, the most recent as of this writing, installed.

I create the project on my Mac using the DesktopGL template and run the project to make sure it works properly, and it does. I get the cornflowerblue window.

Then I add the Nez project to my solution, reference the Nez project from my main project, and make the appropriate changes to my Game1.cs file, such as extending from `Core` instead of `Game` and gutting the skeleton code. I don't make any other changes to the project.

Now when I try to run the project, I get a `System.MissingMethodException` error, referencing the method `Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount` and it fails to start. But I don't understand why, or how to fix it since that's pointing to something in XNA that clearly isn't missing when it runs without Nez. But Nez doesn't change anything with the XNA/Monogame library.

Here's the full stacktrace:
```
System.MissingMethodException: Method 'Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount' not found.
  at Microsoft.Xna.Framework.Game.DoDraw (Microsoft.Xna.Framework.GameTime gameTime) [0x00022] in <63f25ffa523943d79d93c2acd55d64f1>:0
  at Microsoft.Xna.Framework.Game.Tick () [0x00221] in <63f25ffa523943d79d93c2acd55d64f1>:0
  at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop () [0x00021] in <63f25ffa523943d79d93c2acd55d64f1>:0
  at Microsoft.Xna.Framework.Game.Run (Microsoft.Xna.Framework.GameRunBehavior runBehavior) [0x0008a] in <63f25ffa523943d79d93c2acd55d64f1>:0
  at Microsoft.Xna.Framework.Game.Run () [0x0000c] in <63f25ffa523943d79d93c2acd55d64f1>:0
  at ProjectDruid.Program.RunGame () [0x00010] in /ProjectDruid/ProjectDruid/ProjectDruid/Program.cs:28
  at ProjectDruid.Program.Main (System.String[] args) [0x00001] in /ProjectDruid/ProjectDruid/ProjectDruid/Program.cs:52
```

If this is an error anyone else has seen, or if it's an error with my personal configuration that can be solved, I'd be beyond grateful for any help.

**Comment by prime31** [comment]
Have a look at the discussion in the Gitter chat [here](https://gitter.im/Nez-Devs/Lobby?at=586a9a58af6b364a2921e3ae). It has a full explanation of the MonoGame 3.6 changes and potential fixes to keep things happy until MonoGame 3.6 is officially released and Nez is updated to support it.

**Comment by jaxspades** [comment]
I'm having the same issue still, with the released 3.6, do we still have to use the workaround?

**Comment by RUSshy** [comment]
Can port Nez to Ultraviolet please? https://github.com/tlgkccampbell/ultraviolet it is so much better than buggy monogame

**Comment by parkersprouse** [comment]
@jaxspades For the moment, I believe so. prime31 said that Nez currently isn't written to fully support 3.6 yet (even though it does for the most part) and that he's waiting for 3.6.1 to come out before he puts the work in to make Nez fully support the new Monogame version. He said he does it like this because the initial release of a new Monogame version is always buggy, so he waits for the first patch before adapting it.
