### ISSUE TITLE
Correct way to use Graphics.instance.batcher

### ISSUE THREAD

**Issue by mohammadfoda** [prime31/Nez#163]
Hi,

I currently have a few custom geometric shape types defined that require rendering. By subclassing these types from `RenderableComponent` I'm able to override `render` and do all needed rendering needed via `graphics.batcher.draw`

In trying to keep with the ECS design of Nez, I moved the visual properties of these shapes into a `Shape` component and defined a `ShapeRender` system that processes matching entities. However, calling `batcher.draw` inside `process` is not working as nothing is getting rendered on the screen anymore.

This is what my `ShapeRender` system looks like:

```csharp
 class ShapeRender : EntitySystem
    {
        public ShapeRender(Matcher matcher) : base(matcher)
        {
        }

        protected override void process(List<Entity> entities)
        {
            var batcher = Graphics.instance.batcher;

            batcher.begin(Core.scene.camera.transformMatrix);

            foreach (var entity in entities)
            {
                var shape = entity.getComponent<Shape>();
                switch (shape.shapeType)
                {
                    case ShapeType.Circle:
                        var collider = shape.getComponent<CircleCollider>();
                        batcher.drawCircle(entity.position, collider.radius, Color.DarkRed);
                        break;
                }
            }

            batcher.end();
        }       
    }
```

I made sure that the system is added with correct filtering and that `process` is being called but still no luck. 

Any idea what I'm missing?

Thanks in advance

**Comment by Vanit** [comment]
@prime31 may need to correct me here, but I think this is the wrong approach. If you want to take a global approach to rendering like that you should subclass Renderer and add it to the scene as per https://github.com/prime31/Nez/blob/master/FAQs/Rendering.md

**Comment by mohammadfoda** [comment]
@Vanit Thanks. I'll take a look at that and give it a try.

Though this does seem to be the approach used for debug rendering as far as I can see here:
https://github.com/prime31/Nez/blob/master/Nez.Portable/Debug/Debug.cs

**Comment by mohammadfoda** [comment]
I guess more generally the question is, what is the correct way to call `Graphics.instance.batcher.draw` from methods like `Entity.process` or `IUpdatable.update`? Calling it inside 'RenderableComponent.render' works fine so I must be missing something.

**Comment by prime31** [comment]
You can't call any rendering methods in the update loop. The rendering system isn't prepared for rendering at that point. First update is called, then the rendering system is prepped, then render is called on all RenderableComponents. It is only at that point that rendering can occur.

**Comment by mohammadfoda** [comment]
@prime31 Thanks for the clarification. I'll just go with a `RendereableComponent` then.

Really awesome work with the library and the samples btw. I'm building a basic vector/shape editor so hopefully I'll end up with something to share on the samples repo.

Please feel free to close this.
