### ISSUE TITLE
LibGdxAtlas / NinePatch / Nez.UI

### ISSUE THREAD

**Issue by eumario** [prime31/Nez#170]
Looking through the source code, the Nez.ContentPipeline doesn't properly import padding from an atlas file for Nine-Patch, which causes certain UI Elements not to be properly drawn, such as a Progress bar, that has thick borders on the left and right.  Have to manually set padding through getting the skin element, getting the background Nine-Patch, and then manually setting the Padding to be proper values.  This should be referenced from the LibGdxAtlas to allow inset of elements.

**Comment by prime31** [comment]
Feel free to send over a pull request. I personally don't use padding and haven't come across anytime else that does so it was never implemented in the importer or runtime.

**Comment by eumario** [comment]
Done, and done. ;-)
