### ISSUE TITLE
Unable to build Nez.PipelineImporter in Xamarin Studio 6.1.4

### ISSUE THREAD

**Issue by Kharion** [prime31/Nez#174]
When building Nez everything goes fine until Nez.PipelineImporter build. The first crash occours on TiledMapImporter on using Microsoft.Xna.Framework.Content.Pipeline

Error CS0234: The type or namespace name 'Pipeline' does not exist in the namespace 'Microsoft.Xna.Framework.Content' (are you missing an assembly reference?) (CS0234) (Nez.PipelineImporter)

**Comment by prime31** [comment]
It sounds like your IDE didn't actually download the NuGet references which include one for the MonoGame Pipeline classes. Just force a NuGet refresh in your IDE so that it downloads them.
