### ISSUE TITLE
Spelling error in docs

### ISSUE THREAD

**Issue by jbhaywood** [prime31/Nez#175]
Minor spelling issue here: 
http://prime31.github.io/Nez/documentation/systems/ai

> // we can now add any additional states
_machine.addState( new AttackState() );
_machine.addState( new ChaseState() );

"_machine" should be "machine".

**Comment by jbhaywood** [comment]
Some more here:
http://prime31.github.io/Nez/documentation/systems/content-management

> Each scene has it’s own...

"it's" should be "its".

> // after using the ContentPathGenerator you will have compile-tile safety for your content

"compile-tile" should be "compile-time".

> var tex = content.Load<Texture2D>( Content.Textures.Scene1.blueBird" );

No quotation mark after "blueBird".

**Comment by jbhaywood** [comment]
BTW, great system. I'm just a nitpicker. :)

**Comment by Vanit** [comment]
You're better off just making a pull request if you think you've found a simple improvement like this.

**Comment by jbhaywood** [comment]
Good suggestion. I'll do that.
