### ISSUE TITLE
NullReference Exception when using Labels.

### ISSUE THREAD

**Issue by fusspawn** [prime31/Nez#18]
trying to start using the Nez.UI stuff.

made a simple component to display some basic labels.

`
    

    public class TileStats : Component , IUpdatable
    {
        private UICanvas Canvas;
        private Table Layout;
        private Label XLabel;
        private Label YLabel;
        private Label BaseTypeLabel;
        private Label DetailTypeLabel;
        private Label Walkable;

        public override void onAddedToEntity()
        {
            
            Canvas =(UICanvas) entity.addComponent<UICanvas>();
            Canvas.renderLayer = 999;
            Layout = new Table();
            XLabel = new Label("X: ");
            YLabel = new Label("Y: ");
            BaseTypeLabel= new Label("Base Type: ");
            DetailTypeLabel = new Label("Detail Type: ");
            Walkable = new Label("Walkable: ");

            Canvas.stage.addElement(Layout);

            Layout.addElement(XLabel);
            Layout.row();
            Layout.addElement(YLabel);
            Layout.row();
            Layout.addElement(BaseTypeLabel);
            Layout.row();
            Layout.addElement(DetailTypeLabel);
            Layout.row();
            Layout.addElement(Walkable);
            Layout.row();
        }
        

        public void update()
        {
            TileData Data = ChunkManager.MouseTile;

            if (Data != null)
            {
                XLabel.setText("X: " + Data.TileX); //int
                YLabel.setText("Y: " + Data.TileY); //int
                BaseTypeLabel.setText("Base Type: " + Data.TileBaseType); //int
                DetailTypeLabel.setText("Detail Type: " + Data.TileDetailType); //int
                Walkable.setText("Walkable: " + Data.IsTileWalkable); //bool
            }
        }
    }`

throws a null reference exception in Label.cs in the update layout method. 
 on this line: 

`	if( isWrapped || _wrappedString.IndexOf( '\n' ) != -1 ) `

_wrappedString is always null :/

this is the only component in the project using Nez.UI.

**Comment by fusspawn** [comment]
The full project is on Github at: https://github.com/fusspawn/monofarm if you want to look further.

**Comment by prime31** [comment]
Minor little mistake that isnt very well documented (by Nez or libGDX) going on here. When you add your UI elements to the Table you have to use `Layout.add`. In the example you used `Layout.addElement`. The difference here is that `add` puts the elements in cells in the table and they take part in layout. `addElement

**Comment by fusspawn** [comment]
Aha! thanks @prime31
