### ISSUE TITLE
EntitySystem's "update" vs "lateUpdate"

### ISSUE THREAD

**Issue by jbhaywood** [prime31/Nez#187]
I just spent some time debugging an issue where removing a component didn't immediately stop it from being processed in the system that cared about it. I eventually figured out the order of operations...

1. Remove component (marks it for removal)
2. Scene calls .update on all systems (component hasn't been removed yet)
3. Scene updates entities (where the component is actually removed)
4. Scene calls .lateUpdate on all systems (component has been removed and is not processed)

From an API design standpoint, I feel like that's counter-intuitive. I had come across the update and lateUpdate methods, but there aren't any comments explaining why I would use one over the other, so I just didn't think much about it until hitting this issue.

So I'm curious about the thinking behind this structure. What's the use case for wanting to process a component in a system even though it's been marked for removal?

**Comment by prime31** [comment]
I honestly don't use lateUpdate as it was added for someone else so I can't tell you the specifics of the use case. There was some discussion in either Issues or the Pull Request (I don't recall which) that probably has more information on why a lateUpdate was requested.

**Comment by jbhaywood** [comment]
Interesting. I found the PR from @Eendhoorn [here](https://github.com/prime31/Nez/pull/74). He just mentions needing it, but not specifically why. And spelunking through the Monogame thread, I found the original conversation [here](http://community.monogame.net/t/nez-free-open-source-2d-framework/7010/35). But still no details on `lateUpdate`.

Anyway, my main point was actually that I didn't know why anyone would use `update`. :) Since `lateUpdate` ensures that my entities are up to date and that removed components won't get processed, that's the one I'll be using.

Thank!

**Comment by Eendhoorn** [comment]
LateUpdate was added because some components require updating after the main updates have been completed,  thus a "LateUpdate".  Often used for camera stuff to prevent some jitter. I also use LateProcess and LateUpdate for my own physics system.

**Comment by jbhaywood** [comment]
Thanks for chiming in. I might add some method summaries and submit a PR, for posterity.
