### ISSUE TITLE
Ide Policy file for Nez naming conventions

### ISSUE THREAD

**Issue by mohammadfoda** [prime31/Nez#188]
Hi,

Just wanted to share a [.mdpolicy file](https://gist.github.com/mohammadfoda/708a356d49febbb8889e5862f07b3403) for Nez that can be used to set naming conventions in Visual Studio and Xamarin Studio per project.

There's also a short snippet [here](https://stackedit.io/viewer#!provider=gist&gistId=76c9bf2dcd95546b9a7ffaccc6dd583b&filename=Nez+Naming+Conventions) with some examples.

Here is a preview of the naming conventions which I created based on Nez source code.

<img width="1011" alt="screen shot 2017-02-14 at 11 21 14" src="https://cloud.githubusercontent.com/assets/23182653/22913837/28fb97c0-f2a8-11e6-91eb-2c32dd876bcd.png">

Please feel free to use these if they're helpful in any way you'd like.

And again, thanks for all the awesome work on Nez :-)

**Comment by prime31** [comment]
I just added the file in the root of the repo next to the code formatting mdpolicy file.
