### ISSUE TITLE
TextField Carret doesn't take into account letter spacing

### ISSUE THREAD

**Issue by RUSshy** [prime31/Nez#196]
Hello

Here is exagerated the spacing (4f), the carret is positioned at the end of the text, but rendering is wrong

![theroguer game_2017-02-22_17-07-33](https://cloud.githubusercontent.com/assets/18348637/23220221/86c5e6f6-f921-11e6-94f7-5f5c47de777a.png)

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
