### ISSUE TITLE
TiledSprite disappears on camera movement

### ISSUE THREAD

**Issue by mohammadfoda** [prime31/Nez#199]
I'm trying to add a background line grid that spans infinitely in all directions. Using a small grid sprite I'm able to have it tile the screen using a TiledSprite:
```csharp
var sprite = new TiledSprite(texture)
			{
				width   = Core.graphicsDevice.Viewport.Width * 5,
				height  = Core.graphicsDevice.Viewport.Height * 5,
			};
```

However, with the grid located at (0,0) and covering the whole viewport, panning the camera in either of the four directions makes the grid disappear, although at different breakpoints for each direction.

Is using TiledSprite the correct way to achieve what i'm trying to do?

**Comment by prime31** [comment]
It sounds like what you would want to do for an infinite background like that is to have a Sprite tiled the size of the background but parent it's Entity to the Cameras Entity. That way it always fills the screen. To get a scrolling effect you could then just scroll the UVs of the background Sprite in the opposite direction that the camera moves.

**Comment by mohammadfoda** [comment]
Thanks a lot @prime31. That worked!

Here's the code if anyone needs it:

This creates the TiledSprite:
---
```csharp 
void addGrid()
		{
			var viewPort = Core.graphicsDevice.Viewport;

			var texture = content.Load<Texture2D>("Images/grid");

			var sprite = new TiledSprite(texture)
			{
				width = viewPort.Width,
				height = viewPort.Height,
			};

			sprite.setOrigin(new Vector2(viewPort.Width, viewPort.Height));
			sprite.setRenderLayer(999);

			var grid = createEntity("grid")
				.setParent(camera.entity)
				.setLocalPosition(new Vector2(viewPort.Width / 2, viewPort.Height / 2));
			
			grid.addComponent(sprite);
		}
```

And scrolls it when the camera pans:
---
```csharp
void scrollGrid(GestureSample pan)
{
	sprite.scrollX -= (int)pan.Delta.X;
	sprite.scrollY -= (int)pan.Delta.Y;
}
```
