### ISSUE TITLE
SceneResolutionPolicy isn't applied

### ISSUE THREAD

**Issue by Async0x42** [prime31/Nez#2]
I'm just following along with the video tutorials, however no policy is ever applied to the game window (as seen in the screenshot below).

I'm running Windows 10 with MonoGame 3.4 nugets in a Cross Platform Desktop Project.

![image](https://cloud.githubusercontent.com/assets/3268854/13039327/7963b36c-d36b-11e5-8724-4f73039a7bac.png)

**Comment by DoctorB** [comment]
This is not a clean solution, it is just a workaround only for windows platform
on your constructor:

```
Window.AllowUserResizing = true;
Window.ClientSizeChanged += Window_ClientSizeChanged;
```

and on ClientSizeChanged:

```
    private void Window_ClientSizeChanged(object sender, EventArgs e)
    {
      emitter.emit(CoreEvents.GraphicsDeviceReset);
    }
```

**Comment by Async0x42** [comment]
Thanks, the workaround is perfect for now.

**Comment by prime31** [comment]
Ahh. Yes. There is no cross platform way to get at the Window object in a PCL yet. I haven't come up with a clean way to deal with this one. Once SDL2 is in MonoGame this becomes much easier. What you could do for now is very similar to what @DoctorB mentioned:

    Window.ClientSizeChanged += Core.onClientSizeChanged;

The onClientSizeChanged is going out in the next push. I'll update the README as well.
