### ISSUE TITLE
Transparent sprite occludes tilemap

### ISSUE THREAD

**Issue by Vanit** [prime31/Nez#200]
Hoping you can set me on the right path here as I'm a little stumped. I'm using sprites to do basic isometric shadows and the transparency seems to work Sprite to Sprite, but not Sprite to tiledmap component. I suspect that the tiledmap component needs a material assigned to it for it to work, but assigning the normal SpriteAlphaTestEffect + DepthStencilState.Default appears to have no effect. Any ideas?

![2017-02-25_09h22_36](https://cloud.githubusercontent.com/assets/852857/23324860/6c5d9fee-fb3c-11e6-9154-f572be794699.png)

**Comment by prime31** [comment]
I'm not quite sure what I am looking at here but I can say that tile maps are drawn with plain old Batcher.draw calls so they work exactly like any other sprites. Most likely the draw order of stuff would be what you need to look at for blending issues.

**Comment by Vanit** [comment]
Turns out the issue was as simple as setting the tiledmap component on a higher renderlayer. In researching Z buffers and alpha blending I'd gone too far down the rabbit hole and missed something as simple as that, oh well.

Not really worth explaining the setup now the issue is resolved, but your reply was enough anyway. :)
