### ISSUE TITLE
Game state managment with coroutines

### ISSUE THREAD

**Issue by yaegerbomb** [prime31/Nez#205]
Right now I have an animation component that has event data baked into it. It basically scans the timeline of the current animation and looks for any events that the animation will fire off. It then will create a coroutine to send that event.

Looking at the coroutine manager and class - there doesn't seem to be an apparent way to pause or delay it. I could recall the coroutine if the game state isn't correct but then there would be a delay. Any suggestions how to handle this case?

What I have currently done is:

1) add a bool to the CoroutineManager class

`public bool pauseCoroutines = false;`

2) add check in update method inside CoroutineManager class

```C#
void IUpdatableManager.update()
{
        if (!pauseCoroutines)
        {
             ...
        }
}
```

3) Make the _coroutineManager variable in Core.cs to be public

`public CoroutineManager _coroutineManager = new CoroutineManager();`

3) Query CoroutineManager form global manager function and set pauseCoroutines to true

`Game1.getGlobalManager<CoroutineManager>().pauseCoroutines = true;`

The problem with this is that it will stop all coroutine from working (if I need one for the pause state for whatever reason). But I could also just create a new coroutine manager and use that for the pause state... However I'd prefer to not modify your code so that I can pull any new changes without issues.

**Comment by prime31** [comment]
You cant pause the CoroutineManager itself but you can pause any Coroutine by just yielding a float which will be the seconds to pause.
