### ISSUE TITLE
[Suggestion] Draw complex meshes with drawRaw

### ISSUE THREAD

**Issue by RUSshy** [prime31/Nez#206]
Hello

Currently i can only render a single quad using drawRaw

Would be cool if can draw complex stuff like a custom tilemap

Thanks!

**Comment by prime31** [comment]
The Batcher purpose is drawing quads. It is optimized for that specifically. If you want to draw something like a whole tilemap you'll want to be using something better suited like the Mesh class which will store all the verts statically.
