### ISSUE TITLE
Dangerous results with Scene.findEntitiesWithTag()

### ISSUE THREAD

**Issue by jbhaywood** [prime31/Nez#207]
I just spent a good amount of time tracking down a really strange bug in my game where one of my entities could no longer be found by its tag. I set breakpoints in all the places that the EntityList could possibly remove an item from the its internal tag dictionary (_entityDict), but no luck.

Turns out that Scene.findEntitiesWithTag() returns the _actual list_ stored in _entityDict. I wasn't expecting that at all so I was unwittingly modifying its contents after finding the entities. Seems like the fix would be to make Scene.findEntitiesWithTag() return a new list rather than the one used to keep track of tags internally.

I don't think this is a problem with Scene.entitiesOfType<T>() because it uses the ListPool and effectively returns a new list.

If that sounds like a reasonable fix I'll go ahead and do a PR.

**Comment by prime31** [comment]
Going with a ListPool return would probably be a good plan. That will keep allocations to a minimum and provide the added layer of safety.
