### ISSUE TITLE
NullReferenceException in EffectResource.cs

### ISSUE THREAD

**Issue by 5argan** [prime31/Nez#209]
On Windows 8.1, Visual Studio 2015, using Monogame 3.5.1 I encountered an error building an empty monogame project using nez.
I created a default monogame project, added the Nez.csproj from \Nez-master\Nez.Portable, subclassed Core with my Game1 class and removed everything but the initialize method (and the constructor).
When trying to build this project, I get a NullReferenceException at line 81 in Nez.EffectResource:getMonoGameEmbeddedResourceBytes.
This seems to happen because of the statement `var stream = assembly.GetManifestResourceStream( name )` returning null therefore breaking at the point of copying the stream.

Unfortunately I am unable to get rid of this error but I'd really like to get working with nez.
I also tried monogame version 3.6 but since it gave this error I thought maybe nez doesn't work with that version yet, so I downgraded to 3.5.1 which unfortunately did not fix the error.

**Comment by prime31** [comment]
If you don't choose an OpenGL project template Nez will not be able to load any Effects. All Effects are compiled for OpenGL only.

**Comment by 5argan** [comment]
Thank you, choosing the cross platform template fixed it. This honestly didn't cross my mind and might be helpful to add to the readme for windows newcomers to nez like me.

**Comment by prime31** [comment]
Copy/pasted from the README ;)

"All Nez shaders are compiled for OpenGL so be sure to use the DesktopGL template, not DirectX! Nez only supports OpenGL out of the box to keep things compatible across Android/iOS/Mac/Linux/Windows."

**Comment by 5argan** [comment]
Okay, I guess I'm just really really blind then. Thanks for your help!

**Comment by jbhaywood** [comment]
This isn't the first time this has been brought up. See also #61. I think making this part of the setup more prominent in the documentation would be helpful.

**Comment by c0013r** [comment]
Just installed samples. On my I have "Microsoft.Xna.Framework.**Platform**.Graphics.Effect.Resources.SpriteEffect.ogl.mgfxo". Simply changed this name and all work.
