### ISSUE TITLE
Timing issue when starting scenes that contain ArcadeRigidBodies

### ISSUE THREAD

**Issue by HenrySipp** [prime31/Nez#21]
So I've noticed that when I start a scene that contains an ArcadeRigidBody as the game's default scene sometimes the Entity spawns in convoluted and awkward positions. 

IF I give the game a wait period before entering the scene, or we enter the scene from another scene, everything works as intended.

Some example code hopefully to illustrate my issue:

`   public class Character : Entity
    {

        private string avatarTexture;
    	public Character (string textureName, int health = 10, int mana = 10, int walkspeed = 1) :base()
    	{
    		avatarTexture = textureName;
    	}

    	public override void onAddedToScene ()
    	{
    		var texture = scene.contentManager.Load<Texture2D> ("bin/MacOSX/" + avatarTexture);
    		addComponent (new Sprite (texture));
    		addComponent (new FollowCamera (this));
    		addComponent (new CharacterController2D ( ));
    		colliders.add (new BoxCollider ());
    		base.onAddedToScene ();
    	}
    }

    public class TiledMapScene : Scene
    {

    	Entity _player;
    	public TiledMapScene (string mapName)
    	{

    		addRenderer( new DefaultRenderer() );

    		var map = contentManager.Load<Nez.Tiled.TiledMap> ("bin/MacOSX/" + mapName);
    		var objects = map.getObjectGroup ("Objects");
    		var spawn = objects.objectWithName( "spawn" );

    		var wall = createEntity ("tiled-map");
    		wall.addComponent (new TiledMapComponent (map, "Collision"));
    		wall.getComponent<TiledMapComponent> ().tiledmap.getLayer ("Collision").visible = false;

    		_player = new Character ("mage001");
    		_player.transform.position = new Vector2 (spawn.x, spawn.y);
    		addEntity (_player);

    	}
    }

    public class Game1 : Core
    {

    	Scene.SceneResolutionPolicy policy;

    	public Game1 () : base (640, 360, false, true)
    	{ 
    		policy = Scene.SceneResolutionPolicy.NoBorderPixelPerfect;
    		Scene.setDefaultDesignResolution (320, 180, policy);

    	}

    	protected override void Initialize ()
    	{
    		// TODO: Add your initialization logic here
    		base.Initialize ();

    		
    		//This spawns our ArcadeRigidBody player at a really odd position
    		//Note, this doesnt happen if we focus on the game after it starts paused
    		Core.scene = new TiledMapScene ("mainMap");

    		//This works as intended, player spawns where we tell it to
    		//Core.schedule (0.5f, timer => Core.scene = new TiledMapScene("mainMap"));
    	}
    }
`

**Comment by HenrySipp** [comment]
Realized I was on an outdated version of nez (about a week old). Seems to have been fixed.

Sorry

**Comment by prime31** [comment]
Woohoo! Foresaw the bug and psychically fixed it ;)

Mike


On Mar 30, 2016, at 4:28 PM, Henry Sipp <notifications@github.com> wrote:

Realized I was on an outdated version of nez (about a week old). Seems to have been fixed.

Sorry
