### ISSUE TITLE
Weird vertical black line when using Nez with FNA

### ISSUE THREAD

**Issue by Jeedify** [prime31/Nez#217]
Hey there guys *(and @prime31 :))*

So I compiled the latest Nez and Nez.FNA (from git, with 2 separate clones) and created 2 different projects, one for MonoGame with Nez and one for FNA with Nez.

The main game class is as simple as it can get:
```csharp
public class Game1 : Core
{
	public Game1() : base() { }

	protected override void Initialize()
	{
		base.Initialize();

		scene = Scene.createWithDefaultRenderer(Color.CornflowerBlue);
	}
}
```

But the results are different.

#### MonoGame:
![Nez with MonoGame - No black line](http://i.imgur.com/IFIHCMy.png)
\([Screenshot link](http://i.imgur.com/IFIHCMy.png)\)

#### FNA:
![Nez (Nez.FNA) with FNA- Black line](http://i.imgur.com/Bv7lbC6.png)
\([Screenshot link](http://i.imgur.com/Bv7lbC6.png)\)

As you can see, everything is fine with MonoGame, but with FNA, there's a vertical black line, at the right side of the scene, with the width of 1 and the height of the back buffer height.

It's also worth mentioning that the [default game class of XNA/MonoGame](https://github.com/MonoGame/MonoGame/blob/develop/ProjectTemplates/VisualStudio2010/DesktopGL/Game1.cs), **with FNA**, doesn't have this issue.
So I assume it is either a problem on my end or a problem with Nez's compatibility with FNA .

I tried looking at Nez's code to find where such problem might be, but I got lost so fast.
Can anyone who's more experienced with Nez lend a hand, please? :)

**Edit:**
The problem still occurs with the latest Nez.FNA as of July 28th 2017.
[Confirmed by](https://github.com/prime31/Nez/issues/217#issuecomment-318656436) @Alan-FGR

**Comment by Alan-FGR** [comment]
I don't know what's causing this, but I can confirm, except that for me it appears on the bottom too. Maybe FNA returns imprecise values for the framebuffer resolution, but I don't have time to investigate. In any case a quick fix is to modify the line:
https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Scene.cs#L554
to:
`var screenSize = new Point( Screen.width+1, Screen.height+1 );`

**Comment by Jeedify** [comment]
Thank you very much Alan.
That's awesome! :)
And sorry for the late response.

**Comment by Alan-FGR** [comment]
I don't think this should've been closed, I just cloned the latest Nez.FNA, Nez and FNA (all latest) and the problem still persists, it clearly is a bug, maybe not on Nez (although it likely is), but in any case I guess this should should stay 'open' while the problem persists.

**Comment by Jeedify** [comment]
If it's not a problem with Nez but with FNA instead, then I don't think the issue should stay open.
But I will do as you recommend and keep it open while the problem still exist :)

**Comment by Alan-FGR** [comment]
Thanks. I'm going to add some debug info later on here, and if I find something wrong with the FNA values I'll already forward this to flibit.

**Comment by Alan-FGR** [comment]
OK, that problem has been fixed now. I guess it's fine to close this.

**Comment by Jeedify** [comment]
Awesome! Thank you for your research and contribution @Alan-FGR :)
