### ISSUE TITLE
Errro Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount Monogame 3.6

### ISSUE THREAD

**Issue by luciancaetano** [prime31/Nez#218]
An unhandled exception of type 'System.MissingMethodException' occurred in MonoGame.Framework.dll

Additional information: Método não encontrado: 'UInt64 Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount()'.

**Comment by prime31** [comment]
Nez currently supports MonoGame 3.5. When 3.6 stabilizes it will be updated to work with it.

**Comment by cirla** [comment]
@luciancaetano see https://github.com/prime31/Nez/issues/224#issuecomment-303554897
