### ISSUE TITLE
Broken with MonoGame 3.6

### ISSUE THREAD

**Issue by RUSshy** [prime31/Nez#220]
I updated MonoGame dependency to 3.6 and nez is now broken :D

Unhandled Exception: System.MissingMethodException: Method not found: 'UInt64 Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount()'.
   at Nez.Core.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()

**Comment by prime31** [comment]
Nez does not yet support MG 3.6. Once 3.6 stabilizes Nez will be updated to work with it out of the box.

**Comment by robert-wallis** [comment]
3.6 is marked as `stable` on Nuget https://www.nuget.org/packages/MonoGame.Framework.DesktopGL/3.5.1.1679

And the GraphicsMetrics code looks super simple.  I wonder why it's looking for a Uint64 method: https://github.com/MonoGame/MonoGame/blob/989dbe64ab1f629e92af25427c4b25c3895fe130/MonoGame.Framework/Graphics/GraphicsMetrics.cs, is that something to do with PCLs converting `long` to `UInt64` ?

**Comment by prime31** [comment]
Marked as stable and actually being stable are two totally different things ;) MonoGame 3.6 is still buggy and the project templates installed with it are totally broken for DesktopGL.

**Comment by r3tina** [comment]
Can you tell me what the plans for this issue are? I have VS2017 which requires me to use MG 3.6. I'd rather use Nez with this than downgrade to VS 2015/MG 3.5.

**Comment by prime31** [comment]
As of now the first MG 3.6 patch *still* hasn’t dropped. If you search the issues you will find that Nez only required a tiny amount of changes for MG 3.6 compatibility that you can either do yourself or use a repo of someone who made the changes (search Gitter for info).
