### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'UInt64 Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount()'.'

### ISSUE THREAD

**Issue by RShadowhand** [prime31/Nez#224]
My code is identical to the one in the tutorial, and it compiles fine.

But I get `System.MissingMethodException: 'Method not found: 'UInt64 Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount()'.'` when I try to run the application.

**Comment by prime31** [comment]
Nez does not support MonoGame 3.6 yet. When 3.6 stabilizes it will then be supported.

**Comment by cirla** [comment]
@RShadowhand for now as a workaround you can:

- Delete the Nez project's reference to Monogame.Framework.dll and replace it with the one distributed with MonoGame 3.6
- Change the type of `Core.drawCalls` in Nez's Core.cs from `ulong` to `long`

**Comment by RShadowhand** [comment]
Thank you, I'll give that a shot.

**Comment by Effer** [comment]
@cirla Thanks, it works with you suggestions.

**Comment by jaxspades** [comment]
I tried that, it caused a lot of errors...I'll just comment that line out in Core.drawCalls for now until there is a more official fix.

**Comment by nightblade9** [comment]
Ran into this today with the latest `Nez` from Git. Replacing the `MonoGame.Framework.dll` didn't work until I removed and re-added the reference (replacing the file on disk isn't enough, even if Visual Studio shows the correct/updated version).

I also had to change `ulong` to `long` and change `OnApply` in `WaterReflectionEffect.cs` to return `void` instead of `bool`.

**Comment by johmarjac** [comment]
Meanwhile the project targets 3.6 in the packages.config, but it is still throwing this error? Is this Engine dead?

**Comment by prime31** [comment]
If you are using the latest version of Nez it will work fine with MonoGame 3.7 (which is the current version on the MG website for Mac).

**Comment by johmarjac** [comment]
Define latest version of Nez. Do you mean the latest commit? Or the latest release?

**Comment by prime31** [comment]
There is no listed 3.7 version but if you download the latest macOS version the DLL is for some reason tagged as 3.7. It’s been like that for a few months for some reason.

**Comment by prime31** [comment]
And latest version of Nez is always commit. Releases aren’t used anymore. Most folks preferred to grab from git rather than download the random dll and shader bits.

**Comment by prime31** [comment]
Technically, MonoGame's GL template should work identical on Windows an macOS. I personally only fire up Windows on rare occasions so I have no idea what the current MG release version is actually labeled as in the DLL. Most of the folks in the gitter chat use Windows though so anyone there should know the answer (or you could just download it and check).
