### ISSUE TITLE
Running Nez on a custom (editor) Window.

### ISSUE THREAD

**Issue by wihu** [prime31/Nez#226]
Hi, I have been planning on developing a full 2d game editor and just found Nez to be the best candidate for the 2d game framework.
 
However as I looked through the codes, there are some tight dependencies between game components with the Core class and its static members, hence its difficult to create a Core-less Scene instance, and because the Core itself inherits from Game class which will create and run the game in a native Window.

I think it would be nice if we can run and render the game inside a editor gui (e.g. in a docked viewport of game view or scene view, also possible to pause or step game frame), but that might require rewriting / duplicating whats inside the Core class.

Please let me know what you think is the best approach to achieve this.
Nez is a great framework and I would love to using it for my 2d game projects and developing tools for it.

Thank you and cheers.

**Comment by prime31** [comment]
You're best bet for making an editor would be to remake Core. It is currently designed to be a runtime so you'll need to add the ability to pause and step frame by frame and any other features your editor might require.

**Comment by wihu** [comment]
Thank you for the answer, I will look into how I can remake the Core that can be used in the editor environment.
