### ISSUE TITLE
Should renderable components have local rotation/scale/etc. in addition to local position?

### ISSUE THREAD

**Issue by z2oh** [prime31/Nez#23]
For my project I need sprites that rotate independently of the parent entity. This is fairly easy to implement in a custom renderable component, but should the default RenderableComponent have this functionality built in?

**Comment by prime31** [comment]
Try out renderable.transform.localRot/Scale/Pos


On Apr 5, 2016, at 7:09 PM, Jeremy Day <notifications@github.com> wrote:

For my project I need sprites that rotate independently of the parent entity. This is fairly easy to implement in a custom renderable component, but should the default RenderableComponent have this functionality built in?

**Comment by z2oh** [comment]
What type renderable in your example? Should I make new game objects with sprites on them and attach them to my parent entity rather than just using sprites?

**Comment by prime31** [comment]
I should have been more explicit! It was an Entity.  If going from Component it is renderable.entity.transform that contains all the rot/pos/scale and parenting options.

You will definitely want them on their own Entity if they are supposed to behave differently. I don't know your exact situation so I can't say what all of your options are.

**Comment by z2oh** [comment]
Okay thanks, I will put them on their own entity then.
