### ISSUE TITLE
Adding post processors makes the screen black

### ISSUE THREAD

**Issue by rafaelalmeidatk** [prime31/Nez#233]
Every time I add a post processor the game screen turns all black. Core file:

	public class Game1 : Core
	{
		protected override void Initialize()
		{
			base.Initialize();
			Window.AllowUserResizing = true;
			scene = new BasicScene();
		}
	}

Class file:

    public class BasicScene : Scene
    {
        public override void initialize()
        {
            addRenderer(new DefaultRenderer());
            addPostProcessor(new ScanlinesPostProcessor(0)); // If this line is removed, the issue is solved
        }
    }

I figured out after looking at #44 that adding the following snippet at the core solves the issue:

    scene = Scene.createWithDefaultRenderer();
    base.Update(new GameTime());
    base.Draw(new GameTime());

So the working core class is the following:

	public class Game1 : Core
	{
		protected override void Initialize()
		{
			base.Initialize();
			scene = Scene.createWithDefaultRenderer();
			base.Update(new GameTime());
			base.Draw(new GameTime());
			scene = new BasicScene();
		}
	}

I am not sure if it is the intended behaviour, just letting you know, I took a lot of time to make the Post Processors to work and was just able to do using this "hack".

**Comment by zerodarkzone** [comment]
I have the same problem when working on Android. On desktop it works ok. Doing what you did to solve the problem doesn't work for me.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
