### ISSUE TITLE
RenderableComponent runs into infinite loop if subclass does not override any of {width, height, or bounds}.

### ISSUE THREAD

**Issue by wihu** [prime31/Nez#234]
Looks like RenderableComponent has circular references when checking the bounds for rendering:
```
public virtual RectangleF bounds
{
	get
	{
		if( _areBoundsDirty )
		{
			_bounds.calculateBounds( ..., *width*, *height* );
			_areBoundsDirty = false;
		}

		return _bounds;
	}
}
```
width and height properties calling bounds property and so it goes into circular loop:
```
public virtual float width { get { return *bounds*.width; } }
public virtual float height { get { return *bounds*.height; } }
```

I think this creates confusion for when someone started to subclass the RenderableComponent and trying to run the game then the game window freezes. It took me a while to realise that I should override one of those properties.

I would suggest to just return default width and height instead of bounds.width and bounds.height?

**Comment by prime31** [comment]
That is by design. Be sure to read the code comments about providing a proper override when subclassing. They explicitly hit on this exact situation.
