### ISSUE TITLE
Rigid Arcade Body Physics are Affected by Framerate

### ISSUE THREAD

**Issue by AaronShea** [prime31/Nez#240]
When running the Nez-Samples "Rigid Bodies" demo I noticed odd behavior.

With vsync on (144 fps for me) the moon bodies behave like they should, falling fairly quickly and bouncing off each other. However if I turn off vsync and let the demo run at 1000+ fps the simulation seems to slow down tremendously. Things fall at fractions of the rate they did before when vsync was on.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
