### ISSUE TITLE
Inconsistent method naming conventions

### ISSUE THREAD

**Issue by DarrenAtherton49** [prime31/Nez#241]
In the `Core` class, Nez uses **PascalCase** for method names, however in other places such as `Scene`, it uses **camelCase**. For example - the `initialize` method in each of those classes is different. Is there a specific convention used for the project or has this inconsistency just been around from early on?

Thanks, the project is great!

**Comment by prime31** [comment]
Nez used camalCase for everything. The only time PascalCase is used is when it is a method or property overriden from something that is not part of Nez, i.e. not in our control.
