### ISSUE TITLE
ImageButton constructor overloads - Image passed won't show, not sure what's the expected behaviour

### ISSUE THREAD

**Issue by Alan-FGR** [prime31/Nez#242]
I'm not sure what's the expected behaviour of [these ](https://github.com/prime31/Nez/blob/master/Nez.Portable/UI/Widgets/ImageButton.cs#L32)overloads:
```
public ImageButton( IDrawable imageUp ) : this( new ImageButtonStyle( null, null, null, imageUp, null, null ) )
public ImageButton( IDrawable imageUp, IDrawable imageDown ) : this( new ImageButtonStyle( null, null, null, imageUp, imageDown, null ) )
public ImageButton( IDrawable imageUp, IDrawable imageDown, IDrawable imageOver ) : this( new ImageButtonStyle( null, null, null, imageUp, imageDown, imageOver ) )
```
If you create an image button and pass an (IDrawable) image, it won't show... for it to show I had to pass the image I want in the first ImageButtonStyle constructor parameter. I'm not 100% sure though if this is a bug or if I'm missing something.

**Comment by prime31** [comment]
This all depends on what you are trying to achieve. If you use the constructor with only a single IDrawable you are passing the IDrawable through as the `imageUp` param. If you want a button with both a background and an imageUp (and any other options) I'd recommend just using a `Skin`. It is way easier once you get the hang of it and way less error prone since you do all your UI skin setup in once place.

**Comment by Alan-FGR** [comment]
Well, the ImageButtonStyle takes 6 drawables:
up, down, checkked, imageUp, imageDown, imageChecked
The overload ImageButton(IDrawable imageUp) passes that IDrawable to the "imageUp", but it doesn't show on the button. In fact nothing renders at all.
I don't want a button with both a background and imageUp (so, imageUp is supposed to be a foreground image?) I just want a button to show an image on screen, and none of the listed overloads do that.

What would be the appropriate way to just show a texture on a button? The following code for example doesn't do that:
```c#
ImageButton(new SubtextureDrawable(someTexture))
```
I just want to display an image on a table with an "onClick" callback.

**Comment by prime31** [comment]
Just use a regular button if you only have a single image. The purpose of an ImageButton is to have the normal background image along with another image on top.

**Comment by Alan-FGR** [comment]
Ah, OK, thank you 👍
