### ISSUE TITLE
Adding elements to table moves to the next row if you don't add them at once

### ISSUE THREAD

**Issue by Alan-FGR** [prime31/Nez#243]
Consider the following example:
```csharp
using Nez;
using Nez.UI;

public class TestScene2 : Scene
{
    public override void initialize()
    {
        addRenderer(new DefaultRenderer());

        var canvas = createEntity("ui").addComponent(new UICanvas());

        var skin = Skin.createDefaultSkin();
        
        var table = canvas.stage.addElement(new Table());
        table.top().left().setDebug(true);
        table.fillParent = true;

        var resultsTable = new Table();
        resultsTable.setDebug(true);

        var button = new TextButton("add 5 elements", skin);
        button.onClicked += (b) => { 
            for (int i = 0; i < 5; i++)
                resultsTable.add(new Label("sometext3"));
        };
        table.add((new Table()).top().add(button).getTable()).setFillY();

        var button2 = new TextButton("add 1 element", skin);
        button2.onClicked += (b) => resultsTable.add(new Label("sometext1"));
        table.add((new Table()).top().add(button2).getTable()).setFillY();

        table.add(resultsTable);

        table.pack();
    }
}

public class Game : Core
{
    public Game() : base(1280, 720){}
	protected override void Initialize()
	{
		base.Initialize();
		Window.AllowUserResizing = true;
		scene = new TestScene2();
	}
}
```
When it calls Table.add in the for loop, the labels are all added to the same row, however, next time you call it they're added in a new row. I don't think this behaviour is correct but please correct me if I'm wrong and missing something, and in this case please also kindly explain how one should add more elements to the same row in a subsequent call stack.

**Comment by Scellow** [comment]
Check this: https://github.com/libgdx/libgdx/wiki/Table

**Comment by Alan-FGR** [comment]
Yes, the docs are clear, to move to the next row you have to explicitly tell the table to do so, what's happening in that example is that somehow the table went rogue and is adding rows by itself 😝... did you run the example?

**Comment by prime31** [comment]
Are you sure that code is adding a second row? Are you hitting this in the debugger and inspecting the `_rows` value? I think what you are getting there is a bunch of buttons in a row then entire new Tables with more buttons in them. If you turn on debug logging (`TableDebug.All`) you should be able to see exactly where the rows/cols are. I'd also recommend just using the debugger for this kind of stuff. If you trace into the `add` method (or must inspect the Cell that is returned by `add`) you can see the exact row and column that the Cell was added to.

**Comment by Alan-FGR** [comment]
Yes, I'm positive it's adding rows:
![image](https://cloud.githubusercontent.com/assets/8399299/26292742/d90f6434-3e8e-11e7-99d3-35a467a18ad1.png)
I can look into the debugging tools but I don't think this is the expected behaviour, should that code be generating rows at all? Is there a situation where MyTable.add(new Label("sometext")) is expected to generate any row at all?

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
