### ISSUE TITLE
Origin resetting back to center on Sprite<T>

### ISSUE THREAD

**Issue by marcinjakubowski** [prime31/Nez#245]
[Origin is reset on Sprite.setSubtexture](https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Renderables/Sprites/Sprite.cs#L127), which makes setting it on a Sprite\<T\> only work until the animation is played as all frame changes use the base method (e.g. [regular frame change](https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Renderables/Sprites/SpriteT.cs#L179), but also completion behavior, etc.).

**Comment by prime31** [comment]
That is all correct as noted in the [XML comments for origin](https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Renderables/Sprites/Sprite.cs#L29). Sprites always get their origin from the Subtexture they are displaying. This isnt a bug, it is by design.

**Comment by marcinjakubowski** [comment]
I'd say it's a bug for an animated Sprite<T>. The fact that happens is completely hidden away from the user (you never call setSubtexture yourself) and setOrigin works, but only for the first frame, before any animation is played. It also requires setting origin on each individual frame subtexture for the origin to work, which imho makes no sense. 

I can follow my own opinions in my fork though, so no problem :)

**Comment by prime31** [comment]
True indeed. You can also always subclass and change the behavior.
