### ISSUE TITLE
Error compiling on windows - new project

### ISSUE THREAD

**Issue by koniin** [prime31/Nez#25]
Hi Mike,

I just followed your video on youtube and when I tried to build the Nez project I got the following error;

warning MSB3274: The primary reference "MonoGame.Framework" could not be resolved because it was built against the ".NETPortable,Version=v4.5,Profile=Profile111" framework. 
This is a higher version than the currently targeted framework ".NETPortable,Version=v4.0,Profile=Profile5".

I tried changing target but then it spewed a lot of errors in different parts of the Nez projects (mainly reflection parts that have changed in the newer version). 

I fixed it by replacing the dll in the Nez\Nez-PCL\MonoGamePCL folder with the DLL from the monogame site. Don't know if the error is on my side or I did something wrong. It works but I just thought I'd let you know!

**Edit: ** Visual Studio 2015, Monogame 3.5 installer and Monogame windows openGl project template is what I'm using.

**Comment by prime31** [comment]
That's an odd one. Can you send over a link to the DLL that you replaced it with?

It sure will be nice when MonoGame 3.6 drops with a proper, official PCL DLL...
