### ISSUE TITLE
Graphical issue on TrailRibbon

### ISSUE THREAD

**Issue by ampetty** [prime31/Nez#250]
I was trying out the TrailRibbon and I noticed there was an odd graphical issue going on.  At the head of the ribbon there's a misaligned green vertex that only shows when moving in certain directions.

![image](https://cloud.githubusercontent.com/assets/29081662/26759239/8dfb9d22-48ad-11e7-9940-695022f85635.png)

I poked around the TrailRibbon class and it seems like the starting triangle is being offset by 'radVec' for some reason:

```c#
void calculateVertices()
{
	// snip
	
	var center = new Vector3( entity.transform.position, 0f );
	var radVec = new Vector3( 0, -ribbonRadius, 0 );
	
	// starting triangle, the head
	_vertices[0].Position = center + radVec;
	_vertices[0].Color = Color.Red;
	_vertices[1].Position = center + radVec;
	_vertices[1].Color = Color.Yellow;
	_vertices[2].Position = center + radVec;
	_vertices[2].Color = Color.Green;
	
	// snip
}
```

Removing 'radVec' from the calculation seems to fix the issue but I'm not sure if that would be breaking some other intended purpose that it might have.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
