### ISSUE TITLE
Get tile properties when colliding

### ISSUE THREAD

**Issue by ct14it** [prime31/Nez#253]
Thanks for Nez and sorry if this has been covered elsewhere but...

I would like to check custom properties of tiles and objects as defined in the Tiled map editor. Is that possible at all?

I'm assuming I need to check a list of nearby potential colliders, check for a collision and then access the property somehow.

Any clues? : D

Cheers
-Chris

```
// fetch anything that we might overlap with at our position excluding yourself. 
var neighborColliders = Physics.boxcastBroadphaseExcludingSelf(_boxCollider);

// loop through and check each Collider for an overlap
foreach (var collider in neighborColliders)
{
    if (_boxCollider.overlaps(collider))
    {
        // if collider tile property "Foo" == "Bar
        //     do something
    }
}
```

**Comment by prime31** [comment]
Tilemaps don’t use collision so physics queries won’t return any relevant data. The TiledMap layers can convert from world space and tell you the tile at any location and that tile will have a Dictionary of all the properties set in Tiled.

**Comment by ct14it** [comment]
Sorry to reopen this, but how exactly might I do that? 

I think I need to use getTilesIntersectingBounds of TiledTileLayer but I don't really know how I go about accessing the TiledTileLayer from my player class.

I've added the tiled map to the same scene as the player as follows:

```
var tiledEntity = createEntity("tiled-map");
tiledEntity.addComponent(new TiledMapComponent(tiledMap, "main"));
var player = createEntity("player");
// Other components added to player entity
```

Once again, any help will be greatly appreciated :)

**Comment by prime31** [comment]
You're going to want to dig into the code for this kind of stuff. Everything in there is pretty well commented and a lot of time was put into making the code clean and readable. I can't comment on how to get to your Tiled object from your Player class (that is up to your specific setup) but there are several ways to search the Scene for objects such as findEntity, findEntitiesWithTag, entitiesOfType, findComponentOfType, etc. Use whichever works best for your situation or you can just architect your classes to have references to everything that they need.
