### ISSUE TITLE
Null reference exception in DX11 projects

### ISSUE THREAD

**Issue by treplogle** [prime31/Nez#254]
The field EffectResource.spriteEffectBytes references SpriteEffect.ogl.mgfxo which doesn't exist in DX11 MonoGame projects.  The resource name in DX11 projects is SpriteEffect.dx11.mgfxo.  This causes a null reference exception in Core.Initialize when running Nez in a DX11 project.

**Comment by prime31** [comment]
From the [README](https://github.com/prime31/Nez/blob/master/README.md):

> All Nez shaders are compiled for OpenGL so be sure to use the DesktopGL template, not DirectX! Nez only supports OpenGL out of the box to keep things compatible across Android/iOS/Mac/Linux/Windows.

**Comment by treplogle** [comment]
Sorry about that.  I missed that in the readme.
