### ISSUE TITLE
Ellipse Collider Shape

### ISSUE THREAD

**Issue by bojjenclon** [prime31/Nez#26]
Is there any plan to support ellipse shapes for colliders? Using ellipses for (N)PCs is fairly common, as circles don't always fit sprites very well and rectangles don't conform to natural curves of sprites as well.

**Comment by prime31** [comment]
There are currently no plans to add ellipse colliders though pull requests are always welcome ;)

I have never once needed an ellipse before so I have no idea how complex the math is but I can say that a diamond shaped PolygonCollider would be pretty darn close to an ellipse.

**Comment by bojjenclon** [comment]
I'll keep that in mind. I should be able to make due with rectangles and circles, but if for some reason I end up needing to look into ellipses more I'll be sure to send a pull request your way.
