### ISSUE TITLE
Text Markup Engine?

### ISSUE THREAD

**Issue by RUSshy** [prime31/Nez#262]
Hello, do you have plan to add markup engine, like in html or something else ? something like this:

```xml
 <color=red>text in red</color> text in white <color=green>text in gren</color>
```

**Comment by prime31** [comment]
Like this?

https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Text/MarkupText.cs

**Comment by RUSshy** [comment]
i meant directly in the renderer, so it can be used universally even in the UI

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
