### ISSUE TITLE
Setting global rotation of an entity

### ISSUE THREAD

**Issue by Strackeror** [prime31/Nez#265]
I think the calculation in the Transform.setRotation method is reversed, right now it adds the parent's rotation to the given angle :
```C#
if( parent != null )  
    localRotation = parent.rotation + radians;
```
Shouldn't the parent's rotation be substracted instead ?

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
