### ISSUE TITLE
Shaking atlas animation on iOS

### ISSUE THREAD

**Issue by PetrKavan** [prime31/Nez#271]
Hello, I have a slight problem with texture atlas animation. I have created texture atlas asset from series of PNGs and a XML, with Texture atlas generator. It works well in windows, but when used in iOS project, the animation shakes a little - as if every frame was moved by a pixel or two from its correct position.

This is how I create sprite from the atlas a standard way I would think.
`var atlas = this.scene.content.Load<TextureAtlas>("cow_idle");`
`var ani = atlas.getSpriteAnimation("CowIdle");`
`var spr = new Sprite<int>(1, ani);`
`spr.play(1);`

I am sure that original PNGs are ok, it fits well when viewing in image viewer. The animation also plays well in app on windows.

**Comment by tanis2000** [comment]
How are you syncing your movement with the device? You might be experiencing some stutter if you don’t wait for vsync or a fixed time step

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
