### ISSUE TITLE
Dirty transforms can fail to properly set their position

### ISSUE THREAD

**Issue by wgyde** [prime31/Nez#275]
```
private void OnEntityTransformChanged(Transform.Component comp)
{
	Region = new Rectangle(
		(int)position.X - PORTRAIT_SIZE / 2,
		(int)position.Y - PORTRAIT_SIZE / 2,
		PORTRAIT_SIZE,
		PORTRAIT_SIZE
	);
	var _ = Portrait.entity.transform.position; //Position is wrong without this line
	Portrait.transform.setPosition(new Vector2(Region.Left, Region.Top));
	Portrait.SetDimensions(Region.Width, Region.Height);
}
```
In the above code, `transform.setPosition()` seems to fail unless I first run the getter on `transform.position`. I have also been able to fix this issue by breakpointing and observing the `transform.position` property, and running `updateTransform()` within `setPosition`. I cannot view the erroneous position because the act of viewing it causes it to correct itself.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
