### ISSUE TITLE
ui skin config not loading styles (only colors and atlases)

### ISSUE THREAD

**Issue by leshem-amit** [prime31/Nez#276]
I have a very minimalistic ui skin (just getting started with UI):

{
	colors:
	{
		green: '#00ff00',
		orange: '#ff9900',
		blue: '#0000ff',
		black: [0, 0, 0, 255],
		gray: [50, 50, 50, 255],
		blue: [116, 139, 167, 255],
		dialogDim: [50, 50, 50, 50]
	},
	 libGdxAtlases: [],
	 textureAtlases: [],

	LabelStyle:
	{
		default: { fontColor: 'green' },
		tooltip: { fontColor: 'blue' },
	},
}

when I load the skin:
`Skin skin = new Skin("skins/uiskinconfig", Core.content);`
`LabelStyle style = skin.get<LabelStyle>();`
`LabelStyle style2 = skin.get<LabelStyle>("tooltip");`
the skin is loaded but both sking.get(s) return null.

when inspection the skin instance I can see it only has 1 resource
`style._resources.Count = 1`
and it's the colors. no trace of my style.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
