### ISSUE TITLE
[FNA] Rendering doesn't work correctly - better workaround included

### ISSUE THREAD

**Issue by Alan-FGR** [prime31/Nez#281]
This is related to this: https://github.com/prime31/Nez/issues/217 and [this](http://community.monogame.net/t/nez-free-open-source-2d-framework/7010/113).

For some reason, rendering has a problem when using FNA. The fixes linked above are 'ugly workarounds'; they don't solve the actual underlying problem, and although normal rendering works, debug rendering doesn't:
![image](https://user-images.githubusercontent.com/8399299/29781121-85a512dc-8bee-11e7-80e0-3976f9be4ea2.png)

I've managed to track the issue down to these lines:
https://github.com/prime31/Nez/blob/master/Nez.Portable/Graphics/Batcher/Batcher.cs#L1007-L1008

When you change them to these:
```C#
			_projectionMatrix.M11 = 2.0f / (viewport.Width-1);
			_projectionMatrix.M22 = -2.0f / (viewport.Height-1);
```
Everything works fine:
![image](https://user-images.githubusercontent.com/8399299/29781143-98dcc020-8bee-11e7-9840-5f1667b2b872.png)

That is the last access to the pixel dimensions before building the matrix, thus any modifications after that would be subject to fp precision problems, since the value is just a fraction.

The strange part is that all dimensions returned from FNA are correct.
I'm not familiarized with the system well enough to pinpoint exactly where is the problem. Maybe somebody more familiar with it could have a good guess on where exactly the dimensions are being 'corrupted'... changing the scaling doesn't work, the problem is when actually rendering, not just displaying the render result.

In the mean time, the code above is certainly the best way to temporarily remedy the problem.

**Comment by Alan-FGR** [comment]
@prime31 I see you've added the fix above to Nez... I didn't make a PR because I thought you wouldn't want it in the source, but I'd gladly submit one if you'd lemme know the code is OK to merge. Is that fix adequate? Did you figure why that rendering problem happens and why that code fixes it?

**Comment by prime31** [comment]
I have no idea why FNA renders 1 pixel off and don't have the time at the moment to dig into FNA's OpenGL stack to find out.

**Comment by Alan-FGR** [comment]
@prime31 no problem... I wasn't asking that at all. I'm happy that we have a fix :P

**Comment by Alan-FGR** [comment]
OK, today I found out that there's still a problem with this approach: for some reason depending on the render target resolution that problem still occurs, the problem happens when one of the dimensions is even, so it's simple enough to fix it just ` / 2 * 2` your render target resolution and that should do the trick. There's definitely something fishy going on under the hood here... I'm pretty sure the problem is (at least in part) floating point inaccuracy on the GPU since it's hardware dependent, so just to be on the safe side I'm explicitly setting the 4th matrix cols instead of that other fix, because I've a feeling that it's much more robust:
```
_projectionMatrix.M41 = -1;// - 0.5f * _projectionMatrix.M11;
_projectionMatrix.M42 = 1;// - 0.5f * _projectionMatrix.M22;
```
I wish I could use MonoGame but although normally rendering works, Nez fails on a lot of hardware, while FNA works perfectly fine. FNA is also a lot faster too. Perhaps I should just ask on the MG forums if there's a way to fix that instead, but FNA is working quite well so far besides that minor rendering problem.

**Comment by Alan-FGR** [comment]
@prime31 btw, you forgot the brackets:
```
		    _projectionMatrix.M11 = (float)( 2.0 / ((double)viewport.Width - 1) );
		    _projectionMatrix.M22 = (float)( -2.0 / ((double)viewport.Height - 1) );
```
https://github.com/prime31/Nez/blob/master/Nez.Portable/Graphics/Batcher/Batcher.cs#L1008-L1009

But I think the problem lies elsewhere... I'm actually starting to think that MonoGame does some rounding under the hood (maybe 1px overscan), and FNA doesn't.

**Comment by Alan-FGR** [comment]
Hang on a bit, gonna F&F (fork and fix 🤣)

**Comment by Alan-FGR** [comment]
https://github.com/prime31/Nez/pull/283
