### ISSUE TITLE
Nez.Physics glitches

### ISSUE THREAD

**Issue by Alan-FGR** [prime31/Nez#282]
Tomorrow I'm going to investigate this problem, I think it's some math returning a NaN or Infinity.
The easiest way to reproduce is to run the "Shadows" example from the Nez.Samples repo and move your 'character' between the static and the tweening boxes; when the animated box pushes the 'character' against the static one, the character will simply disappear into thin air 😆.
If it's a NaN problem, checking that and returning some reasonable value (maybe 0) could solve that, if it's Infinity, then implementing a 'max pos delta' could solve it.

**Comment by Alan-FGR** [comment]
Lol, that behavior in the Shadows example is a feature, not a bug 🤣...
I've had a similar problem though, and I assumed it was related, but I guess it isn't... gonna make an SSCCE for further investigation.

**Comment by Alan-FGR** [comment]
OK, apparently it isn't a bug, but just undocumented (?) limitation... I thought it was a bug because when I print all collisions and I have say this:
```C#
public class TestScene : Scene
{
    public class CompoundBody : Component
    {
        public override void onAddedToEntity()
        {
            base.onAddedToEntity();
            entity.addComponent(new ArcadeRigidbody().setMass(1));
            entity.addComponent(new CircleCollider(16));
            entity.addComponent(new BoxCollider(-16, -32, 32, 32));
        }
    }

    public class MovingCompoundBody : CompoundBody, IUpdatable
    {
        public void update()
        {
            entity.position += Vector2.UnitX * -1;
        }
    }

    public override void initialize()
    {
        addRenderer(new DefaultRenderer());

        Physics.gravity = Vector2.Zero;

        Entity entity = createEntity("entA");
        entity.addComponent(new MovingCompoundBody());
        entity.position = new Vector2(200,100);

        Entity entity2 = createEntity("entB");
        entity2.addComponent(new CompoundBody());
        entity2.position = Vector2.One*100;
    }
}
```
this is the result:
![17-08-31-47](https://user-images.githubusercontent.com/8399299/29926036-9f141636-8e38-11e7-9750-5caccf0de17d.gif)

So there's no collision between colliders in the same body, but stuff go crazy, and yes, it's NaN.
But when I change the rectangle to be 1px up, this is what I get:
![17-08-31-53](https://user-images.githubusercontent.com/8399299/29926157-006c100a-8e39-11e7-9a9e-bae705b1ff80.gif)

So the problem is, colliders on the same body they collide with themselves... I just assumed otherwise 😛

@prime31 I'd recommend leaving this open until we document that limitation (if it isn't already, to be honest with you I didn't read the docs 😄)... I think this is important because every other engine I've used won't have that problem, colliders on a single body don't collide internally, what imho makes more sense because they can't move relative to each other anyway, but I'm not saying Nez should do that, but should definitely document such a thing because it's certainly a peculiarity.

**Comment by Vanit** [comment]
I think its safe to assume colliders should never collide with themselves, will investigate a fix.

**Comment by prime31** [comment]
Hmm. Colliders wont collide with themselves but the Collider doesnt actually check for other overlapping Colliders on the Entity. If you need compound Colliders you have two options:

1. use the Farseer Physics Colliders. They are a full featured physics simulation and allow compound Colliders.
2. make a custom subclass of ArcadeRigidBody. Override `update` and in the loop `foreach( var neighbor in neighbors )` you'll want to do a check to make sure `neighbor.entity != entity`. Something like this:

    foreach( var neighbor in neighbors )
    {
        if( neighbor.entity != entity ) continue;

**Comment by Vanit** [comment]
So circling back to @Alan-FGR's suggestion - does this belong in the documentation somewhere, or should a collider assert that it has no peers to prevent this gotcha or?

**Comment by prime31** [comment]
I’d probably say just having a note in the Physics docs with regard to the ArcadePhysics being a one Collider per Entity system. Or maybe just adding that one line to the main class so that stuff “just works” would be good.

**Comment by Vanit** [comment]
Let's go with just works :)
