### ISSUE TITLE
UI doesn't work when window is at certain position on screen

### ISSUE THREAD

**Issue by Alan-FGR** [prime31/Nez#284]
Consider the following example:
```C#
class TestScene : Scene
{
    public override void initialize()
    {
        base.initialize();

        setDesignResolution(640,360,SceneResolutionPolicy.ShowAll);
        addRenderer(new DefaultRenderer());

        var canvas = createEntity("ui").addComponent(new UICanvas());
        var skin = Skin.createDefaultSkin();
        var table = canvas.stage.addElement(new Window("window", skin)).setMovable(true).setResizable(true);
        table.pad(20,5,5,5).setPosition(10, 10);
        var inpt = new TextField("input", skin);
        table.add(inpt).pad(10).setRow();
        var button = new TextButton("click", skin);
        table.add(button).size(100,20).setRow();
        table.pack();

        table.setPosition(10, 75); // WINDOW POSITION

    }
}

class TestGame : Core
{
    protected override void Initialize()
    {
        base.Initialize();
        Screen.setSize(1280,720);
        scene = new TestScene();
    }
}

class Program
{
    private static TestGame game;
    static void Main(string[] args)
    {
        game = new TestGame();
        game.Run();
    }
}
```
The code above creates a window with widgets that you can't click over nor hover with the mouse. Pay attention to the line with the comment, if you change that to `table.setPosition(10, 15);` or `table.setPosition(10, 175);`, causing the window to be slightly above or below its original position, then the UI works again. This can also be reproduced by manually positioning the window close to that position, it's not necessary to be extremely precise, the 'area' in which the window won't work is considerable.

**Comment by yaegerbomb** [comment]
[This might be related to this issue.](https://github.com/prime31/Nez/issues/112)

**Comment by brandc87** [comment]
@yaegerbomb / @Alan-FGR If you drag a window past the stage the image/background stays in but the actual bounds of the window continues to move. I've had a look through the code and none of the alignment statements are being hit so the tables are continuing off screen which then stops movement from working.

`if( ( edge & (int)AlignInternal.left ) != 0 )`

I've tried a number of things to fix this but unable to yet.

You can see this with debugAll() running. Some screenshots:
When game loads the windows bounds are correct,
![screen shot 2018-01-25 at 16 30 33](https://user-images.githubusercontent.com/11300674/35399881-42149bb2-01ed-11e8-9911-c8a8f9aea5fb.png)

Here I've tried to drag the window off screen to the left the image stays in but the bounding box continues moving.
![screen shot 2018-01-25 at 16 30 42](https://user-images.githubusercontent.com/11300674/35399882-423ea3da-01ed-11e8-90c3-6d9f0021022b.png)

**Comment by Alan-FGR** [comment]
@brandc87 that's another issue, in my example the window stays fully on the screen and even though it stops registering mouse events.

**Comment by Vanit** [comment]
Found the issue, there was a bug causing hits to be ignored when the window's x position was less than its width (which is why moving it to the right fixed it). ¯\_(ツ)_/¯
