### ISSUE TITLE
Should getComponents<T>/etc also retrieve subclasses?

### ISSUE THREAD

**Issue by Vanit** [prime31/Nez#286]
I need this behaviour as I'm adding an entity system that processes all components B, C and D that subclass component A, which provides a standard interface for the system. It would be great if I could just call getComponents<A>() and get all of those matching components, but the current behaviour gets the exact class via the "is" keyword.

I'm conscious of the fact that this could easily break existing games that assume it doesn't work this way. If that's a concern we could add an optional "includeSubclasses" flag that switches the behaviour on, with off being the default.

At the moment I've hacked in a getComponentsAll() method such that my system can do this itself, but I don't see why we couldn't bake this behaviour into Entity/ComponentList. Is there any reason I shouldn't proceed with a PR for this?

The check used would probably be as follows: 

`component.GetType().IsSubclassOf( typeof( MyComponent ) ) || component.GetType() == typeof( MyComponent) `

**Comment by witlock** [comment]
I was wondering about the same thing a month ago. I have classes that inherit from a class "worldobject" which inherits from **Component**.

**Comment by prime31** [comment]
Feel free to open a PR. I don’t see any reason why it wouldn’t make sense to have it.

**Comment by Vanit** [comment]
I feel like I must be going crazy here; I swear that this didn't work the other day, but maybe I made a mistake. It seems like the subclass usecase is infact inherently covered by the default behaviour after all? Can someone confirm that getComponents<Component>() works for them?

**Comment by witlock** [comment]
Is it really the same thing as **Matcher().all(typeof(Component)**? Because I'm certain that didn't work which is what I was talking about and what I use for entity systems.

**Comment by Vanit** [comment]
Matcher definitely doesn't work with subclasses, but that's a slightly different usecase to the one I wanted to solve, which seems to be solved already as I must've done something dumb like put the wrong class name in the \<\>.

**Comment by 0xFireball** [comment]
https://github.com/prime31/Nez/blob/459df7c2c09dfb87c4ee4dfe129b0bc5a0e30c8a/Nez.Portable/ECS/InternalUtils/ComponentList.cs#L265-L281

It's checking `component is T`, which would also be true for component types inherited from T. Looks like the current behavior is all right?

**Comment by Vanit** [comment]
@0xFireball Yep, it is. Should've closed this issue after my last comment, my bad. :)
