### ISSUE TITLE
Collision Resolution?

### ISSUE THREAD

**Issue by ashes999** [prime31/Nez#288]
Hi,

I looked through the GitHub repo README file and the collision system docs, but I didn't see an answer to my question.

Does Nez ship with collision resolution out of the box?  Or is Nez simply providing collision detection but not resolution? (The intro blog post mentions separation-axis theorem, but I don't see any API references to it.)

For example, can I easily write code for a player, some walls, and have the player walk/collide with walls?

And if present, what are the limitations (eg. AABB only, or requires Farseer, etc.)

**Comment by prime31** [comment]
Nez included Farseer if you want a full physics simulation and it also has its own collision system without a physics simulation which included overlap details for resolution.

**Comment by ashes999** [comment]
So Nez only handles collision resolution if I use Farseer? I don't want a full physics simulation, just simple AABB collision resolution.

**Comment by prime31** [comment]
Nez includes:

- Farseer physics simulation 
- a separating axis theorem implementation which of course includes resolution data you can use

**Comment by ashes999** [comment]
Great, thanks. Can you point me to any examples (documentation or code) that show the SAT return value, and/or how to consume it?

**Comment by prime31** [comment]
There is a whole page dedicated to physics/collision linked right from the README
