### ISSUE TITLE
EffectResources.cs load PostProcessing Effect throw InputStreamInvoker.get_Length() Not SupportedException

### ISSUE THREAD

**Issue by chanliu1983** [prime31/Nez#292]
EffectResources class use 
internal static byte[] deferredSpriteBytes { get { return getFileResourceBytes( "Content/nez/effects/DeferredSprite.mgfxo" ); } }

To get shader on Android, it internally uses 
src/Mono.Android/Android.Runtime/InputStreamInvoker.cs
(In my case public override long Length { get { throw new NotSupportedException (); } })

The function is going to throw a NotSupportedException() how does it work on Android.

https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Android.Runtime/InputStreamInvoker.cs

**Comment by nhorne** [comment]
Pull request #270 is meant to fix this issue.
