### ISSUE TITLE
FollowCamera zooms incorrectly on initialization

### ISSUE THREAD

**Issue by yaegerbomb** [prime31/Nez#294]
I am having a hard time trying to figure out how to set the camera properly.

Right now I am doing the following:

```c#
//camera.setPosition(_playerEntity.position); <-- doesn't seem to make a difference in this case

var followCamera = new FollowCamera(_playerEntity, camera);
camera.addComponent(followCamera);
```

This is fine but the problem is that my sprite sizes are 16 x 16, so we are very far away from everything. Modifying the code to do this:

```c#
//camera.setPosition(_playerEntity.position);

var followCamera = new FollowCamera(_playerEntity, camera);
camera.addComponent(followCamera);
camera.zoomIn(.3f);
```

This causes the camera to zoom in but we are zoomed to the center of the level and the camera does not follow the player entity at all. I feel like I need to set up a deadzone or something but after trying a couple of different numbers it doesn't seem to make a difference.

I am able to zoom in and zoom out fine after the scene has been initialized using key input and everything states the way it should.

```c#
if (inputComponent.PlusButton.isPressed)
{
    scene.camera.zoomIn(.1f);
}

if (inputComponent.MinusButton.isPressed)
{
   scene.camera.zoomOut(.1f);
}
```

 But if I zoom before that everything is very wrong:

Is there a proper way to use the follow camera with smaller sprites?

**Comment by yaegerbomb** [comment]
After investigating what could be causing this I have found the following:

The FollowCamera's follow method gets ran after the camera's zoom function is called. This makes the camera bounds wrong for when we are calculating our deadzone as our deadzone should be calculated before the camera zoom (at least this is what I think needs to happen).

Doing the following in the FollowCamera's follow method:

```C#
public void follow( Entity targetEntity, CameraStyle cameraStyle = CameraStyle.CameraWindow )
{
	var currentZoom = camera.zoom;
	camera.setZoom(0);

	_targetEntity = targetEntity;
	_cameraStyle = cameraStyle;
	var cameraBounds = camera.bounds;

	switch( _cameraStyle )
	{
		case CameraStyle.CameraWindow:
			var w = ( cameraBounds.width / 6 );
			var h = ( cameraBounds.height / 3 );
			deadzone = new RectangleF( ( cameraBounds.width - w ) / 2, ( cameraBounds.height - h ) / 2, w, h );
			break;
		case CameraStyle.LockOn:
			deadzone = new RectangleF( cameraBounds.width / 2, cameraBounds.height / 2, 10, 10 );
			break;
	}

	camera.setZoom(currentZoom);
}
```

Resetting our camera zoom on our follow method and then setting it back after we find our deadzone yields the correct follow camera behavior.

Though this seems a bit dirty. Perhaps the camera could have a method for calculating original bounds without any matrix transformations (scale and rotation)?

**Comment by antonigiske** [comment]
I experienced exactly the same. I'm using @yaegerbomb fix for now, but hopefully this could be fixed in another way.

**Comment by antonigiske** [comment]
I don't know if this is related to this issue, but if I instead half my window/height and use  `Screen.setSize(WINDOW_WIDTH * 2, WINDOW_HEIGHT * 2);` then the FollowCamera will work perfectly without the code changes you mentioned earlier, and the game will be "zoomed" as was my intention.

**Comment by Vanit** [comment]
Investigating this at the moment, but the bug is exactly as described.

Having said that, the ideal way to satisfy your usecase is to use a low screen resolution policy:
~~~
setDesignResolution( 1280, 720, SceneResolutionPolicy.NoBorder );
~~~
