### ISSUE TITLE
Can't seem to get shadow-casters to be visible above their shadows.

### ISSUE THREAD

**Issue by gmantaos** [prime31/Nez#295]
So I've been trying to get some basic lighting to work with the help of the samples and what's been happening is rather odd. It seems like the renderLayer that you asssign to the light processor and the PolyLights has absolutely nothing to do with the layer hierarchy. It doesn't matter what number I assign to it. if it's supposed to render below of above other things, the shadows will hide absolutely everything that is not EXACTLY on the light layer. And even if I did place these objects on the light layer, they would appear as some weird distorted version of the actual sprite. And even if that were acceptable, the other problem would be that they would be visible even when no light is cast on them at all.

So let's assume the following.
```csharp
PolyLight pointLight = new PolyLight(500, Color.White, 0.8f);
pointLight.renderLayer = RenderLayer.Light;
pointLight.collidesWithLayers = CollisionLayers.Shadows;

Entity entity= createEntity();
Sprite sprite = entity.addComponent(new Sprite(...));
sprite.renderLayer = RenderLayer.Fringe;  // Something above the ground that would cast a shadow.
Collider collider = entity.addComponent<BoxCollider>();
collider.physicsLayer = CollisionLayers.Shadows; // Make it cast a shadow.
```

In the above example, no matter what values I set for the execution orders on any of the renderers and post-processors, the sprite will always be hidden by its own shadow...

In the screenshot below those are actually objects with sprites that are set to interact with the PolyLight.

![screenshot_1](https://user-images.githubusercontent.com/29335643/31036676-0a8db602-a576-11e7-99eb-d731f2a2b119.png)

So for one I really hope this is not the intended behavior, I am not hidden by my own shadow...
When you have an object on a table, you can see the object's shadow BEHIND the object itself.

What am I doing wrong and how should I get the desired behavior?

If this is all the PolyLight is supposed to do for now, could I get some pointers on where I should look to improve on it and maybe open a PR?

Thank you in advance

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
