### ISSUE TITLE
deltaTime jumps when moving window

### ISSUE THREAD

**Issue by 0xFireball** [prime31/Nez#297]
Normally, even when paused due to not being focused, the `Time.deltaTime` remains relatively stable.

However, when the MonoGame window is moved, `Time.deltaTime` takes on much larger values, and this can lead to problems:

If a `deltaMovement` is calculated by multiplying a velocity by `dt`, this leads to significant motion jumps that can even lead to an entity "falling through the floor" as its position is updated to skip past any obstacles.

This could also lead to other issues for internal usages of deltaTime.

Workaround:

Enabling fixed timestep solves the problem.

**Comment by prime31** [comment]
Nez just reports delta frame time as it happens. This sounds like a bug on the MonoGame side of things so you’ll want to add it to their issue tracker.
