### ISSUE TITLE
Mouse position is incorrect

### ISSUE THREAD

**Issue by Async0x42** [prime31/Nez#3]
In the MacTest sample, as well as my own simple sample, the mouse coords are never correct.

In the attached image, the mouse is clicking on the D of debug, but a button is highlighted. However it's not always like that, sometimes the mouse can be in the middle of the blue area, and be highlighting a button. The offset can vary quite a bit.

> Activated	Event	Time	Duration	Thread
	Log: mouse pos: {X:1165 Y:176}, scaled mouse pos: {X:1165 Y:176}, screen to world point: {X:1165 Y:176}, world to screen point: {X:1165 Y:176}	58.04s		

Edit: And for example, with a screen of 1280x720, if I click the bottom right of the screen, the Y coord is over 800

![image](https://cloud.githubusercontent.com/assets/3268854/13066913/9f2806d4-d438-11e5-87f4-591189cf83df.png)

**Comment by Async0x42** [comment]
Closing this, I downgraded to the stable nuget packages for MonoGame, rather than the Visual Studio package on their site, and it's fixed the issue.

**Comment by Async0x42** [comment]
Er, sorry for multiple comments. I should have checked it out a bit more in depth, it does actually happen on 3.4 stable.

If the Design Resolution matches the base resolution, then there isn't an issue. If they don't match, then the mouse is offset incorrectly. Resizing the window will also cause the mouse coords to become incorrect.

>         public DKRpg() : base(1280, 720)
>         {
>             policy = Scene.SceneResolutionPolicy.ShowAllPixelPerfect;
>             Scene.setDefaultDesignResolution(640, 360, policy);
>             Window.AllowUserResizing = true;
>             Window.ClientSizeChanged += Window_ClientSizeChanged;
>         }

**Comment by prime31** [comment]
Is this fixed by adding in the changes mentioned in #2

**Comment by Async0x42** [comment]
Unfortunately it hasn't fixed the issue.
 
I have noticed, that the coords are correct in the log now, but the actual click location isn't.

Windows Size (640 x 360), clicking bottom-right
> Activated	Event	Time	Duration	Thread
> 	Log: mouse pos: {X:669 Y:379}, scaled mouse pos: {X:639 Y:359}, screen to world point: {X:639 Y:359}, world to screen point: {X:639 Y:359}	52.41s		

However, this isn't translated over to which buttons actually get highlighted on the screen.In this case, I can mouse over the D on debug, and the first button in the list is highlighted

![image](https://cloud.githubusercontent.com/assets/3268854/13079834/130b6f0e-d494-11e5-88aa-a139d171b79f.png)

**Comment by prime31** [comment]
IMGUI indeed doesn't take into account scaling by default. It was just made for "quick and dirty" UI that is designed to be rendered in world space until a proper GUI system/components are made.

Doing what you did and just sticking the scaled mouse position will be exactly what you want to do to use it with a resolution policy and not in world coords.

Now what is very odd is that you have a 640x360 window and you got a 669x379 click from the rawMousePosition. That could very well be a MonoGame bug. I just fired up a WindowsGL project and couldnt get that to happen myself.

**Comment by Async0x42** [comment]
Oh, I should've attached a screenshot for that. I had resized the window a little to trigger the mouse coord issue, so there were the black borders surrounding the main view. That's why the raw coords are higher than the view (which is fine, the issue was just that I had to offset the mouse to click actual IMGUI buttons)

Regardless, your fix in Issue 2 along with changing IMGUI resolves the issue for me, thanks!

**Comment by Async0x42** [comment]
Actually, is there a reason behind the mouse not taking scaling into account at all times? (If there is no scaling, wouldn't it end up being the raw value?)

I'm just wondering if there's a technical reason, because by default, if there is any scaling, IMGUI buttons basically can't be interacted with, rendering them useless unless Nez source is modified.

**Comment by prime31** [comment]
The whole IMGUI class is a bit of a hack and probably won't be around for much longer. Scaling the mouse in it globally wouldn't work for cases where IMGUI is used at full viewport outside of a scene. Perhaps a bool toggle in beginWindow could remedy this for all cases. True for scaled, false for unscaled.


On Feb 16, 2016, at 8:25 PM, Async0x42 <notifications@github.com> wrote:

Actually, is there a reason behind the mouse not taking scaling into account at all times? (If there is no scaling, wouldn't it end up being the raw value?)

I'm just wondering if there's a technical reason, because by default, if there is any scaling, IMGUI buttons basically can't be interacted with, rendering them useless unless Nez source is modified.

**Comment by Async0x42** [comment]
Understood, that clears it up, thanks! (Also, a bool toggle would work well. Until IMGUI goes away, at least it gives users the option and prevents confusion)
