### ISSUE TITLE
BitmapFontReader - Method not supported

### ISSUE THREAD

**Issue by meowgoocat** [prime31/Nez#30]
After updating to new version of Nez, I have experienced an issue with BitmapFontReader.  I get a Method Not Supported exception on this line:
`textures[i] = reader.ReadObject<Texture2D>();`

Changing this line by not calling ReadBoolean() seems to fix the issue (but obviously skirts the entire purpose of this check):
`var hasTextures = reader.ReadBoolean();`

I'm not sure if this error is related to my implementation or not, but there you go.

**Comment by meowgoocat** [comment]
Nevermind, seems to have something to do with a change in the format.  Was probably using old default font.

**Comment by prime31** [comment]
Exactly what I was just going to say! The format changed making textures now optional so rebuilding your font in the Pipeline tool will fix it up.
