### ISSUE TITLE
Hardcoded Terminal opening

### ISSUE THREAD

**Issue by Kasparsu** [prime31/Nez#303]
Well as I discovered theres 2 ways to open terminal either pressing ~ key or something called oem8 key. 
Neither of them are on Estonian layout. yes we are having issues with other games too to open terminals ;P but in this case would be to stop hardcoding them. yes I can fix it by editing nez code but this should be made cofigurable and may as well default to tilde but possible to override it.

**Comment by tanis2000** [comment]
Yes, I've got a similar problem with the Italian keyboard. Would you submit a PR for it?

**Comment by Kasparsu** [comment]
Sorry not intrested in Nez at this point anymore.

**Comment by Vanit** [comment]
Made a PR, once its merged you'll be able to override the default:

~~~
Nez.Console.DebugConsole.instance.consoleKey = Keys.F10;
~~~
