### ISSUE TITLE
height() doesn't update size of cell in table, post-initialization of table.

### ISSUE THREAD

**Issue by phxvyper** [prime31/Nez#305]
I'm initializing two tables that overlap in `onAddedToEntity()` here:

```cs
public override void onAddedToEntity()
{
    base.onAddedToEntity();
    isFullScreen = true;
    renderLayer = Utility.UILayer;

    var skin = Skin.createDefaultSkin();
    var barTable = stage.addElement(new Table());
    barTable.setFillParent(true).bottom().right();
    barTable.row()
        .bottom()
        .right()
        .setMinWidth(barWidth)
        .setPadRight(10)
        .setPadBottom(10);

    whiteVialBar = barTable.add(new Image(Content.Images.VialBar));

    whiteVialBar.getElement<Image>().setColor(Color.White);
    whiteVialBar.height(GetBarHeight(player.WhiteVial.Energy));

    var vialTable = stage.addElement(new Table());
    vialTable.setFillParent(true).bottom().right();
    vialTable.row()
        .setMinHeight(barHeight)
        .setMinWidth(barWidth)
        .setPadRight(10)
        .setPadBottom(10);

    whiteVial = vialTable.add(new Image(Content.Images.Vial));

    whiteVial.getElement<Image>().setColor(Color.White);

    player.WhiteVial.OnVialChanged += WhiteVial_OnVialChanged;
}
```

at the bottom of that block I subscribe to an event via the function `WhiteVial_OnVialChanged` in the same class, here: 

```cs
private void WhiteVial_OnVialChanged(object sender, VialChangedEventArgs e)
{
    whiteVialBar.height(GetBarHeight(e.Vial.Energy));
    whiteLabel.setText(e.Vial.Count.ToString());
}
```

I've double checked that the event is getting invoked, that my subscribed function is getting invoked, that `GetBarHeight` is returning the correct values I'm looking for.

I've also break pointed during the event to make sure that calling `whiteVialBar.height()` is actually setting the height of the cell, and it is.

Why does calling `height()` in `onAddedToEntity()` accurately change the bounds of the cell, but calling `height()` anytime later doesn't change how the cell is rendered at all? How do I change the size of a cell post initialization?

**Comment by phxvyper** [comment]
@prime31 sorry for the double mention, but this issue is still prevalent as well. I managed to hack my way through this issue by manually adjusting the position and height of the element itself - but if I were to change my alignment to `top()` instead of `bottom()` then I'd have to alter this code to account for that.

**Comment by Vanit** [comment]
Don't know if you still care, but the solution is to call invalidate() on the parent table after resizing the cell so it knows to recalculate its own height:

~~~
private void WhiteVial_OnVialChanged(object sender, VialChangedEventArgs e)
{
    whiteVialBar.height(GetBarHeight(e.Vial.Energy));
    barTable.invalidate();
    whiteLabel.setText(e.Vial.Count.ToString());
}
~~~

With that I believe this issue can be closed. :)
