### ISSUE TITLE
Nez scrollpane not showing scrollbars

### ISSUE THREAD

**Issue by cshiel** [prime31/Nez#307]
Example of issue:

`         
     
        var skin = Skin.createDefaultSkin();
         Window window = new Window("Shop", skin);
         stage.addElement(window);
         window.setResizeBorderSize(1);
         window.setSize(310, 360);
         window.setPosition(0, 0);

         Table table = new Table();

         Button b = new Button(skin);
         b.setBounds(0, 0, 1000, 1000);
         b.fillParent = true;

         ScrollPane pane = new ScrollPane(b);
         window.addElement(pane);
         pane.setBounds(0, 0, 200, 200);`

**Comment by Vanit** [comment]
You're probably long gone, but I was determined to find out how this worked and get some resolution for future reference. I couldn't get your specific example working, but I did work out one of your core mistakes was forgetting to set skin to the ScrollPane.

Here's a working example showing 20 buttons and a scrollbar:

~~~
var entity = createEntity( "ui" );
var ui = entity.addComponent( new UICanvas() );

var skin = Skin.createDefaultSkin();
Window window = new Window( "Shop", skin );
ui.stage.addElement( window );
window.setResizeBorderSize( 1 );
window.setSize( 200, 100 );
window.setPosition( 0, 0 );

Table scrollTable = new Table();

for( var i = 0; i < 20; i++ )
{
	Button b = new Button( skin );
	b.add( new Label( "Test "+i ) );
	scrollTable.add( b );
	scrollTable.row();
}

ScrollPane scroller = new ScrollPane( scrollTable, skin);
scroller.setBounds( 0, 0, 200, 100 );
window.addElement( scroller );
~~~

Which should appear like:
![scrollbars](https://user-images.githubusercontent.com/852857/35478224-2e9b099e-0423-11e8-9d2f-11051b027f77.png)

I believe this issue can be closed.

**Comment by cshiel** [comment]
This should not be closed as its odd behaviour that things just don't work "as is". Special tricks for getting components working is quite frustrating and time consuming. I'd recommend that scroll bars work by default.

**Comment by prime31** [comment]
Without a Skin, the scroll bar will not appear. It requires some sort of visual for it to be rendered. That is by design.

**Comment by cshiel** [comment]
Why isn't there a default skin?

**Comment by prime31** [comment]
There is a simple, image-less one if you choose to use it. See the example above.

**Comment by cshiel** [comment]
Why isn't the default skin applied by default?

**Comment by prime31** [comment]
Nez will never create all those textures without you asking for them specifically. All you have to do is create and assign a default skin if you just want placeholder colors in the UI.
