### ISSUE TITLE
AnimationCompletionBehavior.HideSprite causes a null reference exception

### ISSUE THREAD

**Issue by nhorne** [prime31/Nez#309]
To recreate the problem, update the fireball animation parameters in the Ninja Adventure sample scene (line 93 of NinjaAdventureScene.cs) so that loop = false and completionBehavior = AnimationCompletionBehavior.HideSprite then shoot a fireball.

The HideSprite completion behavior sets the sprite's subtexture to null after the animation ends (line 141 of SpriteT.cs). The subtexture is then accessed the next time the Sprite's bounds are checked (line 19 of Sprite.cs).

My workaround has been to disable the SpriteT component rather than setting subtexture to null and then re-enable it in the play function, but I'm not sure if there is a more appropriate solution.

**Comment by tanis2000** [comment]
I agree that setting the SpriteT component would be more appropriated than setting the subtexture to null. Care to submit a PR?

**Comment by Vanit** [comment]
I believe this issue can be closed.
