### ISSUE TITLE
Matcher isInterested returning wrong result

### ISSUE THREAD

**Issue by RobinPerris** [prime31/Nez#31]
So I'd usually just fix this kind of thing myself, but I'm struggling to understand how exactly the matcher is storing/comparing types.

I'm adding an entity processor like so:

`addEntityProcessor(new CombatSystem(new Matcher().all(typeof(CharacterComponent))));`

However, this matcher is returning 'true' when an entity with a ~~`DialogueComponent`~~ `Sprite<T>` attached is getting passed through for comparison. This entity does _not_ have a `CharacterComponent` attached.

~~When debugging I take a look within the Matcher class.~~

~~`public bool isInterested( BitSet componentBits )`~~

~~From what I can see, when looking in to the componentBits that are passed in, both `DialogComponent` and `CharacterComponent` are being represented as {0}, causing the matcher to register my entity for a system it shouldn't do.~~

Edit: All of that is wrong. This seems related to the `Sprite<T>` component instead.

**Comment by prime31** [comment]
Do you have a stripped down repro available? That would help in identifying exactly what is going on here.

**Comment by RobinPerris** [comment]
Good call on that. Turns out this is caused by the `Sprite<T>` component, not my custom components.

From what I can see, the `Sprite<T>` component is being registered as {0} in the matcher, but so is my custom component. As such, _anything_ I place a SpriteAnimation on gets picked up by the matcher.

I've thrown a gist up here: [Minimal example](https://gist.github.com/RobinPerris/510b2c3b5b274d5d93b86de1d914b0ce)

If you place that in the ProjectTemplate project and put a 32x32 texture in the Content it should run out of the box. I can upload a copy of the repo if you'd prefer.

Hope this helps. I'll try looking in to the problem later tonight to see if I can find out why this is happening. (Although this bit stuff is a bit over my head.)

**Comment by prime31** [comment]
Hmm. Oddly enough the minimal example works fine for me. I changed one line just to see the successful matches:

```csharp
		public override void process( Entity entity )
		{
			if( entity.name == "dialogue" )
				throw new Exception( "Sprite<T> getting recognised in a matcher for CharacterComponent." );
			else
				Debug.log( "matched: {0}", entity.name );
		}
```

One place you may want to give a look is the ComponentTypeManager.getIndexFor method. If you stick a break point there and have a look at the _componentTypesMask field that should contain every Component subclass with a unique int for each one.

**Comment by RobinPerris** [comment]
That's very strange. I ran it on a second computer and got the same results.

I added a Debug.log call to ComponentTypeManager.getIndexFor and got the following:

```
Log: Returned index '0' for type 'ProjectTemplate.CharacterComponent'.
Log: Returned index '1' for type 'Nez.Camera'.
Log: Returned index '0' for type 'ProjectTemplate.CharacterComponent'.
Log: Returned index '0' for type 'Nez.Sprites.Sprite`1[System.Int32]'.
```

At a glance it appears like a key exists, however the type being passed in isn't getting recognised as being a key in the dictionary.

I replaced the method with this and got a KeyNotFoundException:

```csharp
public static int getIndexFor( Type type )
{
    var v = -1;
    v = _componentTypesMask[type];
    return v;
}
```

Whilst a key exists for ```Nez.Sprites.Sprite`1[TEnum]``` it's not being picked up when ```Nez.Sprites.Sprite`1[System.Int32]``` is being passed in.

Would you be able to log the results on your machine? I'd be interested to see what your type is being passed through as for `Sprite<T>`.

**Comment by prime31** [comment]
I am seeing all the expected types added to the list:
<img width="582" alt="screen shot 2016-05-25 at 2 53 49 pm" src="https://cloud.githubusercontent.com/assets/60377/15557551/bf294da0-2288-11e6-9123-ff9f301ab071.png">

The log line is also returning the expected output:

```
Log: Returned index '1' for type 'MacTester.CharacterComponent'
Log: Returned index '2' for type 'Nez.Camera'
Log: Returned index '1' for type 'MacTester.CharacterComponent'
Log: Returned index '0' for type 'Nez.Sprites.Sprite`1[System.Int32]'
```

**Comment by prime31** [comment]
It almost seems like your Component subclasses are not getting added. Stick a breakpoint in `ComponentTypeManager.initialize` and make sure that your assembly is in the `assemblies` variable when it is fetched. That's the only thing I can think of that could be causing the issue.

On a related side note, I think I just got an idea to make the whole registration system work in an automatic fashion but I'll need to do some testing.

**Comment by RobinPerris** [comment]
That isn't the expected result though, is it?

```Log: Returned index '0' for type 'Nez.Sprites.Sprite`1[System.Int32]'```

You're getting an index of 0 which is the index of 'FollowMouse'. The types aren't getting registered in the same order, which is causing my example to fail.

If you modify the minimal example to have a system run a matcher on 'FollowMouse' instead it should exhibit the wrong behaviour I raised.

**Comment by prime31** [comment]
Wait a second. You are absolutely right. Sprite<int> isnt registered at all. I think I might have an idea of what is happening. Digging in now.

**Comment by prime31** [comment]
So, it appears types created from generics are not present in the initial assembly check. I guess they are JIT compiled and created on the fly. Try changing the getIndexFor method to be the following:

```csharp
		public static int getIndexFor( Type type )
		{
			var v = -1;
			if( !_componentTypesMask.TryGetValue( type, out v ) )
			{
				add( type );
				_componentTypesMask.TryGetValue( type, out v );
			}

			return v;
		}
```

If it doesnt find the component mask it will just add it on the fly so all classes should work. I'm still testing this but it should do the trick.

**Comment by RobinPerris** [comment]
Huh, that's actually really interesting. Might have to look in to that a bit more.

Thanks for the fix - and for teaching me something new about generics.
