### ISSUE TITLE
Create a new release and/or tag?

### ISSUE THREAD

**Issue by KenRud** [prime31/Nez#310]
I'm looking into using Nez in a new project and was wondering if there have been any new releases since 0.9 which was on 10/09/2016. The README seems to indicate that I should just work from HEAD, but I am worried about stability issues. Can we create a new release branch or tag that indicates a stable state in which new developers can work from?

**Comment by prime31** [comment]
There are no plans to add any more releases. Almost everyone just downloads the source (which is highly recommended anyway).
