### ISSUE TITLE
PrototypeSprite.cs

### ISSUE THREAD

**Issue by 1509489** [prime31/Nez#313]
Hi, I am trying to follow your tutorial on youtube but when I run the game, I get this error

> System.NullReferenceException occurred
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=Nez
>   StackTrace:
>    at Nez.PrototypeSprite..ctor(Single width, Single height) in D:\ComputerScience\Level3\Games Design\Nez-master\Nez.Portable\ECS\Components\Renderables\Sprites\PrototypeSprite.cs:line 40
>    at Shoot_em_up.Scene1.initialize() in D:\ComputerScience\Level3\Games Design\Course_Work\Shooter\Shoot'em up\Shoot'em up\Scene1.cs:line 25
>    at Nez.Scene..ctor() in D:\ComputerScience\Level3\Games Design\Nez-master\Nez.Portable\ECS\Scene.cs:line 317
>    at Shoot_em_up.Scene1..ctor()
>    at Shoot_em_up.Game1.Initialize() in D:\ComputerScience\Level3\Games Design\Course_Work\Shooter\Shoot'em up\Shoot'em up\Game1.cs:line 31
>    at Microsoft.Xna.Framework.Game.DoInitialize()
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
>    at Shoot_em_up.Program.Main() in D:\ComputerScience\Level3\Games Design\Course_Work\Shooter\Shoot'em up\Shoot'em up\Program.cs:line 17

the error points to this constructer in the PrototypeSprite.cs 

```
public PrototypeSprite( float width, float height ) : base( Graphics.instance.pixelTexture )
{
	_width = width;
	_height = height;
	originNormalized = new Vector2( 0.5f, 0.5f );
}
```
the `base( Graphics.instance.pixelTexture )` is where the error occur. Could you please help. I am using Monogame 3.6

**Comment by prime31** [comment]
Using MG 3.6 you are on your own. All the Nez code and samples are compiled against, and tested with 3.5. We could not come up with any good reason to move to 3.6. If you insist on using 3.6 now would be a good time for you to learn how to use the debugger and trace through the code to see where the NRE is occurring. It is not a deep stack trace and should be quite easy to locate and remedy.
