### ISSUE TITLE
Performance of EntityList remove and contains can be improved

### ISSUE THREAD

**Issue by ThomasZeman** [prime31/Nez#314]
In EntityList.cs "remove" and "contains" run a linear search over a list (entitiesToRemove.Contains) which means that when a large number of entities is removed during one update cycle (or added b/c of entitiesToAdd.Contains) a lot of CPU time is burned in these methods. E.g. removing 1000 items leads to 0+1+2+3...+999 = 499.500 operations instead of 1000.
Same applies to addEntity in Scene.cs. This could lead to serious performance hickups when there is larger number of entities in the scene.
Changing the toRemove and toAdd collections to HashSets would solve this.

**Comment by tanis2000** [comment]
Yes, that makes sense and I can't see any reason against turning those Lists into HashSets. A PR would be appreciated.

**Comment by Vanit** [comment]
I believe this issue can be closed now?
