### ISSUE TITLE
FollowCamera not behaving as expected

### ISSUE THREAD

**Issue by Aeirex** [prime31/Nez#321]
I have a large tilemap, it seems to clamp my sprite (character) to a specific region. Maybe it is the resolution size or something, I don't really know.

When I walk, it works. If I modify the transform.position or position in the code, it only allows me to move so far on the map, then it clamps my X/Y to the edge of whatever value it is.

**Comment by Vanit** [comment]
As its been a while since you've posted I think we can assume you've resolved the issue or moved on.

I believe this issue can be closed.
