### ISSUE TITLE
How to stop SceneTransition

### ISSUE THREAD

**Issue by 1509489** [prime31/Nez#322]
I keep getting an Assertion Failed when I call the `Core.startSceneTransition(new FadeTransition(() => new Scene1()));` saying: _You cannot start a new SceneTransition until the previous one has completed_

How can I stop the scenetransition?

**Comment by Vanit** [comment]
It sounds like you may be unwittingly invoking *Core.startSceneTransition* multiple times (perhaps through a repeatedly triggering collider).

As its been a while since you've posted I think this issue should be closed, but feel free to reopen it.
