### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by EReeves** [prime31/Nez#326]
I'm sure this is a personal thing but, why is the naming in Nez like a java library? Shouldn't it be C# in nature? It would clash with the majority of developers using it.

Examples being all the public methods and properties starting with lower case rather than a capital.

A few other C# frameworks have leftovers from java, c++ and other such languages, but they are mostly all working on removing them and making them use C# style naming conventions.
A good example is OpenTK https://github.com/opentk/opentk/issues/566

I'd be happy to go through renaming the core stuff and send a pull request, renaming other stuff as I encounter it in my projects or get the time.

**Comment by prime31** [comment]
I am personally not a fan of the C# style guidelines and don't really see any reason to follow them. Many Microsoft engineers themselves don't even like them but they are stuck with them now so not much can be done about it (for them at least). As an added benefit (besides not having to use your shift key all the damn time ;) you will always clearly know what is a .NET/MonoGame API and what is a Nez API call.

**Comment by EReeves** [comment]
Ok, non issue then.

**Comment by prime31** [comment]
You can think of the style as more of an Apple inspired set of guidelines. They seem more well thought out than Microsoft’s ancient guidelines.

**Comment by prime31** [comment]
I should add, imo it’s more important for a codebase to follow a fairly strict set of guidelines. Which those are is less important and really is just a matter of taste.

**Comment by EReeves** [comment]
Not really important now that this is closed, but I batch renamed my Monogame 3.7 fork with Resharper/Jetbrains naming conventions just for the hell of it.

https://github.com/EReeves/Nez/commit/a36c3ebbe642d0639d24609fdb6a0d233d1fcc4a
