### ISSUE TITLE
getComponent returns components which haven't been added to an entity yet

### ISSUE THREAD

**Issue by RobinPerris** [prime31/Nez#33]
Component initialisation logic is placed in `onAddedToEntity()`

However, there doesn't seem to be a way to find out if a component has _actually_ been added to the entity yet - meaning there's no way to find out if custom component initialisation code has been run yet.

`getComponent` methods within `ComponentList` return components which are within the `components` list _as well as_ `componentsToAdd`. 

I currently have the following code in a system. The system is being added to the scene the same frame the `PlayerInputComponent` is being added to the entity.

```csharp
var input = player.getComponent<PlayerInputComponent>();

if (input.xAxisInput.value < 0)
    moveLeft();
```

The `xAxisInput` property isn't initialised until the component is added to the entity, so this falls down.

I _could_ place checks everywhere in my code to make sure I don't reference things which haven't been initiated, but I feel like this would be better solved by:

1. Adding additional variations on `getComponent` which allow you to only return components which have been initialised. (Preferred - no additional checks required)

2. Some sort of flag on the component which tells you whether it has been added or not. (Requires extra conditionals)

At the moment I've just removed the checks to the `componentsToAdd` in the `getComponent` method, but this is specific to my needs and I'd love the core library to support this out of the box.

More than happy to write the code, would just like your input on possible solutions first.

**Comment by prime31** [comment]
One possible solution could be to delay adding the Component to the entity systems until it is actually added to the main components list. That only solves this specific case though and there may be other non-entity systems cases that hit the same situation.
