### ISSUE TITLE
Ability to use the Nez UI without Nez.

### ISSUE THREAD

**Issue by msmshazan** [prime31/Nez#332]
I wanted to use the Nez UI system but without including the whole nez library but at the moment it depends on Nez . Will it be possible to make it independent of Nez ?

**Comment by prime31** [comment]
The source is there if you want to dig through and remove the Nez bindings. In the end it does all drawing through methods identical to the MonoGame SpriteBatch so it shouldn’t be too much work to gut the Nez parts.

I personally have no plans to do that though. The entire point of Nez is to cover the basics of what a game needs in one package. All the parts are there for anyone to use who wants to adapt it for their projects.
