### ISSUE TITLE
Close hanging issues?

### ISSUE THREAD

**Issue by Vanit** [prime31/Nez#334]
It seems that over time a lot of issues have built up that were either too vague to solicit help or the author abandoned them, and its starting to look a bit messy. I'm happy to volunteer to review them and comment on the ones that need closing, but just want to check if there's not a better process for this.

**Comment by prime31** [comment]
I’m all for that. Feel free to just stick a comment on any dead/abandoned issues and I’ll close them out.

**Comment by Vanit** [comment]
Well I made a bit of progress (as you'd know)!

My intention going in wasn't to fix the outstanding bugs, but now I'm determined to try get Nez (somewhat close) to "issue 0". Will do another round of review tonight :)

**Comment by prime31** [comment]
"A bit" is an understatement. You're a full on bug killer!

**Comment by Vanit** [comment]
FYI this is still on my radar; this is not a hanging issue :)

**Comment by prime31** [comment]
I’m hiding out in Hawaii at the moment so I won’t notice anything at all until I get back to work in a few days ;)

**Comment by Vanit** [comment]
@prime31 Back soon? Got a few PRs/issues that just need you to sign off on the resolution :)

**Comment by prime31** [comment]
I’m mostly back, physically at least. I’ll checkout the PRs later today.

**Comment by Vanit** [comment]
I fear this has itself become a hanging issue :) I'm still hanging around checking things, but I'm basically happy that a lot of the low hanging fruit that could be resolved has been.
