### ISSUE TITLE
KeepWithinStage not working for windows/dialogs

### ISSUE THREAD

**Issue by brandc87** [prime31/Nez#338]
Seems it was unrelated too the other issues. If you drag a window past the stage the image/background stays in but the actual bounds of the window continues to move.

You can see this with debugAll() running. Some screenshots:
When game loads the windows bounds are correct,
![screen shot 2018-01-25 at 16 30 33](https://user-images.githubusercontent.com/11300674/35399881-42149bb2-01ed-11e8-9911-c8a8f9aea5fb.png)

Here I've tried to drag the window off screen to the left the image stays in but the bounding box continues moving.
![screen shot 2018-01-25 at 16 30 42](https://user-images.githubusercontent.com/11300674/35399882-423ea3da-01ed-11e8-90c3-6d9f0021022b.png)

**Comment by Vanit** [comment]
Happy to look into it - can you post a snippet of code that reproduces the issue?

**Comment by brandc87** [comment]
Sure,

```
using System;
using Microsoft.Xna.Framework;
using Nez;
using Nez.UI;

namespace Test
{
    public class TestScene : Scene
    {
        public TestScene()
        {
            addRenderer(new DefaultRenderer());

            var canvas = createEntity("ui").addComponent(new UICanvas());
            canvas.isFullScreen = true;
            canvas.renderLayer = 100;

            var table = canvas.stage.addElement(new Table());
            table.setFillParent(true);

            var window = new Window("Window", new WindowStyle(Graphics.instance.bitmapFont, Color.White, new PrimitiveDrawable(250, 250, Color.DimGray)));
            window.setPosition(20, 20);
            window.pad(20);
            canvas.stage.addElement(window);

            window.debugAll();
        }
    }
}
```

If you drag the window off the edge the PrimitiveDrawable will stay but the bounds of the window continue to move, meaning if a user let go of the mouse off screen the window will no longer respond to any input.

Thanks.

**Comment by Vanit** [comment]
Got a PR, easy fix :)
