### ISSUE TITLE
Exception When Setting Tag on Entity

### ISSUE THREAD

**Issue by someone2b** [prime31/Nez#347]
Setting the tag on an entity after using the scene method `createEntity(string name)` causes an "System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary."

```
entityText = createEntity("text");
entityText.tag = ENTITYTYPE.SCENE; //Exception here
```

I have not dug deep enough to know the exact things that need corrected to avoid this. Note that the following sequence does not raise the exception because it keeps scene null while setting the tag. Note that I am calling these from Initialize().

```
entityBackground = new Entity("background");
entityBackground.tag = ENTITYTYPE.SCENE;
addEntity(entityBackground);
```
I haven't dug deep enough into the life-cycle of Entities to identify the ideal fix for this issue. Alternatively, am I mis-using the tag by setting it in Initialize()?

**Comment by someone2b** [comment]
I wish I could be more useful, but I will say that testing on more recent commits suggests that between fc9c1b7 and the current Head several changes were made to the Entity and Scene system that cause my game to break. I have reverted to fc9c1b7 for now since there aren't any features I am lacking, but am hopeful that by working on the specific issue above the ECS can be redesigned a bit to work around the issues.

I think there must be some missing checks in the Entity adding/removing functions on scene.

**Comment by Vanit** [comment]
Fixed, thanks for the report. The issue was specifically in the tag code, and not with entity handling overall.
