### ISSUE TITLE
Stopwatch resolution

### ISSUE THREAD

**Issue by xposure** [prime31/Nez#350]
The stopwatch included in Nez is extremely inaccurate because the nature of Ticks are inaccurate. Nez needs to use the Stopwatch from System.Diagnostics. Its literally drop in and replace after changing a few casings on variables and provides the TimeRuler with correct output.

I spent an embarrassing amount of time trying to figure out why the TimeRuler was bouncing all around (and off the screen) between each frame with a blank scene and a simple Sleep(5) in both render and update. Constantly the timer was returning 0 instead of a value near 5 and after gutting a lot of code and realizing that the stopwatch I was looking at was hand rolled from silverlight it became clear what was going on.

Not sure how to really submit a PR as I'm working on a fork of a fork and I guess the only way to really do a PR would be to clone this repo and submit the changes here and hope the person I forked pulls it so I can then pull his fork?

**Comment by prime31** [comment]
Hmm. If I recall, the reason the class was made is because the Stopwatch doesn't exist in PCLs. I could be mistaken on that but I am about 90% sure that is why a custom Stopwatch was created.

**Comment by Vanit** [comment]
@xposure Can you post the code for an example scene that demonstrates the issue?

**Comment by xposure** [comment]
@Vanit You can simply test this inside of a console project by doing ...

```
var sw = Nez.Analysis.Stopwatch.startNew();
System.Threading.Thread.Sleep(5);
sw.stop();
Console.WriteLine(sw.elapsedTime.TotalMillisecinds);

```

As for a scene simply create a blank scene, enable the ruler with showLog and sleep for 5ms. It won't report accurately depending on the system you are on as the system ticks are low resolution.

You can also inspect the Stopwatch class source from MS to see how it handles high resolution timers, some systems don't support it and you can check the flag on the class to see if your system does.

@prime31 Its possible, but it's there now in System.Diagnostics without any change to the project and it will have the TimeRuler report correctly on systems with a hires timer. It seems that the TimeRuler class is the only system to use it, so likely nothing would break internally.

**Comment by xposure** [comment]
https://github.com/xposure/FFNez/commit/daa294b534158fc15e3bb46afed0583da219a6be

I have also added ToString methods on most of the TimeRuler objects while trying to debug and see what was going on. Not sure if thats the sort of thing you would want, also seems like I'm using tabs over spaces if I had to guess.

**Comment by prime31** [comment]
ToString methods can always be of use (especially for classes that only live in Debug builds) so feel free to send over a PR. The latest version has the Stopwatch change now also.
