### ISSUE TITLE
Nez.Core is missing Xna?

### ISSUE THREAD

**Issue by jacobcoughenour** [prime31/Nez#351]
(I'm new to Nez)

I have the latest Nez (portable) as a submodule and added to my solution.  It was able to run with a test scene the first time, but after restarting VS, everything in the Nez (Portable) csproj can't find Microsoft.Xna even though the MonoGame.Framework reference isn't broken.

Am I missing something?

**Comment by jacobcoughenour** [comment]
I found that my project builds perfectly if I build Nez and use the Nez.dll as the reference instead of the csproj

**Comment by Vanit** [comment]
I think there's an undocumented step here; you need to build the Nez solution first separately to have to load all its dependencies.

- Open the Nez solution directly in VS (not your own project solution)
- Build the solution
- Return to your own project's solution, should just work

**Comment by Vanit** [comment]
@jacobcoughenour Did you get it working?

**Comment by jacobcoughenour** [comment]
@Vanit Yes.  I made a fresh project and setup up everything again and now it works.  I must have missed something the first time.  Thanks!
