### ISSUE TITLE
Inspector Layout Problem

### ISSUE THREAD

**Issue by massanchik** [prime31/Nez#352]
Hi!
I'm just started learning monogame/nez and decided to make simple pong with the engine.
So problem is when I typing "inspect ball"(ball is the entity name) in to console it's showing inspector with some layout issues.
Screenshot of the game window: 
![inspectorlayout](https://user-images.githubusercontent.com/3767814/36343622-271a78e0-1417-11e8-8ebe-b0158761d1a8.png)

**Comment by massanchik** [comment]
Windows 10 x64
I have putted on scene the "ball" entity with texture and circle collider components. 
As you can see on screenshot, there is a longish length named parameter on circle collider section on the inspector.
From first glance that is looks like an issue maker.

**Comment by Vanit** [comment]
Ahhh, I totally skimmed over that; you're right that definitely looks to be the issue, will look into it.

**Comment by prime31** [comment]
Good spot! It’s probably just a char limit that needs to be enforced to work around that.

**Comment by Vanit** [comment]
I was just planning to make that specific property less verbose to start, like "scaleAndRotateWithTransform".

**Comment by Vanit** [comment]
Ah wait, strike that - that's definitely a breaking change. Guess will truncate or word break or something.

**Comment by massanchik** [comment]
Another variant is to make inspector width flexible and make some transparency slider or field, so that user can see what's actually  happening in the game behind the inspector. Last one will be useful anyway)

**Comment by massanchik** [comment]
One more option is to make one volumn layout, where a parameter name is above its value, instead of two columns, where a parameter name is on the left side of a value.

**Comment by jbhaywood** [comment]
I've run into this too. I would be nice to get it fixed, one way or the other.
