### ISSUE TITLE
Strange property declaration

### ISSUE THREAD

**Issue by ApmeM** [prime31/Nez#358]
Those property in Transform looks strange:
https://github.com/prime31/Nez/blob/f57759101dced1b6f6ebde5c0ff91fd9e4d7448b/Nez.Portable/ECS/Transform.cs#L147

- it gets _localRotation without calling updateTransform (as localRotation does)
- and at the same time rotationDegrees call setRotation instead of assigning rotation
- why localRotation calls updateTransform? it is local.
- it sets to property instead of calling setLocalRotationDegrees (as rotationDegrees do)

Also entity properties for same set looks different:
https://github.com/prime31/Nez/blob/f57759101dced1b6f6ebde5c0ff91fd9e4d7448b/Nez.Portable/ECS/Entity.cs#L137

- it calls setLocalRotationDegrees (in opposite to localRitationDegrees in Transform)
- it do not call properties from transform but do almost same (except this strange property)

Unfortunately I cant create a patch for my issue because I do not understand how it actually should work. Each property goes its own way in current code.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
