### ISSUE TITLE
active/enable consistency

### ISSUE THREAD

**Issue by xposure** [prime31/Nez#360]
1. Entity states that `enabled` controls the lifecycle events.
2. Components have `active` and `enabled` one controlling update and one controlling rendering.

Is there really a good reason to split these up as it leads to confusion. For example I assumed unchecking the box in the inspector for the component would disable that component but its update methods continue get called, it instead disables the rendering for the component.

Should there be a 2nd check box to control the update of a component in addition to rendering?

**Comment by xposure** [comment]
Putting this here to see if there is interest...

https://github.com/xposure/FFNez/commit/04531a1b97a9a6d1b56acdc249ab3e9e5891ddac

**Comment by HenrySipp** [comment]
This really makes sense to do IMO.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
