### ISSUE TITLE
Should entity transforms round the position by default?

### ISSUE THREAD

**Issue by EReeves** [prime31/Nez#367]
So right now when you set the position of an entity it rounds the value by default.
This kind of removes the point of having a Vector2 made of floats, when using a data structure made of floats, you expect to be able to set them to float values.

Is it because of issues rendering entities at float positions? This should be resolved at rendering, it causes lots of issues. I spent far too long trying to figure out why this didn't result in the entity moving in the direction I wanted.
 `position += direction * speed;` //where direction is a directional Vector2 with float values.

Turns out it wasn't an issue with my math for finding the direction.

**Comment by prime31** [comment]
fixed by commit 837d9e359885775f6364c9735c37757d3f04328a
