### ISSUE TITLE
Behavior Tree abort bugs?

### ISSUE THREAD

**Issue by brettmjohnson** [prime31/Nez#37]
I've written a couple of behavior trees to test how the aborts work and it seems like there might be a bug or two. It's entirely possible this is working as it should and I'm just not understanding how aborts work.

Here's the code:
`
		bool test = true;

		TaskStatus ToggleTest()
		{
			test = !test;
			return TaskStatus.Success;
		}

		public BehaviorTree<BehaviorTreeMiner> buildSelfAbortBugTree()
		{
			var builder = BehaviorTreeBuilder<BehaviorTreeMiner>.begin( this );

			builder.selector( AbortTypes.Self );
			{
				builder.conditionalDecorator(m => m.test, false);
				builder.sequence()
					.logAction("1-1")
					.action( m => m.ToggleTest() )
					.logAction("1-2")
					.endComposite();

				builder.conditionalDecorator(m => !m.test, false);
				builder.sequence()
					.logAction("2-1")
					.action( m => m.ToggleTest() )
					.logAction("2-2")
					.endComposite();
			}
			builder.endComposite();

			return builder.build();
		}

		public BehaviorTree<BehaviorTreeMiner> buildLowerPriorityAbortBugTree()
		{
			var builder = BehaviorTreeBuilder<BehaviorTreeMiner>.begin( this );

			builder.selector();
			{
				builder.sequence(AbortTypes.LowerPriority)
					.conditional( m => m.test )
					.logAction("1-1")
					.action( m => m.ToggleTest() )
					.logAction("1-2")
					.endComposite();

				builder.sequence(AbortTypes.LowerPriority)
					.conditional( m => !m.test )
					.logAction("2-1")
					.action( m => m.ToggleTest() )
					.logAction("2-2")
					.endComposite();
			}
			builder.endComposite();

			return builder.build();
		}
`

And here's the output for each test:
![low abort bug](http://i.imgur.com/Ay1UJQF.png)
![self abort bug](http://i.imgur.com/5EFWMif.png)

**Comment by prime31** [comment]
Everything looks as it should be for the lower priority abort. A lower priority abort only looks for conditionals in a branch that is a sibling to the current branch (a separate branch to it's left). When running the left branch there is no further left branch that gets checked.  When running the right branch the conditional before the "log 1-1" node will get checked for the abort.

For the self abort example, it looks like there is a bug where the Decorator's child task is not getting invalidated. I'll push a fix for that momentarily.

With regard to the first sequence finishing that is the expected result. The self abort Conditional only aborts siblings. So in this example, the two siblings are both conditionalDecorators so the 1st conditionalDecorator can abort the second if it changes but the first cannot abort itself. I believe what you are looking for can be achieved by just setting shouldReevaluate to true on the first conditionalDecorator like so:

`builder.conditionalDecorator( m => m.test, true );`
