### ISSUE TITLE
Removing the need for System.Drawing.Drawing2D to create paths

### ISSUE THREAD

**Issue by Blucky87** [prime31/Nez#378]
I am in the process of converting my fork of Nez to a .Net Core Class Library w/ .net standard 2.0 framework for cross compatibility reasons but ran into an issue. 

I noticed Nez's SVG implementation relies on System.Drawing.Drawing2D and it's GraphicsPath class. Is the only reason for using GraphicsPath to easily calculate paths?

I am going to look more into this tonight if you do not get back to me in time. But, if it is only being used for generating a path I am going to try and port over [Lily Path](https://github.com/jaquadro/LilyPath)'s path creation features into my fork to replace Nez's SVGPathBuilder and company.

**Comment by prime31** [comment]
System.Drawing is only used for paths. The API is entirely reflection based by default so you don't even have to link to System.Drawing at all. See the `ISvgPathBuilder` for details.
