### ISSUE TITLE
Loading models after first scene init seems to render them

### ISSUE THREAD

**Issue by Lucas-Brown-CSS** [prime31/Nez#379]
I've found this weird issue where Model assets that are loaded after the first scene init seem to be rendered on top of the scene. I stumbled onto this when looking at adding multiple maps to my game via scene transitions. At first I thought maybe Nez was doing something weird during the transitions, but after some investigation I found the issue would occur if there's no scene movement at all.

![cube](https://user-images.githubusercontent.com/36827387/38768441-31754d82-4037-11e8-8856-5b203c5e741a.png)

In this scene the sphere is loaded first (no issue), but when the cube is loaded it appears. I didn't realise it at first, but the black artifact is the cube itself, not some side effect. If you switch the cube/sphere models in the sample code the artifact changes (entire screen blacks out because the sphere is larger).

It may be that this is a Monogame issue rather than a Nez issue, but I'd appreciate it if someone could reproduce this, especially if its with their own models.

Model files: [Content.zip](https://github.com/prime31/Nez/files/1910382/Content.zip)
~~~
public class GameScene: Scene
{
	VirtualButton input;

	public GameScene()
	{
		addRenderer(new DefaultRenderer());
	}

	public override void initialize()
	{
		var cube = content.Load<Model>( "sphere" );

		input = new VirtualButton();
		input.nodes.Add( new Nez.VirtualButton.KeyboardKey( Keys.E ) );
	}

	public override void update()
	{
		if( input.isPressed )
		{
			var cube = content.Load<Model>( "cube" );
		}

		base.update();
	}
}
~~~

**Comment by Vanit** [comment]
Ack, accidentally posted this on my work account, oh well :P

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
