### ISSUE TITLE
worldToScreenPoint is inaccurate when using FollowCamera and inside deadzone

### ISSUE THREAD

**Issue by raykuhnell** [prime31/Nez#380]
If you add a FollowCamera to your scene and have it track an entity, the values move as expected normally, but when the entity enters the deadzone, the values returned from Camera.worldToScreenPoint continue to change even though the camera position does not change.

This issue can be reproduced by using worldToScreenPoint in the NinjaAdventureScene in the Nez.Samples.

**Comment by SolarOmni** [comment]
Just ran into this problem myself when approaching the deadzone of my tiled map and trying to get the world position of an enemy by clicking on it.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
