### ISSUE TITLE
TrailRibbon not rendering when added to an Entity

### ISSUE THREAD

**Issue by r0adkll** [prime31/Nez#381]
When I add the `TrailRibbon` component to my entity like so:

```csharp
var ribbon = entity.addComponent(new TrailRibbon(64));
ribbon.renderLayer = 2;
ribbon.ribbonRadius = 32;
```

It does not appear to render in the scene. 
I am also using the `Mover` class to move this entity around

Other information:
macOS High Sierra v10.13.4 Beta
Visual Studio Community v7.4.3  (build 10)
MonoGame v3.6.0.1625

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
