### ISSUE TITLE
Is there a way to know if a UI element has the focus ?

### ISSUE THREAD

**Issue by DomDumont** [prime31/Nez#389]
Hi,

My main character can move using the arrow keys.
but my main UI contains many TextFields and this cause some problems.
I would like to know if any of those Textfields has the focus in order to avoid moving my main
character when I am editing a text.

I am using a VirtualIntegerAxis to move my character, it may be cool to have an automatic way to stop updating it when a UI element has focus.

Thanks

**Comment by Scellow** [comment]
Check this: https://github.com/prime31/Nez/blob/master/Nez.Portable/UI/Stage.cs#L665

**Comment by Scellow** [comment]
If you are interested here is the code:  (Input.cs / Stage.cs)
https://gist.github.com/Scellow/8ec1dd3d43b3e7edd7fcd0848d991acb

It's part of the engine i wrote when i was using MonoGame back in the days (it is fully decoupled from Nez ECS)

```c#
// pseudo code

Core.input = new Input(game);

void update()
{
    Core.input.update(gameTime);
    
    // gamelogic
    onUpdate();
    
    Core.input.prepareNext();
}

(..)


var gameController = new MyGameController();
var stage = new Stage();
var processor = new InputMultiplexer(stage, gameController);
Core.input.setInputProcessor(processor);
```

Just like libGDX :p

**Comment by DomDumont** [comment]
Thanks a lot, this will help me !

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
