### ISSUE TITLE
Blurry bitmap fonts

### ISSUE THREAD

**Issue by DomDumont** [prime31/Nez#393]
Hi,
As the default font does not support french accents, I tried to create my own bitmap font using Littera. Unfortunately the final result seems very blurry compared to the default font. Is it a scale or alias problem ?
Is there a flag to set somewhere ? Should I use a skin instead of a style ?
In my current  code I use a style like this :
    
 ```
           var font = entity.scene.content.Load<BitmapFont>("myfont");

            var labelStyle = new LabelStyle();

            labelStyle.font = font;

```

Any help appreciated.

Thanks

**Comment by prime31** [comment]
The default font is just a plain old bitmap font but it makes sure to use point filtering. For pixel art you need point filtering else everything is blurry

**Comment by DomDumont** [comment]
Finally it was due to the font. With a good pixel font and the right size everything is now ok !
