### ISSUE TITLE
Use standard .Net naming conventions and Field Design guidelines

### ISSUE THREAD

**Issue by JeroMiya** [prime31/Nez#396]
.Net/C# is different than many languages/runtimes in that it has a documented set of standardized naming conventions. Please use them - there isn't any reason not to (even when you're doing P/Invoke) and it creates confusion otherwise.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members

Also, please consider following standard conventions w.r.t. field design if possible. For example, no public or protected instance fields in classes, all public or protected static fields should be const or readonly, etc... Of course, some wiggle room here for performance and for structs, though I think you'll find in most runtimes the property getter/setters are inlined after JIT or AOT.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/field

**Comment by witlock** [comment]
I think this has been brought up before several times.
#15 #326 
etc.

**Comment by JeroMiya** [comment]
Well, to each his own - it's your library. IMO I haven't been convinced any naming convention is inherently better than another to such a degree that overrides the benefits of consistency to code readability. Having to press shift more often doesn't cut it for me, IMO. By not following the platform conventions you're guaranteeing that code written using your library will always have inconsistent conventions, which harms readability. If every library has its own conventions, which might be different from yours, then it's just going to be chaos.

Also, just for those reading, property getter/setters with no code in them (e.g. `public int Foo { get; set; }`) are ALWAYS inlined during JIT or AOT if you're running on a runtime newer than 2010 (2008 really, if you're on the desktop windows framework). There is no performance related justification for using public fields instead of properties in classes (structs don't follow this convention). If you want to verify this, build in release mode, run the application outside of VS *without* the debugger, then attach. Then see the disassembly. If you run the app with the debugger from the start, all JIT optimizations will be disabled.

The belief that properties are always a function call comes from older versions of Unity using an ancient version of Mono.
