### ISSUE TITLE
Tiled Custom Property Deserialization Issue

### ISSUE THREAD

**Issue by Yankas** [prime31/Nez#404]
There is a problem when processing .tmx with complex custom properties.

Normally, Tiled will export custom properties like this:

`<property name="foo" value="bar"/>`

However, if the custom property contains line breaks, Tiled will export the value as inner text like this:

```
<property name="foo">bar
more bar</property>
```

When the the deserializer tries to initialize the TmxProperty, the value attribute will be null, since it only checks for the attribute. 

I am currently working around the issue by trying to parse both and then checking if either of them is empty. 

```
[XmlAttribute("value")]
public string valueAttribute { get; set; }

[XmlText]
public string valueInner { get; set; }

[XmlIgnore]
public string value => string.IsNullOrEmpty(valueInner) ? valueAttribute : valueInner;
```
This works and is _mostly_ backwards compatible with the older method, but it looks a bit hack-y and there might be a cleaner solution.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
