### ISSUE TITLE
Tiled Slopes Buggy

### ISSUE THREAD

**Issue by johmarjac** [prime31/Nez#406]
Hi,

I have 128x128 tiles and some of them are slopes. As I find it really really cool that Nez has support for slopes I wanted to use them of course.

However they seem to be quite buggy to me.
For example I have a slope like that |\ (actually it is 45°) I ´ve put slopeTopLeft to 0, and slopTopRight to 128. Is that correct? It seems to collide just fine so I guess it is correct. The thing is when the next tile to the slope is a straight tile, then it bugs... Its quite hard to explain so here is a video:

https://puu.sh/B7VZz/2cc4dea642.mp4

Another thing is, you see, between those two slopes, there is no square tile, in the following video I put one there and it also collides with the square tile which makes me unable to move further up the slope.

https://puu.sh/B7W2G/63189e4bac.mp4

Is it maybe because I put wrong slope values? Or maybe my player collider? What could be wrong?

**Comment by nhorne** [comment]
slopeTopRight should be 127 since the coordinates start at 0.

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
