### ISSUE TITLE
Existing entities blinking/disappearing on adding new entity

### ISSUE THREAD

**Issue by fabianPas** [prime31/Nez#407]
I have the following scene I am using within my game. It's a simple Tiled Map with a single button 'UI'. I start the scene with some entities and have my update method spawn new entities on click. The spawned entities on initialization are placed on the tiled map properly but when added by mouse click, the existing and new entities just blink after each click. The debug borders around the entities are still visible but the sprites of the entities blink. Is this a bug?

```
public class GameScene : Scene
{
        public override void initialize()
        {
            // Set scene background color
            clearColor = Color.Black;

            Core.debugRenderEnabled = true;

            // Set camera zoom
            camera.setZoom(1);

            // Add the renderers
            addRenderer(new ScreenSpaceRenderer(100, UI.UI_RENDER_LAYER));
            addRenderer(new RenderLayerExcludeRenderer(0, UI.UI_RENDER_LAYER));

            var map = content.Load<TiledMap>("maps/Fardia");
            addEntity(new UI());
            addEntity(new Map(map));
            addEntity(new God());

            for (int i = 0; i < 100; i++)
            {
                var position = Nez.Random.range(new Vector2(10, 10), new Vector2(100, 100));

                addEntity(new Human()
                {
                    position = position
                });
            }
        }

        public override void update()
        {
            base.update();

            if (Input.leftMouseButtonPressed)
            {
                addEntity(new Human()
                {
                    position = camera.mouseToWorldPoint().round()
                });
            }
        }
    }
```

**Comment by SolarOmni** [comment]
I've had no problem with this, however I do see you're using camera.mouseToWorldPoint() which can cause issues if you're within the deadzone of your camera. However, that shouldn't cause your entities to blink, instead it would cause them to be placed in the wrong position. 

Whichever component on your Human entity that is responsible for drawing should probably be inspected to see if your issue is there.

**Comment by fabianPas** [comment]
I get the same results with a fixed position. I use the default Sprite component that comes with Nez to draw the sprite. I am very confused.

**Comment by SolarOmni** [comment]
Can you post your Human class?

**Comment by fabianPas** [comment]
My Human class is as simple as:

```
public class Human : Entity
    {
        public Human()
        {
        }

        public override void onAddedToScene()
        {
            var texture = scene.content.Load<Texture2D>("sprites/male_blue");
            addComponent(new Sprite(texture));
        }
    }
```

**Comment by SolarOmni** [comment]
Hmm..well it's not your Human class. 

I just wrote up a simple program with a tiledmap and also placing entities with just a simple sprite and Texture2D via mouse click and there is no blinking on my end.

**Comment by fabianPas** [comment]
Ugh, I'm so confused!

**Comment by fabianPas** [comment]
I removed all my entities and went back to using the DefaultRenderer and adding Humans the same way. The same kind of blinking happens when I add multiple Human entities around the same position overlapping eachother. Is this a problem with the way things are rendered? Or is this intended behaviour?

**Comment by fabianPas** [comment]
Setting the renderLayer to 0 on the Map and to 1 on the Human entities prevents blinking of the entities when placed on the map, but when the Human entities overlap they still blink.

**Comment by SolarOmni** [comment]
Try sorting your human entities and put them on different render layers (though I still have no idea why things are blinking.) I use a GlobalManager that gets all entities of a certain type and sorts them by Y position and using a counter I just change their renderlayer to that of the counter. So they're all on a different layer depending on their y position.

**Comment by fabianPas** [comment]
Do you have an example of that? And is that a common practice to work with? Also, where do you change their renderlayer to that of the counter? During the update or during initialization/onAdd?

**Comment by SolarOmni** [comment]
Common practice with Nez? I dunno. Common practice in game development in general? Yes. This was just something I quickly did and it worked like a charm, though I haven't used it in something big or anything. I just quickly did it with tags, but you can always get them and sort them by type or something instead.
`
namespace Evermore.GameCore.Tools
{
	class RenderManager : IUpdatableManager
	{
		public void update()
		{

			var characters = Core.scene.findEntitiesWithTag(GameCore.TagCharacter);
			characters.Sort(delegate (Entity x, Entity y)
			{
				var xY = x.transform.position.Y;
				var yY = y.transform.position.Y;
				return (xY.CompareTo(yY));
			});
			int renderCounter = 1000;
			foreach(Entity e in characters)
			{
				renderCounter--;
				e.getComponent<Character>().GetAnimation().renderLayer = renderCounter;
			}
		}
	}
}
`

**Comment by prime31** [comment]
Chiming in to say what you are seeing is most likely z-fighting. You have to move overlapping sprites to different z-indices (layer depth) else the beets just get jumbled up and the GPU won’t k ow how to render everything.

**Comment by fabianPas** [comment]
It was all me then.. @SolarOmni thanks for your great example!

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
