### ISSUE TITLE
Layout with scale in Nez.UI.Image

### ISSUE THREAD

**Issue by Samba4e** [prime31/Nez#408]
It is laid out without considering its scales:  
https://github.com/prime31/Nez/blob/master/Nez.Portable/UI/Widgets/Image.cs#L106  
  
For example, with someImage.setAlignment( Align.center ).setScale( 0.5f ), it is laid out to left top corner of the region area.
  
So, how about using scaled imageWidth and imageHeight to compute imageX and image Y?  
  
like this: from [line 118](https://github.com/prime31/Nez/blob/master/Nez.Portable/UI/Widgets/Image.cs#L118)  
```
if( ( _align & AlignInternal.left ) != 0 )
				imageX = 0;
			else if( ( _align & AlignInternal.right ) != 0 )
				imageX = (int)( width - imageWidth * scaleX );
			else
				imageX = (int)( width / 2 - imageWidth * scaleX / 2 );

			if( ( _align & AlignInternal.top ) != 0 )
				imageY = (int)( height - imageHeight * scaleY );
			else if( ( _align & AlignInternal.bottom ) != 0 )
				imageY = 0;
			else
				imageY = (int)( height / 2 - imageHeight * scaleY / 2 );
```

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
