### ISSUE TITLE
[Mover.cs] neighbors collection gets modified while looping

### ISSUE THREAD

**Issue by witlock** [prime31/Nez#41]
_Additional information: Collection was modified; enumeration operation may not execute._

For some reason every once in a while this happens to me while I move around with the character.
My movement component called Mover.move at the end of it's IUpdatable.update loop.
Advice?

Edit: I assume it has something to do with another thread doing
**unregisterAllCollidersWithPhysicsSystem**
**player.transform.position = new Vector2(x,y);**
**registerAllCollidersWithPhysicsSystem**

..to correct the players location if it differs from the server.
What would be the best way to achieve this without making the "physics" go crazy?

Just set the position without unregistering the colliders?

**Comment by prime31** [comment]
Nez is not thread safe. There are no locks/mutexes at all anywhere in the framework so if you are using multiple threads you will need so synchronize back on the main thread to avoid issues.
