### ISSUE TITLE
Collider.collidesWithAny() not detecting a collision between two clearly touching colliders

### ISSUE THREAD

**Issue by lizenas** [prime31/Nez#412]
I have two entities with BoxColliders that have working collision when using Mover.move() to collide them, but when I call Collider.collidesWithAny() on either of them it will never return a collision. Any ideas as to what could be going wrong? I can provide more specific code if necessary.

**Comment by prime31** [comment]
Something odd must be happening here. The `Mover.move` method is doing exactly the same thing as `Collider.collidesWithAny`:

`Physics.boxcastBroadphaseExcludingSelf` then `collider.collidesWith`

I'd suggest tracing through the collision checks for both and see if maybe you have some layers set differently or something else going on in there.

**Comment by lizenas** [comment]
I commented out all physicsLayer and collidesWithLayer changes and still nothing. I'm literally just running `if (hitbox.collidesWithAny(out CollisionResult result)) { Debug.log("collision!"); }` in update()

**Comment by prime31** [comment]
Do you have a Mover in the same Entity? That would prevent any collisions from occurring if you did.

**Comment by lizenas** [comment]
I do. Why does that happen? Is there a way to work around it?

**Comment by prime31** [comment]
Well, the Mover will make sure overlaps don’t ever happen. That’s what it’s role is. If you need the data for a collision use the CollisionResult you get when you call `move`.

**Comment by lizenas** [comment]
Ah, that makes sense. Thanks for the help! Your ~Kit repos were very useful when I was playing around in Unity btw.

**Comment by prime31** [comment]
If you know about the *Kits you’ll probably see some familiar stuff in Nez! ZestKit, UtilityKit, StateKit and a few others were ported to Nez.

**Comment by lizenas** [comment]
Excellent! I got my isGrounded check working so I'll close this issue :)
