### ISSUE TITLE
OSX: Nez content processors/importers don't show up in the Monogame Pipeline app

### ISSUE THREAD

**Issue by hotdiggitydoddo** [prime31/Nez#415]
This works fine with an older version of Monogame and pipeline app.  It also works fine on Windows with the 3.7.  It's broken on Mac, though.  I've followed all the instructions and loaded up the appropriate DLLs but the app still won't recognize any of Nez's custom importers/processors.

**Comment by exploder1531** [comment]
I've the same issue with Windows 10. I've taken a look over Monogame website and I noticed that some people had issues too. ([source](http://community.monogame.net/t/solved-tmx-tiledmap-file-has-no-importer-and-processor/11018/10)

Try using most recent development build of Monogame and check if it's working.

I'll try checking it myself soon (maybe tomorrow) and get back here with my result.

**Comment by exploder1531** [comment]
I've just tried installing development build of Monogame, all content processors/importers are there. It seems to be an issue with 3.7 version (at least for me).

**Comment by 0x25b3** [comment]
Had the same issue on windows, can confirm the current 3.8 development build solved it

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
