### ISSUE TITLE
Change GamePadDeadZone used in GamePadData

### ISSUE THREAD

**Issue by osum4est** [prime31/Nez#416]
Hello! Is there any way to change the GamePadDeadZone used in GamePadData? I would like to use the circular mode. I looked through the source and didn't see any way to do so but I could've missed something. If there is no way to do this I am happy to submit a pull request with the addition!

**Comment by prime31** [comment]
Whenever you get the values of the left or right stick, you can optionally pass in a deadzone value. See the getLeftStick method for the details.

**Comment by osum4est** [comment]
I saw that, but that only lets you pass in a double, not a value from the GamePadDeadZone enum. By default GamePadDeadZone.IndependantAxes is used, which makes it so that very small angles are set to the closes axis, making it easier to move straight up/down/left/right. I need the Circular mode, though, as that one allows any angle. In default MonoGame, this is passed into GamePad.GetState

**Comment by prime31** [comment]
Aha. I see what you are looking for now.
