### ISSUE TITLE
Debug console doesn't open following the simple tutorial

### ISSUE THREAD

**Issue by ontehfritz** [prime31/Nez#418]
Following the tutorial of creating a basic scene and getting that to work is straight forward. In the documentation of nez it states if you key ~ it will open a debug console, this doesn't seem to work (i am compiling and running in debug), is there something I need to add to the basic scene tutorial to get this to work?

**Comment by ontehfritz** [comment]
I am using the nuget package? Is this because it was built in release? That being said,  you can never get the debug console with the nuget package?

**Comment by prime31** [comment]
That is correct. NuGet includes precompiled DLLs and they are from a release build. I haven’t come up with a good solution to work around that limitation yet so for now using source for dev is easiest for sure.

**Comment by ontehfritz** [comment]
This is probably a good thing to put in the documentation, killed a lot of time on it. Thanks keep up the great work!
