### ISSUE TITLE
Can't click buttons but mouse actions are properly registering.

### ISSUE THREAD

**Issue by alexwoopl** [prime31/Nez#427]
So, I dont know if I am missing something but any way I work it or look into it I am unable to click on any buttons on the screens.

I made a dialog box with a button essentially as shown in the sample projects but when ever I try to click the button nothing happens at all.
I tried firing the onClick programmatically and it works fine, I also tested that the mouse inputs were being registered okay and they were.
I am at a total loss for any reason why this wouldnt work.

My class code is below:
`
        public class Interactable : UICanvas
    {

        public void interact()
        {
            var skin = Skin.createDefaultSkin();

            var table = stage.addElement(new Table());
            table.center();
            table.setFillParent(true);

            table.add(talk(this.entity.name, "Stay a while and glisten", "Bye!"));
            
        }

        public Dialog talk(string title, string messageText, string closeButtonText)
        {
            var skin = Skin.createDefaultSkin();

            var style = new WindowStyle
            {
                background = new PrimitiveDrawable(new Color(50, 50, 50)),
                //Dims the background
                stageBackground = new PrimitiveDrawable(new Color(0, 0, 0, 150))
            };

            var dialog = new Dialog(title, style);
            dialog.getTitleLabel().getStyle().background = new PrimitiveDrawable(new Color(55, 100, 100));
            dialog.pad(20, 5, 5, 5);
            dialog.addText(messageText);
            var exitButton = new TextButton(closeButtonText, skin);
            exitButton.onClicked += butt => dialog.hide();
            dialog.add(exitButton);
            

            return dialog;
        }
        
        
    }
}
`

The interact() is called when running up to another entity and pressing "E".
Which causes everything to render properly but I can't click on the button.

**Comment by alexwoopl** [comment]
Update: It seems that the issue is that where the button is being rendered and where the actual click box is are not the same.
I have Zoomed in the camera by 2 and the camera also follows my little character around. The dialog will then appear at the X,Y in relation to the current camera view but the actual click box appears at the X,Y in terms of the TiledMap (which is not always on screen)

**Comment by exploder1531** [comment]
You should generally use ScreenSpaceRenderer for any UI elements. It's using a separate camera that can't be moved around, so everything it renders will always be in the same place no matter the zoom, rotation, movement, or whatever you do with the camera.

You'll have to set it to render only layers that you use for UI elements, while making sure that your other renderers don't render them.

**Comment by alexwoopl** [comment]
@exploder1531 Thank you so much! This was the issue exactly :) I don't know if it was an issue of clarity that made it hard to find or not but ill just put it down to my own idiocy haha. Thanks again Ill close this 👍
