### ISSUE TITLE
Individual Tile/Row depth?

### ISSUE THREAD

**Issue by BunnyJumper** [prime31/Nez#432]
I'm curious to know if there's a way to get tiles/a row from tiled and possibly set its depth? ik u can get a tile if it has a collision on it but even then u cant set its depth, a few pictures to show what I'm going for, 
![example4](https://user-images.githubusercontent.com/45908469/50049819-57e92d00-00c4-11e9-879a-5add4c84f77f.png) When the player is "infront" of the fence doesnt really matter how tall he is it will still render correctly and then when he goes behind
![example3](https://user-images.githubusercontent.com/45908469/50049821-6df6ed80-00c4-11e9-8d32-12c412fa497f.png) ![example5](https://user-images.githubusercontent.com/45908469/50049923-6b48c800-00c5-11e9-9aa0-da78fdb7ab9f.png) the fence is infront, with just setting different layers it works if the player is smaller then the collision but if hes bigger u get this 
![example2](https://user-images.githubusercontent.com/45908469/50049835-9979d800-00c4-11e9-967f-97909c51f9d2.png) any easy way to do this inside nez? or is it achieved in some whole different way? like with rendertargets and what not? (Idk anything when it comes rendertargets and all that tbh) (sorry for the noob/prob annoying question)

**Comment by prime31** [comment]
Have a look at the Nez.Samples. There is an example of exactly this along with a shadow stencil shader for when behind tiled.

**Comment by BunnyJumper** [comment]
the same thing happens tho 
![example6](https://user-images.githubusercontent.com/45908469/50054177-e043ee00-0115-11e9-839d-4b4286d1f7a4.png) if your character or sprite is  higher then the collision/the infront layer you will just clip through since the depth of the player and that layer changes and theres not really a way I can personally think of without having each row have a different depth based on y and the players depth updating based on y(higher y = lower depth), (or something like that I could be wrong tho) here's maybe another example to get the idea across better maybe, 
![example7](https://user-images.githubusercontent.com/45908469/50054389-a4118d00-0117-11e9-83cf-0a60dd72e4ea.png) here you can see the player sprite is higher then what would be the front layer since hes over the collision but it still renders correctly and when hes under that layer it  renders correctly 
![example8](https://user-images.githubusercontent.com/45908469/50054402-d3c09500-0117-11e9-8c8c-54bed84b6406.png)
