### ISSUE TITLE
No MonoGame reference when adding Nez to project

### ISSUE THREAD

**Issue by mathshane** [prime31/Nez#433]
Nez, out of the box, won't work following the installation instructions.

# Versions used
- Cloned latest Nez repo as of 18.12.18
- MonoGame 3.7.1.189

# Steps to reproduce
1. Create new project "MonoGame Cross Platform Desktop Project in Virtual Studio 2017.
2. Go to Solution -> Add -> Existing Project -> Nez -> Nez.Portable -> Nez.csproj (as per the Nez installation instructions)
3. In main MonoGame project: References -> Add Reference -> Projects -> Nez
4. Add 'using Nez;' to `Game1.cs` in main project.
5. Have Game1 as subclass of `Nez.Core`.

This is where I get the error:
> The type or namespace name 'Game' could not be found (are you missing a using directive or an assembly reference?)

# Comparison of 'MonoGame.Framework' properties under 'References'.
Sure enough, the `MonoGame.Framework` reference appears to differ between Nez and the one when creating a MonoGame Cross Platform Desktop project.

The MonoGame reference in Nez doesn't appear to have any actual path, as seen here:
![image](https://user-images.githubusercontent.com/10103131/50170113-29827200-02bd-11e9-8239-c6637f91411a.png)

And here is a working reference to MonoGame when creating a pure MonoGame project:
![image](https://user-images.githubusercontent.com/10103131/50170171-46b74080-02bd-11e9-9c96-8476970224eb.png)

# Fix
Sure enough, removing the MonoGame reference in the Nez project and manually adding the correct path (in the image directly above) seems to remove these errors and let me run a blank MonoGame + Nez window.

**Comment by pacoo2454** [comment]
I was having the same problem for a while too. Now, if the project doesn't build I will open the Nez.sln and manually restore NuGet packages for Nez Portable and Nez Pipeline. That seems to have fixed the build problems I was getting with new projects.

**Comment by jd-bender** [comment]
I'm having this issue as well. I'm also not able to build Nez like is done in this youtube instructional video https://www.youtube.com/watch?v=ZfVMCbOniV0&t=196s.

**Comment by jd-bender** [comment]
mathshane's solution worked for me. The problem here is definitely due to a bugged monogame reference in the nez project. @prime31

**Comment by jd-bender** [comment]
Also noticed in Nez.PipelineImporter that the references to Ionic.ZLib, Newtonsoft.Json, and MonoGame.Framework.Content.Pipeline all also have empty paths.
