### ISSUE TITLE
Calling "SpriteT.play()" from within an "onAnimationCompletedEvent" callback does not work as expected.

### ISSUE THREAD

**Issue by tullrich** [prime31/Nez#434]
Due to the following code flow in SpriteT::update():

```
// if we arent looping and elapsedTime is 0 we are done. Handle it appropriately
if( !_currentAnimation.loop && elapsedTime == 0 )
{
   // the animation is done so fire our event
   if( onAnimationCompletedEvent != null )
	onAnimationCompletedEvent( _currentAnimationKey );
   isPlaying = false;
   switch( _currentAnimation.completionBehavior )
   {
      case AnimationCompletionBehavior.RemainOnFinalFrame:
	  return;
      case AnimationCompletionBehavior.RevertToFirstFrame:
         setSubtexture( _currentAnimation.frames[0] );
	 return;
      case AnimationCompletionBehavior.HideSprite:
	 _subtexture = null;
	 _currentAnimation = null;
	 return;
   }
}
```
I was using onAnimationCompletedEvent() to determine the next animation to play in a sequence. However calling play() synchronously from the cb does not work as I expected. The next animation is instead frozen on the first frame due to isPlaying being assigned false.

One suggested fix would be to fire the callback as the final piece of logic in update(). I could also work around this issue by calling play() via some asynchronous means (waiting for the next update, etc.).

Is this behavior expected?  What is the suggested way to do animation sequences?

**Comment by prime31** [comment]
SpriteT no longer exists in Nez
