### ISSUE TITLE
[question]  Rendering Spine animations

### ISSUE THREAD

**Issue by Owlzy** [prime31/Nez#440]
I've been looking into porting a game to MonoGame, and Nez seemed ideal in that it offers a number of features I'd implement myself if using pure MonoGame.  However, it doesn't seem that straight forward to plug in custom rendering.  I started by extending the Renderer class, but haven't got very far because the render function won't take my extended Scene class. 

I've been trying to create a custom scene base class, with a list of Spine skeletons which I can draw (using the monogame / xna spine runtime).  Is this fairly straightforward or would I be better sticking with MonoGame and adding in the features I need? 

Or otherwise am I missing something / does Nez support spine out of the box?

**Comment by prime31** [comment]
I have no idea how Spine does it’s rendering. What I personally would do is just subclass of RenderableComponent. That gives you access to the render method. You can render whatever you want, however you want in whatever order you want with it.
