### ISSUE TITLE
Loading Fonts from Skins

### ISSUE THREAD

**Issue by mikeatuconn** [prime31/Nez#441]
I am loading a skin as follows:

`"TextButtonStyle": {
            "default": {
                "font": "font-button-export",
                "fontColor": "black",
                "up": "button",
                "down": "button-pressed",
                "over": "button-highlighted"
            }
        },`

The button images are loading correctly, font color seems to load, but text won't display and the font for the UI style appears to be null. I can manually load the font and print it to the screen, so it doesn't seem to be an issue with the font itself.  

I've looked through the pipeline processor and UI widgets and don't see any issues.

Does anyone have a skin file with fonts that they know works so I can diagnose where the issue is?

Thanks in advance

**Comment by prime31** [comment]
Fonts are handled [here](https://github.com/prime31/Nez/blob/master/Nez.Portable/UI/Skin.cs#L263). Note that whatever identifier you set is just passed directly over to `contentManager.Load<BitmapFont>( identifier )`.
