### ISSUE TITLE
Interval or Loop coroutine best practices

### ISSUE THREAD

**Issue by holyxiaoxin** [prime31/Nez#443]
I would like to run an interval that sends my player's position to the game server. Unity has InvokeRepeating(), but I guess we could achieve the same by:
```cs
// Core.startCoroutine(IntervalSendPosition());

IEnumerator IntervalSendPosition()
{
    while (true)
    {
        yield return Coroutine.waitForSeconds(0.2f);
        Console.WriteLine(entity.position);
    }
}
```

Is this considered a good practice?

**Comment by prime31** [comment]
Coroutines in Nez are even more efficient than Unity’s implementation so you can use them as much as you’d like. I would personally consider using Core.schedule which is specifically designed for dealing with timers and repeated calls.

**Comment by holyxiaoxin** [comment]
```cs
Core.schedule(0.2f, true, this, IntervalSendPosition); // true for repeating
private void IntervalSendPosition(ITimer t)
{
    Console.WriteLine(entity.position);
}
```
