### ISSUE TITLE
TexturePacker piplineimporter

### ISSUE THREAD

**Issue by thomasbrunstrom** [prime31/Nez#444]
I get a "Object reference not set to an object" error when I'm trying to add a json file to the monogame pipeline tool.

The contents of the file is the following

`{"frames": [

{
	"filename": "Character_Falling_0.png",
	"frame": {"x":0,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Falling_1.png",
	"frame": {"x":256,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Falling_2.png",
	"frame": {"x":512,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Falling_3.png",
	"frame": {"x":768,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Falling_4.png",
	"frame": {"x":1024,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Falling_5.png",
	"frame": {"x":1280,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Falling_6.png",
	"frame": {"x":1536,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_00.png",
	"frame": {"x":1792,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_01.png",
	"frame": {"x":2048,"y":0,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_02.png",
	"frame": {"x":0,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_03.png",
	"frame": {"x":256,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_04.png",
	"frame": {"x":512,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_05.png",
	"frame": {"x":768,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_06.png",
	"frame": {"x":1024,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_07.png",
	"frame": {"x":1280,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_08.png",
	"frame": {"x":1536,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_09.png",
	"frame": {"x":1792,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_10.png",
	"frame": {"x":2048,"y":256,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_11.png",
	"frame": {"x":0,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Idle_12.png",
	"frame": {"x":256,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Jump_0.png",
	"frame": {"x":512,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Jump_1.png",
	"frame": {"x":768,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Jump_2.png",
	"frame": {"x":1024,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Jump_3.png",
	"frame": {"x":1280,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Jump_4.png",
	"frame": {"x":1536,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Jump_5.png",
	"frame": {"x":1792,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Jump_6.png",
	"frame": {"x":2048,"y":512,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_00.png",
	"frame": {"x":0,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_01.png",
	"frame": {"x":256,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_02.png",
	"frame": {"x":512,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_03.png",
	"frame": {"x":768,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_04.png",
	"frame": {"x":1024,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_05.png",
	"frame": {"x":1280,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_06.png",
	"frame": {"x":1536,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_07.png",
	"frame": {"x":1792,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_08.png",
	"frame": {"x":2048,"y":768,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_09.png",
	"frame": {"x":0,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_10.png",
	"frame": {"x":256,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_11.png",
	"frame": {"x":512,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_12.png",
	"frame": {"x":768,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_13.png",
	"frame": {"x":1024,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_SmallAttack_14.png",
	"frame": {"x":1280,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_00.png",
	"frame": {"x":1536,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_01.png",
	"frame": {"x":1792,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_02.png",
	"frame": {"x":2048,"y":1024,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_03.png",
	"frame": {"x":0,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_04.png",
	"frame": {"x":256,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_05.png",
	"frame": {"x":512,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_06.png",
	"frame": {"x":768,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_07.png",
	"frame": {"x":1024,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_08.png",
	"frame": {"x":1280,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_09.png",
	"frame": {"x":1536,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_10.png",
	"frame": {"x":1792,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_11.png",
	"frame": {"x":2048,"y":1280,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_12.png",
	"frame": {"x":0,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_13.png",
	"frame": {"x":256,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_14.png",
	"frame": {"x":512,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_15.png",
	"frame": {"x":768,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_16.png",
	"frame": {"x":1024,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_17.png",
	"frame": {"x":1280,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_18.png",
	"frame": {"x":1536,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_19.png",
	"frame": {"x":1792,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_20.png",
	"frame": {"x":2048,"y":1536,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_21.png",
	"frame": {"x":0,"y":1792,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_22.png",
	"frame": {"x":256,"y":1792,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_23.png",
	"frame": {"x":512,"y":1792,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_24.png",
	"frame": {"x":768,"y":1792,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
},
{
	"filename": "Character_Walkin_25.png",
	"frame": {"x":1024,"y":1792,"w":256,"h":256},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":256,"h":256},
	"sourceSize": {"w":256,"h":256}
}],
"meta": {
	"app": "https://www.codeandweb.com/texturepacker",
	"version": "1.0",
	"image": "heroatlas.png",
	"format": "RGBA8888",
	"size": {"w":2304,"h":2304},
	"scale": "1",
	"smartupdate": "$TexturePacker:SmartUpdate:54eda4342ef7f65dbbb6e86d111410dc:75c48b118f11cc5dea615cbc8b86ed0c:c59168d61d79136e17e613e607d1c83a$"
}
}
`

And the heroatlas.png file is in the same directory as the hero.json file. 

Any ideas?

**Comment by prime31** [comment]
No idea. I would suggest running the Pipeline tool attached to a debugger so you can get some actual information about the error.
