### ISSUE TITLE
BoxCollider collides with PolygonColliders bounding box 

### ISSUE THREAD

**Issue by thomasbrunstrom** [prime31/Nez#445]
Ok, so I've tried to implement a polygon item in my game and added a PolygonCollider to that item but it seems like my "player's" BoxCollider collides with the bounding box of the PolygonCollider and not the Polygon it self. 

Maybe I'm doing something wrong but it seems like it should collide with the shape of the polygon and not the bounding box. 

I'm using the [Mover](https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Physics/Mover.cs) component to check for collisions. 

![nez-polygoncollider](https://user-images.githubusercontent.com/3089359/52585750-f3351f00-2e35-11e9-9ee3-80b80ef14f77.png)

Any ideas what I might be doing wrong?

**Comment by prime31** [comment]
The Mover just calls [Collider.collidesWith](https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Physics/Colliders/Collider.cs#L273) for anything that has an overlapping bounds. Trying hitting that in the debugger.

**Comment by thomasbrunstrom** [comment]
Well, thats the problem. It collides with the bounding box and not the polygon. But I guess I'll try to debug it some more if You don't have anything obvious. 

Thanks for a awesome framework btw!

**Comment by prime31** [comment]
The debugger should have the answer. Chances are there is a stray Box shape or something like that on your Entity.

**Comment by thomasbrunstrom** [comment]
As you can see in the image i provided there is thin white line, which i suppose is the bounding box for the PolygonCollider, the polygon is the one with red outline around the green box. The code for adding the polygon is like this: 

`
            var tiledEntity = createEntity("tiled-map-entity");
            tiledMap = content.Load<TiledMap>(Content.Maps.Mock.start);
            var tiledMapComponent = tiledEntity.addComponent(new TiledMapComponent(tiledMap));
            tiledMapComponent.setLayersToRender(new string[] { "base" });
            tiledMapComponent.renderLayer = RenderLayers.InFront;

            var coll = createEntity("Colliders");
            tiledMap.getObjectGroup("collisions").objectsWithType("collider").ForEach(e =>
            {
                var c = coll.addComponent<PolygonCollider>(new PolygonCollider(e.polyPoints));
            });
`

And I have not added any colliders for the TiledMap.

The red empty box above is the player.

**Comment by prime31** [comment]
White lines are not colliders, that is just a normal rendering bounds. Hit the code in the debugger and it will show you exactly what is happening.
