### ISSUE TITLE
Multiple missing members in Nez.ImGui

### ISSUE THREAD

**Issue by leecannon** [prime31/Nez#448]
I have only just come across Nez and after cloning the repo I saw the Nez.ImGui project, as I was planning on adding my own ImGui renderer to my game this would save alot of effort (yours will probably be higher quality as well). 

I decided to give it ago however multiple classes/inferfaces do not exist: 
- IComponentInspector
- TransformInspector
- PostProcessorInspector

All of them seem to be in the Nez.ImGuiTools.ComponentInspectors namespace which is not present at all as of commit:  9dcefad2e1dad4a7f27c4b07aa163c60aa63c612

I know the ImGui project is in its infancy, looking at the commits it was created yesterday, hot off the presses :smile:.
I am only raising this issue as it seems like the missing code is probably implemented on your local repo and was not git added.

**Comment by prime31** [comment]
Try fetching now. There were a bunch of wip files that didnt get pushed. They are still very, very wip but they are up there now.

**Comment by leecannon** [comment]
Thanks
