### ISSUE TITLE
Framerate-dependent movement?

### ISSUE THREAD

**Issue by meowgoocat** [prime31/Nez#45]
Entity using ArcadeRigidbody for movement with no other entities on scene.

Have two PC monitors.

On 144 hz monitor, I get 144 fps and it takes slightly less than 4 seconds to move from one end of window to the other.

On 60 hz monitor, I get about 48 fps, and it takes nearly 7 seconds to move from one end of the window to the other.

There is clearly not framerate independency here, even though ArcadeRigidbody appears to rely on deltatime.

**Comment by prime31** [comment]
Everything (all accelerations and velocities) in the ArcadeRigidbody are indeed multiplied by deltaTime before applying them. The distance traveled would certainly have an effect on the situation if one of your monitors had a different resolution than the other or if the windows had different sizes.

**Comment by meowgoocat** [comment]
Okay, I believe I've figured it out.

I am using very small sprites and a very small camera, so on my faster monitor, the product of velocity and delta time is so small that it is less than a unit.  The engine rounds this up to 1 unit.  Increasing movement speed caused both monitors to have similar speeds, though it seems to always round to the nearest unit.

I'm sure you'll be able to let me know whether this a framework limitation or a bug.  Do I have to resize my textures and increase movement speed across the board or is there an easy way to change unit size?

**Comment by prime31** [comment]
Aha! By default all values are indeed rounded. Just set Transform.shouldRoundPosition To false and they will no longer be rounded.

**Comment by meowgoocat** [comment]
Yep that'll do it.
