### ISSUE TITLE
ImGuiManager options

### ISSUE THREAD

**Issue by leecannon** [prime31/Nez#450]
Can the below properties have a public API for configuring both on creation of the ImGuiManager object as well as to make it possible to hook them up to something like a keypress.

https://github.com/prime31/Nez/blob/bb288731e15f7147dd98db375e4b06562c3228ae/Nez.ImGui/Core/ImGuiManager.cs#L13-L17

The same with the built in ImGui main menu.

**Comment by prime31** [comment]
Yup. That sounds good to me. I’ll whop that up later today. I’d also like to get font merging in there but ImGui.NET doesn’t expose it yet so I need to find some time to dig in to their code and see if I can add it.

**Comment by prime31** [comment]
Instead of adding them to config i just made them public. That way you can control them anywhere, anytime.
