### ISSUE TITLE
Altering Tiled tiles based on TiledMapMover.CollisionState

### ISSUE THREAD

**Issue by farmerpat** [prime31/Nez#452]
I am not sure if what I'm trying to achieve is beyond the scope of Tiled support, but here goes:

When my component collides with a tile, I would like to alter that tile's texture (e.g, change its color). When I recognize a collision in IUpdatable.update()  (e.g. if (_collisionState.below)), is it possible to grab references to all the tiles my component is colliding with and monkey with them?

Thanks!

**Comment by prime31** [comment]
The TiledMap class draws all tiles with the same vertex colors (see [here](https://github.com/prime31/Nez/blob/master/Nez.Portable/PipelineRuntime/Tiled/TiledTileLayer.cs)). You can, however just grab the collided tiles and change the texture portion they are pointing at by just changing the tile `id`.
