### ISSUE TITLE
PolyLight not correctly colliding with TiledMap collision layer

### ISSUE THREAD

**Issue by stants225** [prime31/Nez#454]
As in the title, after creating a tiled map and enitity and assigning the collision layer, it works for physics collisions (e.g with player) however the poly light seems to just miss out several of the boxcolliders in the tiled map, but not all of them.
          

            var tiledMap = content.Load<TiledMap>("NezMap");
            var tiledMapEntity = createEntity("map");
            var tiledComponent = new TiledMapComponent(tiledMap, "Main");

            var pointLight = new PolyLight(700, Color.Red);
            pointLight.renderLayer = LIGHT_RENDER_LAYER;
            pointLight.collidesWithLayers = 1;
            pointLight.power = 0.5f;
            var light = createEntity("light");
            light.position = new Vector2(700f, 300f);
            light.addComponent(pointLight);

![image](https://user-images.githubusercontent.com/23246639/53922621-00c47a00-406d-11e9-9f38-0b3913efdc98.png)

However as you can see the polylight just doesn't "see" most of the colliders from the tiled map and I have no idea why it sees a couple but not all. The ones it "sees" also change as the player moves into different regions of the spacial hash, leading me to believe it has something to do with that.

Thanks in advance

**Comment by prime31** [comment]
The PolyLight wasnt designed to work with TiledMaps. You could get it working with a bit of manual coding by updating the data passed to the Visibility class. The data it gets in there is how it creates it's Mesh.
