### ISSUE TITLE
FSDebugView does not scale well with zoomed in cameras

### ISSUE THREAD

**Issue by williamahartman** [prime31/Nez#455]
I'm using Farseer physics with a pretty zoomed in camera. I'm seeing some issues with how the debug visualizations draw that makes them pretty tough to interpret. It would be much nicer if these drew with a consistent scale irrespective of the camera's zoom.

For example:

![image](https://user-images.githubusercontent.com/7718837/54247050-cf84f780-450d-11e9-8366-01dc81988b9d.png)

Taking a quick look at the code, it looks like some of the drawing methods (`drawCircle()`, `drawPolygon()`) take `FSConvert` into account, but a few (`drawPoint()`, `drawSegment()`, `drawString()`) do not.

`DebugViewFlags.Shape` works correctly. I'm pretty sure `DebugViewFlags.AABB` is correct but I'm a little confused about what that one is doing, so I'm not totally sure. I don't have any Controllers in my scene right now, so I didn't try that one. It looks like it only uses `drawAABB()` though, which uses `FSConvert`, so I think that should be fine too. 

FSDebugView visualizations with scaling issues:
- `DebugViewFlags.CenterOfMass`
- `DebugViewFlags.ContactNormals`
- `DebugViewFlags.ContactPoints`
- `DebugViewFlags.DebugPanel`
- `DebugViewFlags.Joint`
- `DebugViewFlags.PolygonPoints`
- The graph in `DebugViewFlags.PerformanceGraph` looks right, but the text is somewhere off screen

**Comment by prime31** [comment]
Feel free to send a PR. This is a pretty non-standard setup (highly zoomed cam) and the debug drawer is a very simple bit of code to just get some data on screen so it isnt designed to handle every scenario.
