### ISSUE TITLE
TiledSprite 'modified' size does not adjust culling behaviour of rendering

### ISSUE THREAD

**Issue by BasBloem** [prime31/Nez#457]
I'm having issues with TiledSprite's culling behaviour
As it looks to me; it ignores the 'rendering' size in the culling behaviour, and only uses the size of the source texture, instead of the total width that I want the TiledSprite to be rendered.
I hope I'm explaining it well enough to understand along with the video.

https://youtu.be/63b8GIiWXOA

**Comment by prime31** [comment]
I believe this was fixed a while back. If not, feel free to reopen.
