### ISSUE TITLE
TrailRibbon problems when attached to pooled entity

### ISSUE THREAD

**Issue by ismyhc** [prime31/Nez#46]
Ive been having an issue using the TrailRibbon component when its attached to a pooled entity. When obtaining an entity from the pool that had been previously used you would see the trail quickly move from its last position that was used.

I fixed the issue be overriding onEnabled() in the TrailRibbon component like below.

I was going to submit a pull request, but decided I'd ask to see if you have a better solution?

**TrailRibbon.cs**
```
public override void onEnabled()
{
	base.onEnabled();

	_segments.Clear();
	initializeVertices();
}
```

So now in my **PlayerBulletEntity.cs**
```
public class PlayerBulletEntity : Entity, IPoolable
{

	TrailRibbon _trailRibbon;

	public PlayerBulletEntity() : base()
	{
			
		addComponent(new PlayerBulletComponent());

		_trailRibbon = addComponent(new TrailRibbon(10));
		_trailRibbon.setRenderLayer(4);
		_trailRibbon.ribbonRadius = 8;
		_trailRibbon.startColor = Color.AliceBlue;
		_trailRibbon.endColor = Color.Yellow;

		reset();

	}

	public void reset()
	{
		setEnabled(false);
	}

	public void start(Vector2 pos)
	{

		transform.setPosition(pos);

		_trailRibbon.transform.position = pos;

		setEnabled(true);

	}

}
```

**Comment by prime31** [comment]
I can't think of any reason why someone would want to disable/enable it and not have the trail cleared out. That solution should work fine until someone comes along wanting to do that ;)
