### ISSUE TITLE
The documentation link on the readme cannot be accessed

### ISSUE THREAD

**Issue by CountessAnise** [prime31/Nez#460]
The documentation link on the [README.md](https://github.com/prime31/Nez/blob/master/README.md) cannot be accessed.

The link is: [http://prime31.github.io/Nez/documentation/setup/installation](http://prime31.github.io/Nez/documentation/setup/installation)

That returns a 301 (Moved Permanently) with a location set to: [http://blog.prime31.com/Nez/documentation/setup/installation](http://blog.prime31.com/Nez/documentation/setup/installation)

The host `blog.prime31.com` does not resolve. I've tried multiple DNS servers, all failed the nslookup.

I've tried to manually add it to my hosts file with `prime31.com`'s resolved IP (`50.87.177.79` at the time of writing this) but that gives a 404 (Not Found).

So I assume it's not just a record issue, the content itself is missing.

Not sure if it's intended or not but I thought you might want to know. You might want to remove that link from the readme if it's intended.

Wishing you an awesome upcoming weekend! o7

**Comment by prime31** [comment]
All fixed!
