### ISSUE TITLE
[Help] Implementing GeonbitUI With RenderTarget

### ISSUE THREAD

**Issue by Deecellar** [prime31/Nez#462]
I'm using GeonbitUI and Nez for a college project and I did get to make GeonbitUI work by creating a renderer for it (It just implements in the render method the ``GeonbitUI.Userinterface.Active.Draw`` with a new spritebatch for the renderer)

Now I want to use the UseRendererTarget to use some features from it, but, in order to do that I have to implement this logic:
```cs
protected override void Draw(GameTime gameTime)
{
    // draw ui
    UserInterface.Active.Draw(spriteBatch);

    // clear buffer
    GraphicsDevice.Clear(Color.CornflowerBlue);

    // do your game renderings...

    // use `UserInterface.Active.RenderTarget` here.
    // in this example we call DrawMainRenderTarget(), which will draw the UserInterface.Active.RenderTarget on the currently set target (or backbuffer if non is set)
    UserInterface.Active.DrawMainRenderTarget(spriteBatch);

    // call base draw function
    base.Draw(gameTime);
}
 ```

I implemented the GeonbitUIRenderer like this
```cs
    class RendererGeonbitUI : Renderer
    {
        private SpriteBatch sprite = new SpriteBatch(Graphics.instance.batcher.graphicsDevice);

        public RendererGeonbitUI(int renderOrder = int.MaxValue, Camera camera = null) : base(renderOrder, camera)
        {
            UserInterface.Active.UseRenderTarget = true;
        }
        public override void render(Scene scene)
        {
            
            UserInterface.Active.Draw(sprite);


        }
    }
```

Thank you

**Comment by prime31** [comment]
You have to manage your own render target if you are using a SpriteBatch. Nez Renderers use a Batcher and manage the render target automatically (https://github.com/prime31/Nez/blob/master/Nez.Portable/Graphics/Renderers/Renderer.cs#L107). You need to override this behavior and make and manage your own render target.
