### ISSUE TITLE
(Windows) Nez / FNA / ImGUI rendering issues when run in Debug mode

### ISSUE THREAD

**Issue by hotdiggitydoddo** [prime31/Nez#463]
When either using the Nez/FNA project template or createing a project form scratch, Nez/ImGui/FNA fails to properly render elements in the most basic scene setup when the application is launched in **Debug config** and on **Windows ONLY**:  (everything compiled for .net 4.7.1, on 2 different machines)
![image](https://user-images.githubusercontent.com/2938036/55923156-13c0f180-5bb9-11e9-8213-fd70b8f61159.png)

Notice everything works fine in Release mode:

![image](https://user-images.githubusercontent.com/2938036/55923195-44089000-5bb9-11e9-99dc-977e37aac105.png)

I have tried to debug into the ImGui manager and implementation file and could not immediately spot anything unusual.

**Comment by hotdiggitydoddo** [comment]
Any traction on this?

**Comment by prime31** [comment]
I can’t repro it on any of my 3 computers and no one else has reported the issue so as of now it seems to be isolated to your box.

**Comment by hotdiggitydoddo** [comment]
I have a hard time believing it's isolated to solely me because i can't get this to work on 2 distinct physical Windows boxes.  

I've attached another screenie with the console output and my project structure as well in case I have it wrong for some reason.  For what it's worth, i do notice "GREMEDY_string_marker not supported!" in the console output only appears when I launch in debug mode.  google doesn't seem to helpful with this issue.

Again, all of this works fine in Release mode, it's just that there's no stepping through the code.
![image](https://user-images.githubusercontent.com/2938036/57177877-9d14be00-6e1d-11e9-8b7d-6e1d866394c7.png)

I'm really not sure what I'm missing. :(

**Comment by prime31** [comment]
Closing this out. Doesn't seem to be anyone else experiencing the issue and Nez doesn't access the GPU itself so this would be a lower-to-the-metal issue anyway.
