### ISSUE TITLE
Incorrect PrototypeSprite rendering when its entity has parent

### ISSUE THREAD

**Issue by TheKrzyko** [prime31/Nez#464]
PrototypeSprite is rendered incorrectly when its entity has parent. The existing offset vary on different rotation.
```C#
var tireSprite = scene.createEntity( "tireSprite" );
tireSprite.addComponent( new Sprite( scene.content.Load<Texture2D>( "tire" ) ) );//Black tire
tireSprite.addComponent( new PrototypeSprite(8, 20) );//White tire
tireSprite.setParent( tireEntity );
```
![image](https://user-images.githubusercontent.com/8425579/56282007-58471280-610e-11e9-8638-67882f353869.png)

![image](https://user-images.githubusercontent.com/8425579/56282604-d35cf880-610f-11e9-8153-7cbc920c0a7e.png)

**Comment by prime31** [comment]
You will most likely need to adjust the `LocalOffset` per instance of the `PrototypeSpriteRenderer`. It wasn't designed for hierarchies so it wont behave with how you would expect seeing as how it is anchored by a corner.
