### ISSUE TITLE
Why does Nez/Nez.Portable/ECS/Components/IUpdatable.cs duplicate MonoGame/IUpdatable?

### ISSUE THREAD

**Issue by cybtachyon** [prime31/Nez#465]
`Microsoft.Xna.Framework.IUpdatable` is a similar and identically-named interface to `Nez.IUpdatable`.

I understand they accomplish some of the same tasks, but honestly this seems to cause more problems than it solves IMHO. Is there a better solution, maybe by extending the original MG interface and adding IComparable vs a brand new Nez interface?

**Comment by prime31** [comment]
Nez ditches the entirety of the XNA component system. XNA Components don’t take part in a Nez scene at all. Changing the name of the interface would just cause everyone using Nez to have a breaking change in their code. It doesn’t really serve much purpose to change it at this point.

**Comment by cybtachyon** [comment]
Thanks for the background.

I'm not suggesting that we introduce a breaking change, and I agree there's no purpose to doing that.

However I'm uncomfortable with this issue being closed as that's a sort of "Ignore the problem" approach. Would it be possible to either allow edits to the project wiki https://github.com/prime31/Nez/wiki or allow forking & PR's so that the community can assist with documentation?

I'd like to contribute back documentation for what I'm discovering as I use Nez on a real project.

**Comment by prime31** [comment]
You can absolutely send PRs for the docs. They are all just .md files right in the main repo. Feel free to fork, mod and PR any changes you have.

**Comment by cybtachyon** [comment]
Are you just talking about https://github.com/prime31/Nez/tree/master/FAQs or would you suggest moving the Wiki content into the repo?

**Comment by prime31** [comment]
The FAQs are what most people see. Wiki is very basic and not many folks find it.

**Comment by cybtachyon** [comment]
Ok, wonderful, thanks so much for the info! I'll get to cracking on PR's for the docs and hopefully we'll end up with some helpful contributions! I appreciate you taking the time to walk me through this 😁 

`/me stops necroing the issue`
