### ISSUE TITLE
nuget package?

### ISSUE THREAD

**Issue by darthdeus** [prime31/Nez#48]
I just came around looking to get started with Nez and was surprised there isn't a nuget package available.

**Comment by prime31** [comment]
Nez is still under heavy development. Once it reaches a nice, stable version 1.0 with extensive documentation I'll stick it on NuGet. For now it's best used with the source intact.

**Comment by qntf** [comment]
Are we at that point yet? @prime31

**Comment by prime31** [comment]
It probably wont ever happen unfortunately. With all the extra shader files, multiple projects present now NuGet just isnt a great option.
