### ISSUE TITLE
Standard versions

### ISSUE THREAD

**Issue by xposure** [prime31/Nez#480]
I see there is a FNA.Standard project but there is not a corresponding standard project for the rest of the sub projects like persistence and imgui, is there a reason I'm missing.

I ask because i'm trying to include FNA.Core and all of the Nez projects in to a solution and the Nez.FNA projects are not picking up the main Nez project since its Nez.FNA.Standard and the other projects don't appear to be targeting core.

**Comment by xposure** [comment]
That being said, Persistence has a dependency on Nez which it doesn't use and also one on FNA thats only used for a single line.

```
#if FNA
			return SDL2.SDL.SDL_GetPrefPath( null, exeName );
#else
			return Path.Combine( Environment.GetFolderPath( Environment.SpecialFolder.LocalApplicationData ), exeName );
#endif
```

Those could be possibly removed.

**Comment by prime31** [comment]
Feel free to send over a PR. I don't think many folks are targeting Core at the moment so adding Core support isn't a priority for me personally.
