### ISSUE TITLE
Request for meta data on buttons/check boxes

### ISSUE THREAD

**Issue by bayganik** [prime31/Nez#482]
I love the UI buttons and  sliders !!  But I can't find a way to assign an extra value to them to know which one was clicked on (When they are an element in a canvas).  It would be nice if they had a TAG, much like an entity.

This will allow me to have an array of canvas elements all using the same onClick event.  By testing the TAG, I'll know which one was pressed.  I don't use the text property.

Thanks
Kamran

**Comment by prime31** [comment]
Element now has a UserData object field

**Comment by bayganik** [comment]
Thank you so much.
