### ISSUE TITLE
BitmapFont.measureString() always returns a height of 0.

### ISSUE THREAD

**Issue by thatpixelguy** [prime31/Nez#485]
The local `blockHeight` variable (line 335 of [BitmapFont.cs](https://github.com/prime31/Nez/blob/master/Nez.Portable/PipelineRuntime/BitmapFonts/BitmapFont.cs)) in the new BitmapFont's measureString() method is used to return the height of the string (line 377), but `blockHeight` is never updated and thus is always 0. This causes TextButtons to always have a height of 0.

I've made a simple fix locally (iterated through the `lineHeights` list at the end of the method and added the value of each item to `blockHeight`), but I'm working in the PascalCase branch so I'm not sure where/how I should submit a PR since the issue affects the main branch too.

**Comment by prime31** [comment]
Feel free to submit the PR on the PascalCase branch and I'll cherry pick and convert the commit to master.
