### ISSUE TITLE
Collider.collidesWithAny and multiple collisions

### ISSUE THREAD

**Issue by nikarh** [prime31/Nez#487]
Hi, 
I have noticed, that when I have a `Collider`, which by moving with `motion` will collide simultaneously with multiple components on another collision layer, `collidesWithAny` returns true, but `CollisionResult` is empty (zero vectors, null collider). Is this the expected behavior or am I doing something wrong?
Thank you!

**Comment by prime31** [comment]
Please reopen with a repro project/code if this is still an issue.
