### ISSUE TITLE
ImGUI IFinalRenderDelegate conflict?

### ISSUE THREAD

**Issue by witlock** [prime31/Nez#488]
Whenever I use ImGUI my Scene implementing IFinalRenderDelegate stops working (handleFinalRender not called).

**Comment by witlock** [comment]
ImGui also "breaks streaming" when using window capture. It only displays the "ImGUI stuff".

**Comment by prime31** [comment]
ImGUI installs itself as the `IFinalRenderDelegate`. If your game is also using one you will need to create a wrapper `IFinalRenderDelegate` that calls the ImGUI interface methods and your own custom ones.
