### ISSUE TITLE
Handling layer depth via Tiled?

### ISSUE THREAD

**Issue by meowgoocat** [prime31/Nez#49]
I'm curious what the preferred approach to changing layer depth is when importing with Tiled (IE some layers in foreground, some in background, etc).  The approach I'm trying now is to have tile layers with a custom Depth property, and then setting the value to a TiledLayer object.  Then, when the TiledLayer is to be drawn, I pass in the depth value of the current layer being drawn instead of the map's layerDepth value.

This isn't working, though I'm not sure why.

The only other approach I can think of is to have separate map components for each depth I want to use, but that seems unwieldy.

Any way to do this elegantly?

**Comment by prime31** [comment]
I wouldn't say there is any specific preferred approach for dealing with layer depth. Depending on your particular needs there are lots of ways to handle it. For a side scroller just rendering your layers back to front and rendering your player just after your main layer is all that is required. For a top-down game any tiles that can occlude the player would need to be rendered after the player. You can see an example of that in the Ninja Adventure sample.
