### ISSUE TITLE
TilemapComponent Y Sort

### ISSUE THREAD

**Issue by Toemsel** [prime31/Nez#491]
How do I enable Y Sort for objects within the ECS System in order to render them behind or above a tileset layer?

Similar to https://github.com/prime31/Nez/issues/150

However, I don't want to apply an effect onto every tile and as far as I saw the source code, there isn't a possibility to render layers depending on other entities Y coordinate.

Before I start implementing a custom renderer, did someone already address this issue?

**Comment by prime31** [comment]
You can now set your own sorter for the renderable lists: https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/InternalUtils/RenderableComponentList.cs#L8

**Comment by Toemsel** [comment]
I am not seeing how this should help us properly.

The entities are moving permanently, thus requiring a RenderLayer re-adjustment nearly each update. Sorting the list (with a force update) does the job, but doesn't quite fit the requirements.

**Comment by prime31** [comment]
If the sort solution doesnt work for you then subclassing Renderer and doing your own custom implementation would be the appropriate way to proceed. Nez lets you full take over the rendering process with a `Renderer` subclass.

**Comment by Toemsel** [comment]
I thought that a 2D focused framework extension does provide already a default implementation for Y-Sort. However, thanks for your time and work.

**Comment by prime31** [comment]
Well, it does. The isometric folks are using the aforementioned sorter. You mentioned that was not good enough for your particular situation so in that case a game-specific Renderer subclass was suggested so that you can do your rendering exactly how you want to do it. Every game and every dev has their own requirements which is why the Nez rendering system is totally overridable. A custom Renderer is about 10 lines of code making it accessible to any game to have its own custom setup.

**Comment by Toemsel** [comment]
Since my original post was in August, I already did implement a custom renderer :) I was just curious of other possible solutions.

**Comment by witlock** [comment]
What I did was a create a system that goes through every tile, image object and player sprite and sets the LayerDepths based on their position. Is that bad?

**Comment by prime31** [comment]
If it works for you go with it. There are always lots of ways to do things in the game dev arena.
