### ISSUE TITLE
Tiled Collision Information

### ISSUE THREAD

**Issue by leononame** [prime31/Nez#494]
I've recently started to look into Monogame and more specifically Nez and I've had a short look at the samples. I see that the Tiled Map import uses a dedicated collision layer to manage collisions. Does Nez also support the Tiled Collision Editor? It would be nice if one could define a collision shape for a single tile and thus making the collision layer unnecessary. Additionally, it could support collision polygons. 

Is there a way to do this that I simply did not find? Or is there no support for it?

**Comment by prime31** [comment]
Out of the box, Nez can automatically create collision via layer. All the other data is available via object layer and you are free to create your collision from it if you would like manually.
