### ISSUE TITLE
Cannot resolve reference to System.Drawing when targeting Android on 0.9.4

### ISSUE THREAD

**Issue by mijofr** [prime31/Nez#497]
When building to target Android against 0.9.4, I receive error message 

Can not resolve reference: `System.Drawing`, referenced by `Nez`. Please add a NuGet package or assembly reference for `System.Drawing`, or remove the reference to `Nez`.	

Adding a nuget reference to System.Drawing.Common isn't any help. I'm able to build successfully against Windows OpenGL, however. Issue is fixed when downgrading to Nez 0.9.2

**Comment by mijofr** [comment]
If it's relevant, I'm adding Nez via the nuget package, not via nested repository.

**Comment by AnshumanKumar14** [comment]
In the assembly of nez references. Go to Nuget manager and update the System Drawing. This should fix your issue.

**Comment by mijofr** [comment]
System.Drawing is not a Nuget-distributed assembly.

**Comment by prime31** [comment]
https://www.nuget.org/packages/System.Drawing.Common/

**Comment by mijofr** [comment]
As I mentioned, adding Nuget references to the latest version of that package.

**Comment by DriantG** [comment]
Same issue here, cannot get Android project to compile, no matter what I tried. Was really hyped about Nez :(

**Comment by prime31** [comment]
If you arent using SVG parsing you can just remove the System.Drawing reference completely.
