### ISSUE TITLE
Origin and FlipX in sprites

### ISSUE THREAD

**Issue by nikarh** [prime31/Nez#498]
Hi,
I have a simple spritesheet with character animation. After sheet optimization I have subtextures with unequal widths, so I am compensating for that in subtextures `Origin` field. But when I set `FlipX` equal to true in my Sprite animation, the render method still offsets my texture from the left side.

Right now I am hacking `Render` method of `Sprite` and using the following Vector2 instead of `Origin` field:

```csharp
new Vector2(
    FlipX ? _subtexture.SourceRect.Width - Origin.X : Origin.X,
    FlipY ? _subtexture.SourceRect.Height - Origin.Y : Origin.Y
)
```

**Comment by prime31** [comment]
Flip just flips a sprite. If you require different behavior you’ll need to address that in your calling code.

**Comment by nikarh** [comment]
Here's an example. I have a 32x32 sprite animation. Yellow rect is a bounding box, pink line is located at `myEntity.Position.X` (it also indicates a default Origin in case it is not provided in Subtextures constructor), and black stuff is an actual sprite.

To reduce the size of my final spritesheet, I can reduce the size of each frame to a yellow rect. If I didn't do that, everything would have worked - every `Subtexture` would have been 32x32, and a constructor of a `Subtexture` would have calculated `Origin` as `sourceRect.GetHalfSize()`. As you can see on the example images, after optimization I would get a 20x24 sprite for the first frame and 12x31 for a second frame. 
To compensate for that during rendering, for the first image I have to set origin to 16 (distance from the left side of yellow rect to a pink line, default would have been calculated as 10), but for the flipped variant for sprite, Origin should be 4px (distance from left side of the yellow rect to a pink line, or calcualted as 20-16, sprite width minus non-flipped offset). The same goes for the second image.

![Sprite-0002](https://user-images.githubusercontent.com/5517011/65374758-25ddaa80-dc96-11e9-9f97-62a145b12885.png)
![Sprite-0003](https://user-images.githubusercontent.com/5517011/65374759-25ddaa80-dc96-11e9-860b-245660b2396d.png)

Since each `Subtexture` of the animation can have it's own `Origin` an size, and animation frames are changed implicitly by `Sprite<T>. Update`, I see no other way to do this in my code, but by overloading `Update` method of every entity which has a sprite animation, calculating and setting a new origin after calling `base.Update()`, which could have changed a sprite of my animation to a next frame.

I still believe that this might be a common case for those who want to optimize their spritesheets, and it would be nice if Nez could provide an API for that.

Thanks!
