### ISSUE TITLE
SpriteAtlasLoader.ParseSpriteAtlas error when called at LoadContent

### ISSUE THREAD

**Issue by edwinsyarief** [prime31/Nez#499]
Hi,

I'm trying the latest **Nez SpriteAtlasLoader**, an error occured when I called **ParseSpriteAtlas** method at **LoadContent**, here is the detail error:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: graphicsDevice at SpriteAtlasLoader.cs:line 18
```

at this line :
```cs
return spriteAtlas.AsSpriteAtlas(Texture2D.FromStream(Core.GraphicsDevice, stream));
```
the value **Core.GraphicsDevice** is null

But, working smoothly when I moved the ParseSpriteAtlas at Initialize method.

I also cannot use **ImGuiManager**, the error is the same **Core.GraphicsDevice** is null

Please help

**Comment by prime31** [comment]
Nez doesn't expect you to be overriding LoadContent like that. you wont be able to do anything that needs the GPU until the GraphicsDevice is actually set: https://github.com/prime31/Nez/blob/new-sprite-atlases/Nez.Portable/Core.cs#L223

If you use the Scene system everything will be setup and ready when a Scene is started. If you choose not to use the Scene system than you need to take care that Core.Initialize is called before you do anything with the GPU.
