### ISSUE TITLE
Possible redundant method in Mathf

### ISSUE THREAD

**Issue by foreverWIP** [prime31/Nez#501]
I was browsing the source and came across this method in Mathf:

```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool WithinEpsilon(float floatA, float floatB)
{
    return Abs(floatA - floatB) < float.Epsilon;
}
```

[The specification for epsilon](https://docs.microsoft.com/en-us/dotnet/api/system.single.epsilon) confirms that it is the smallest positive value represented by a float. So if you're checking if the absolute value of an expression is less than epsilon, wouldn't that be equivalent to checking if the value is 0 (since 0 is the only "positive" value smaller than epsilon)?
I can set up a pull request that replaces usages of this method with a check for 0, but I wanted to make sure there wasn't anything I was missing in this first.

**Comment by prime31** [comment]
You are exactly correct! This method should actually take in an epsilon as user input to use for the comparison that defaults to a reasonable value if not passed in.

**Comment by foreverWIP** [comment]
I'll set up a pull request for it, but in the meantime, something else to note:
The method is currently used only 3 times, and every use has 0 as the second parameter (so in effect it's checking if the first parameter is less than epsilon, i.e. 0), so I could replace the calls with a check for 0 and modify the method to allow a variable epsilon for future use.

**Comment by prime31** [comment]
Sounds like a plan
