### ISSUE TITLE
System.TypeInitializationException on latest commit.

### ISSUE THREAD

**Issue by mythicaldog** [prime31/Nez#51]
"The type initialiser for 'Nez.Input' threw an exception" when running on the latest commit.
System.DllNotFoundException: user32.dll at (wrapper managed-to-native) Microsoft.Xna.Framework.Input.Touch.TouchPanelCapabilities:GetSystemMetrics (int).

```
			// set some values in the Input class to translate mouse position to our scaled resolution
			var scaleX = renderTargetWidth / (float)_finalRenderDestinationRect.Width;
			var scaleY = renderTargetHeight / (float)_finalRenderDestinationRect.Height;

			Input._resolutionScale = new Vector2( scaleX, scaleY );
			Input._resolutionOffset = _finalRenderDestinationRect.Location;
```

This area in scene seems to cause the problem.

**Comment by prime31** [comment]
Thats a bit odd. I can't seem to repro this. Moreover I would expect the issue to happen in the [TouchInput class.](https://github.com/prime31/Nez/blob/master/Nez-PCL/Input/TouchInput.cs#L47). If you stick a breakpoint in there is that method returning?

**Comment by mythicaldog** [comment]
Okay so it tries to run:
`_isConnected = TouchPanel.GetCapabilities().IsConnected;`
and fails because user32.dll is not found :/

![screen shot 2016-06-29 at 23 51 40](https://cloud.githubusercontent.com/assets/11300674/16471438/a0e05932-3e54-11e6-8d73-72b2a9a3d45e.png)

**Comment by mythicaldog** [comment]
Okay this fixes it, seems DesktopGL doesn't like TouchPanel on OS X not sure about windows? Although you are using OS X are you not?

`#if !___IOS___ || !___ANDROID___ || !FNA
			_isConnected = false;
#else
			_isConnected = TouchPanel.GetCapabilities().IsConnected;
#endif`

**Comment by prime31** [comment]
I am indeed on OS X and it seems to work for me. Very odd. I'll wrap it up in the next commit just to be safe.

**Comment by mythicaldog** [comment]
Possibly something different in Xamarin 6.0 to 6.0.1? That's the only thing that is different between our setups that I can think of.

**Comment by prime31** [comment]
I just pushed a commit that does things a bit differently and requires manually enabling touch support. See if it solves it for you.

**Comment by mythicaldog** [comment]
Yeah working fine with that commit! Will test a touch device shortly but only had issue's on my mac regarding this. Thanks.

**Comment by prime31** [comment]
It seems to work on Mac, Windows and iOS for me so hopefully this does the trick.

**Comment by Sirhyro** [comment]
Hello, 

This issue is plaguing me. I'm new to Monogame and C#, but not Visual Studio so I know somewhat of what i'm doing.

I cloned the samples, built Nez/Nez.sln, then when I open Nez.Samples and attempt to run it I get:

```
An unhandled exception of type 'System.TypeInitializationException' occurred in Nez.dll
Additional information: The type initializer for 'Nez.Input' threw an exception.
```
It points to Scene.cs:656 which is
`
Input._resolutionScale = new Vector2( scaleX, scaleY );
`

OS: Windows 10 x64
IDE: Visual Studio Community 2015

**Comment by prime31** [comment]
A TypeInitializationException will hide the underlying problem. Put a breakpoint in the Input initializer and see what the real exception is and where it is occurring.

**Comment by Sirhyro** [comment]
Hi, 

I'm not sure how to read the output of that linebreak. It seems to be pointing all over the place.

![nez_error](https://cloud.githubusercontent.com/assets/6743505/16527841/1d59ef36-3f87-11e6-913b-585806d65049.png)

Is this an issue with something i've done, or the repo? I haven't done any modifications other than the previously mentioned fix, so this is an error straight out of the box.
-
MonoGame SDK 3.5.1
XNA Redist 4.0 Refresh

**Comment by prime31** [comment]
There shouldn't be any need to change the base code at all. A fix was pushed in a recent commit that moves touch stuff into its own method until MonoGame gets a fix out.

It's impossible to say what is happening here without the actual Exception. Stick a breakpoint in the Input constructor and step through there. That will reveal the actual error that is occurring.

**Comment by prime31** [comment]
Closing this one since it seems like it is all fixed up.
