### ISSUE TITLE
version 0.10.0 on NuGet does not match Github

### ISSUE THREAD

**Issue by PastTheFuture** [prime31/Nez#516]
I might be misunderstanding something here, but it would appear that the package on NuGet for v0.10.0 is missing some of the changes that were made to Sprites/Animations. Namely it still contains Sprite instead of SpriteRenderer and SpriteAnimation instead of SpriteAnimator.

There could be more it's missing, I'm not sure.

**Comment by prime31** [comment]
NuGet is deprecated and no longer updated. Nez should always be used with the source code which contains tons of useful comments.
