### ISSUE TITLE
Text Component Font Scale

### ISSUE THREAD

**Issue by witlock** [prime31/Nez#52]
I'm trying to create some HUD elements by adding **Sprite**s and **Text** under a certain HUD component to the entity.
I'd like to decrease the size of the font, but it looks like the only way to do that is to scale the entity. Is this correct?
What is the recommended way to achieve this? Should I have the text under a different entity or should I use the UI classes instead?

**Comment by prime31** [comment]
The Text Component indeed uses the Entity scale. You could just stick it on another Entity and parent it to your main Entity so it moves along with it.

Another option would be to just make a new RenderableComponent subclass that you can setup however you like and just make it draw the string with the parameters that you set.
