### ISSUE TITLE
No support for loading audio in v10 NezContentManager for MonoGame. FNA's ContentManager works.

### ISSUE THREAD

**Issue by slikvik55** [prime31/Nez#527]
FNA's standard content loader will look for an XNG and if it's not found will load a wav.
MG's content loader has no such support so you're still forced to use the pipeline tool or load from stream.
Making a request to add a LoadSoundEffect method to the NezContentManager.

**Comment by prime31** [comment]
Feel free to send over a PR. I personally don’t use MonoGame and always suggest folks switch to FNA.
