### ISSUE TITLE
Incompatibilities with MonoGame 3.8

### ISSUE THREAD

**Issue by Shidesu** [prime31/Nez#529]
When trying to use MonoGame 3.8, GetMonoGameEmbeddedResourceBytes() is throwing a null reference Exception.
Looks like Nez is not capable of getting embedded resource with MonoGame 3.8.
Though MonoGame 3.8, even if still on development, is a necessity for some people because of the OpenAL errors from previous versions.

**Comment by prime31** [comment]
There is a bug report open with the MG team. They realized they broke XNA compatibility and MG compatibility with the change so it should be reverted at some point on there end. In the meantime you can just add some code to the EffectResource class to change the path to the new one they moved the effects to.
