### ISSUE TITLE
Nez project failed to load

### ISSUE THREAD

**Issue by Saliken** [prime31/Nez#53]
When I clone Nez to one of my computers and attempt to open the solution it fails. The Nez project says load failed and gives me the following message:

"The project is targeting frameworks that are either not installed or are included as part of future updates to Visual Studio."

I've cloned the Nez project previously onto my desktop computer and the project loaded just fine, only on this other PC is it giving me this error.

Two things to note:
1. The Nez project won't load, but the pipeline importer project does
2. My computer that it does load on is running VS2015, my other (where it fails) is running 2013. Both have the same version of monogame installed.

**Comment by prime31** [comment]
Nez now targets .NET 4.5 PCL. It sounds like your old install with VS 2013 doesn't have the PCL profiles installed. You *should* be able to install them somehow but I can't say how it can be done. I havent used VS 2013 for many years.
