### ISSUE TITLE
Ability to provide my own content file streams.

### ISSUE THREAD

**Issue by dmitrymatveev** [prime31/Nez#533]
Hello,

Recently I have started using FNA + NEZ and I am eager and ready to completely dump monogame content pipeline.

I have got a set up working to manage my own content folder and load everything I need using PhysFS library.
a simple example of such is this:
```
            var pfs = new PhysFS("");  
            pfs.Mount("./Content.zip", "/", true);  
            return pfs.OpenRead("characters/player.png");  
```
This gives me a `Stream` object that, as far as, Nez is concerned identical to any other stream consumed by the the content manager class.  
All I need now is a way to instruct Nez to use my own sources of file streams instead of `TitleContainer.OpenStream` which is provided by FNA.

**The issue that I have run into is** that I can not easily add my own extension methods to `NezContentManager` since most `Load` functions also add parsed results to `DisposableAssets` list which is marked as `private` and I very much appreciate Nez Scenes managing life-circle of it's content objects.

One solution would be to create a delegate in `Nez.Core` that can be used as part of a strategy pattern. Use that delegate then in place of all occurrences of the `TitleContainer.OpenStream` line
``` using (var stream = Path.IsPathRooted(name) ? File.OpenRead(name) : TitleContainer.OpenStream(name))```

I would be happy to create a pull request with necessary changes if this is deemed a worthy addition to Nez.

Otherwise please advise on a better course of action, thoughts and ideas :)

Thanks

**Comment by prime31** [comment]
The `DisposableAssets` and `LoadedAssets` definitely arent appropriate to be exposed. They are internal implementations and backed by cached reflection even on FNA/XNA due to them being internally private.

I would suggest just subclassing NezContentManager (or even going a level higher and subclassing ContentManager) for something like this. Then you can just pass in your PhysFS root to it and let the content manager mount and manage it.

**Comment by dmitrymatveev** [comment]
@prime31 thanks for your reply.

I did consider sub-classing NezContentManager. But in this case I will still need access to `DisposableAssets` and `LoadedAssets` properties. Then there is also `TmxMap ` that is using extension methods internally to load its tilesets and that means that this class will also need to be extended or replaced.

Subclassing in this case in my oppinion would be an overkill resulting in me re-writting a big chunk of Nez loading classes and a great deal of duplication since I will need to copy-paste most of the class implementations.

This is the reason why I mention that all that is required in this case is a way to provide my own file streams.
This way Nez can keep handling all the assets exactly the way it is doing it right now with the only difference is that consumers provide it's own file reading routines.

Just by encapsulating this line of code `TitleContainer.OpenStream(name)` into a strategy method can provide exactly the necessary level of extendability that I am looking for.
