### ISSUE TITLE
Rename "Debug" folder to something not covered by default VisualStudio.gitignore

### ISSUE THREAD

**Issue by bretgourdie** [prime31/Nez#537]
The folder "Nez/Nez.Portable/Debug/" with source code is caught by the [VisualStudio.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) filter `[Dd]ebug/`.

This is frustrating when adding the project as source code to a repo, then having to redownload it after subsequent repo clones anyway since the folder gets ignored and stops the build.

Looks like there are no namespace issues since everything is in `Nez` anyway. I can provide a quick proposal.

**Comment by prime31** [comment]
You can just delete the line from the gitignore file...
