### ISSUE TITLE
Texture atlas element names

### ISSUE THREAD

**Issue by mythicaldog** [prime31/Nez#54]
I wouldn't really consider this an issue just something I noticed using Monocle that seems the correct way. So at the minute using a Texture Packer atlas my layout is this:

![screen shot 2016-07-03 at 20 00 34](https://cloud.githubusercontent.com/assets/11300674/16547083/d610b014-4158-11e6-9762-ee17f727234d.png)

I can access that texture I need in Nez by typing:

`getSubtexture("Wall_Top")`

The idea was I could have the same names under different "area" folders and be accessed like

`getSubtexture"(Enviroment/Forest/Wall_Top)"`

Instead of naming each of my actual files ForestWall_Top, OtherAreaWall_Top etc. Just a suggestion!

**Comment by prime31** [comment]
For a quick change to get the bevaiour you are looking for just change [this line](https://github.com/prime31/Nez/blob/master/Nez.PipelineImporter/TexturePacker/TexturePackerWriter.cs#L25) to be the following:

`writer.Write( region.filename );`

**Comment by mythicaldog** [comment]
Thanks and loving the new global manager and generated content stuff keep up the awesome work!

**Comment by prime31** [comment]
Check the latest commit for the Texture Packer change. It now matches the TP filenames minus the file extension
