### ISSUE TITLE
AddComponent Method acting strangely

### ISSUE THREAD

**Issue by kaiisch** [prime31/Nez#547]
I've started following the Youtube guide presented by [prime31](https://www.youtube.com/watch?v=ZfVMCbOniV0)

I only got about 11 minutes into the video when I noticed my code won't compile like his will. I feel this behavior is strange as it seems to be a pretty important part of the framework. I hope the screenshot included is of any help :).
The Code up until this point is nearly the same as that which is shown in the video.
** Code followed by error message**
```
protected override void Initialize()
   {

        base.Initialize();

        Scene _scene = Scene.CreateWithDefaultRenderer();

        var turtle = _scene.ContentManager.Load<Texture2D>("turtle");

        Entity entity = _scene.CreateEntity("first-sprite");
        entity.AddComponent(new Sprite(turtle));
    }
```
![grafik](https://user-images.githubusercontent.com/47891899/72295493-fcd39200-3657-11ea-857d-9460940d6481.png)

Thanks in advance!

**Comment by prime31** [comment]
Just like the error is telling you, Sprite is not a Component. Many things have been renamed since the video was made so you’ll want to look at the text documentation or the Samples repo for updated classes.
