### ISSUE TITLE
UI image cannot be resized

### ISSUE THREAD

**Issue by Memorix101** [prime31/Nez#548]
Hello, 
I am fairly new to nez so excuse me maybe the issue is on my end.
I tried to resize an image component for the UI based on the libGDX docs and
whatever I tried doesn't work. The only thing that worked for me is setting a different scale (float)
but then the layout is incorrect for me (maybe this is how it should be I don't know).
I also tried different scaling types. No change at all.
I hope someone can help me and maybe I found a bug here.

![image](https://user-images.githubusercontent.com/1466920/72755844-c653c500-3bcb-11ea-835e-b0469fd69d51.png)

**Comment by williamahartman** [comment]
If it's in a table (which it looks like it is in your example), setting the width/height of the cell after you add the image worked for me.

**Comment by Memorix101** [comment]
That code works so far but messes up the layout:
```cs
            table2.GetCell(fmg_img).SetMaxHeight(100f);
            table2.GetCell(fmg_img).SetMaxWidth(100f);
```
