### ISSUE TITLE
Larger than grid tiles drawn differently

### ISSUE THREAD

**Issue by witlock** [prime31/Nez#55]
I have a 16x16 grid on tiled, but I sometimes include tilesets of 32x32 tiles etc.
When placing those tiles in tiled they are drawn differently (anchor bottom left on Tiled).
What is the best way to sync the results without changing something about Nez that would not be pulled in later?

Is there anything built-in to adjust this currently?
I could theoretically place them as images on the object layer, but it would greatly reduce the dev speed.

**Comment by prime31** [comment]
I am not quite sure I follow. If I am understanding correctly, you are mixing two different tile sizes on the same tile map, is that correct? I have never seen that done before and I'm quite surprised it even works at all! Can you send a screenshot comparing what is in Tiled versus the output from Nez?

**Comment by witlock** [comment]
When you add a new tileset you can always pick another tile size. All the tools in tiled does not fully support this, but it does work.
It seems to move down the assets depending on how much it exceeds the grid size.
If the grid size is 16x16 and you add a tile of size 32x32 it will place it 16 pixels lower.
If the grid size is 16x16 and you place a tile of size 64x64 it will place the tile 48 pixels lower in Nez. (I think)

![misplace32](https://cloud.githubusercontent.com/assets/8792184/16565874/08ba3c7c-4219-11e6-9d5e-6080e6aea9f8.png)
