### ISSUE TITLE
Scene.Initialize runs before constructor

### ISSUE THREAD

**Issue by geirsagberg** [prime31/Nez#553]
Because `Initialize()` is called from the base constructor, any overrides will be called before derived constructors. More info here: https://www.jetbrains.com/help/rider/VirtualMemberCallInConstructor.html

Here is a screenshot of the types of issues this can cause: I inject a GameSettings instance in the constructor, and attempt to use it in the Initialize override, but receive a nullref:

![image](https://user-images.githubusercontent.com/594564/73772528-96d2ba00-4780-11ea-8605-bd49952fc35d.png)

I would suggest removing the Initialize method entirely; nothing can be done there that can't be done in the constructor. Or maybe look into allowing a method delegate to be passed to the base constructor, as is suggested in the Jetbrains article.

**Comment by prime31** [comment]
`Initialize` is not at all required to be used. There are other options including your constructor and `OnStart`. The initialize XML comment clearly states: `This is called from the constructor after the scene sets itself up`.

**Comment by geirsagberg** [comment]
My point is, perhaps it should be marked as `[Obsolete]`, if it can cause problems like the one I ran into, and there are other better options like constructor and `OnStart`?

I'm fine with not using it, just thought it might be better for new users to know to avoid it :)

Btw, great work on the library, I've just started using MonoGame again for the first time in 10 years (XNA 3.1), and Nez really saves a lot of time!
