### ISSUE TITLE
Latest NuGet package not functional (Visual Studio for Mac 2019) 

### ISSUE THREAD

**Issue by Diamond-Wolf** [prime31/Nez#554]
When I use the latest NuGet Package (0.10.0), I cannot access the Nez namespace and by extension any Nez functionality. Reverting to 0.9.5 allows access to the namespace.

**Comment by ZombieBear** [comment]
I've opened the 0.9.5 and 0.10.0 packages  in winrar and the 0.10.0 package is literally missing the whole lib directory

**Comment by prime31** [comment]
Using NuGet is not recommended for Nez use. The source code is an invaluable resource and deving without it is noon her supported. The 0.10 NuGet will be removed.
