### ISSUE TITLE
Adding ITriggerListener component to an entity with a collider doesn't fire onTriggerEnter with Tiled collision layer

### ISSUE THREAD

**Issue by darthdeus** [prime31/Nez#56]
I'm using the `TiledMapComponent` to setup my collision layer. What I wanted is to add a collider to the entity that moves on the tile map and get collision data.

Looking through the source code for `Mover`, specifically `notifyTriggerListeners` it seems that any `ITriggerListener` component attached to the colliding entity should fire the events on collision, but it doesn't happen.

**Comment by prime31** [comment]
ITriggerListener will only notify of intersections with Colliders setup as triggers. If you want to move and get the details of a collision when you call Mover.move it returns via out the CollisionResult. Alternatively, if you are only doing tile map collisions there is a Mover that works with them directly: https://github.com/prime31/Nez/blob/master/Nez-PCL/ECS/Components/Physics/TiledMapMover.cs If you need more data you can always just mimic what Mover does and take control of all the details.
