### ISSUE TITLE
Deferred Light Sample in FNA return a grey screen

### ISSUE THREAD

**Issue by Predator75** [prime31/Nez#560]
Hi,
the deferred Light Sample in FNA return a gray screen, with mono works
regards
![immagine](https://user-images.githubusercontent.com/1283811/76697979-d228a880-669d-11ea-9971-5df7a61b6e76.png)

**Comment by flibitijibibo** [comment]
This is resolved by https://github.com/prime31/Nez/commit/4e10edc55ad3bcdd2395ab1b2ed98a24dfb8d174
