### ISSUE TITLE
Is Nez pipeline importer deprecated?

### ISSUE THREAD

**Issue by potateprogrammer** [prime31/Nez#561]
I can't find the Nez pipeline importer folder in the master branch and when I try to import things Tiled maps and error is thrown stating it cant find an importer.

So how load things like Tiled maps, effects etc in _Binary_?

**Comment by prime31** [comment]
All pipeline importers were removed a few months ago. All asset loading is now with raw asset files.

**Comment by Argiziont** [comment]
Could you left some examples with this 

> raw assets

 approach

**Comment by NoHarmDan** [comment]
...which brakes the Samples repo, doesn't it?
