### ISSUE TITLE
Nez documentation a little bit deprecated

### ISSUE THREAD

**Issue by Argiziont** [prime31/Nez#565]
Could you update doc, becouse for newbies in nez like me, a lot of things are too complicated, like, i tried to do as u show in youtube videos but  they are even more deprecated that documentation, and i couldn't even copy-paste code from doc/video and compile project without errors. 
I know SFML and it helps me a lot, but Monogame still one of the top popular game-frameworks for .NET, and it would be good idea to upate your documetation, cuz NEZ for a now is top 1 library for monogame, thank you in advance.

**Comment by prime31** [comment]
The YouTube videos are definitely not documentation. They are just demos. Feel free to send PRs if you find anything that needs updating in the actual docs in the Nez repo.

**Comment by toyboot4e** [comment]
I guess he is referring to the [Docs](https://prime31.github.io/Nez/documentation/setup/installation) website. It's outdated

**Comment by prime31** [comment]
How does one locate the docs page? Is there a link to it somewhere that im not seeing?

**Comment by toyboot4e** [comment]
No, there's no link to it in the repository. It can't be found without googling. But I think the FAQ is OK, so if something official doesn't work, that might be from the Docs.

**Comment by prime31** [comment]
I just removed the gh-pages branch altogether. That should solve the issue.
