### ISSUE TITLE
Object space LineRenderer disappears when Worldspace origin not in view of camera

### ISSUE THREAD

**Issue by PastTheFuture** [prime31/Nez#567]
Title says it all. A LineRenderer operating in object space (as opposed to world space) will disappear depending on its position relative to the camera and zoom. My best guess through some experimentation is that when determining if the component is on camera (and therefore should be drawn) it is still using world space coordinates rather than its parent object coordinates. It will render properly anytime the WorldSpace Origin(0, 0) is in camera. 

![NezOrbital_2020-04-05_00-50-01](https://user-images.githubusercontent.com/7075990/78469598-9c447600-76d7-11ea-9fa6-5404f80d80ca.png)
.

**Comment by prime31** [comment]
Bounds is the only thing used for visibility checks and it should get updated automatically when you call `CalculateVertices()`. If you turn on debug rendering in the console you should be able to tsee the bounds rect.
