### ISSUE TITLE
Loading TiledMaps

### ISSUE THREAD

**Issue by MythicalMarsh** [prime31/Nez#569]
Idk what I'm doing wrong but seriously been fighting this stuff for like 5 hours. 
I put the tmx etc in Content and build it with the pipeline importer,but then it wants it in bin/debug/500 file paths so then fine I put it there it works but if I try to play it on release it doesn't work like am I doing something wrong? is this how it is? I'm so confused.
![Sprite-0001](https://user-images.githubusercontent.com/63443278/79671384-445e4280-81a0-11ea-9bd4-d0edec63f366.png)

![Sprite-0002](https://user-images.githubusercontent.com/63443278/79671440-9ef79e80-81a0-11ea-8b5d-ebb77ec32309.png)

**Comment by sachdevs** [comment]
Did you remember to set `Copy To Output Directory` to `Copy If Newer` in visual studio?

**Comment by MythicalMarsh** [comment]
> 
> 
> Did you remember to set `Copy To Output Directory` to `Copy If Newer` in visual studio?

I've tried doing this but it seems to of done nothing :/ feels like this type of stuff only happens to me
