### ISSUE TITLE
Nez and Tiled workflow

### ISSUE THREAD

**Issue by potateprogrammer** [prime31/Nez#570]
I'm a little confused on how to integrate Tiled maps in a Nez project. 

What I'm currently doing is placing the tmx file and it's respective png tileset file in the build content folder and then accessing it via `NezContentManager.LoadTiledMap`. This causes me to expose the raw files in the final build.

Is there another way to do this (maybe integrate it with the MGCP? ). Or if this is the way, am I doing it right?

Any help is appreciated.

**Comment by Shidesu** [comment]
The Pipeline is no more used by Nez so you're doing it the right way.
