### ISSUE TITLE
Font's don't draw properly when using MonoGme.Framework.DesktopGL.Core

### ISSUE THREAD

**Issue by CipherLab** [prime31/Nez#571]
I don't really know if the issue is core vs full, but I can't get fonts to show properly for the life of me. 
I tried the default font (shown below) a spritefont, other bitmap fonts. I can get some bitmap fonts to be readable but they look like garbage. Doesn't matter though, the default font should work.
![](https://i.imgur.com/LldHSwy.png?raw=true)

**Comment by prime31** [comment]
None of Nez code changes between Core vs Framework so I cant provide any insight as to why Core doesnt handle font textures properly.

**Comment by CipherLab** [comment]
I'd agree except the xna loader in the same project works...doesn't that mean it's something Nez is doing?

**Comment by xdrie** [comment]
looks like this is the same issue i'm experiencing (#574), it looks like the cause of it is not Nez and instead something about MonoGame on .NET Core.

however, @CipherLab you mentioned that the default font still works; however, when I use the default BMFont i still have the same issue. were you able to find a workaround of some sort?

**Comment by CipherLab** [comment]
Sorry, I only meant the default works queen running desktop.gl (not core). I boiled down to the simplest code I could with core and nez, just drawing a bit of text and I couldn't work out the cause. Glad I'm not the only one though! I really wanted nez to work with my .net core app

**Comment by yhuang0** [comment]
Doing a (0.5, 0.5) transform at the root Begin call did the trick for me. If you're using NezUI, I also had to do stage.GetRoot().SetPosition(0.5f, 0.5f). I didn't look into why it works but you can try to see if it works for you.

**Comment by CipherLab** [comment]
@yhuang0 Sorry, how did you do a transform at Begin? In the batcher?

**Comment by yhuang0** [comment]
Yea, there should be a parameter to pass in a custom transform to Begin.
You would create the translation offset like this:
`var transform = Matrix.CreateTranslation(0.5f, 0.5f, 0f);`

You should probably try to get it working with just BitmapFont and Graphics.Instance.Batcher.DrawString first before you try to get the NezUI text to work

**Comment by CipherLab** [comment]
@xdrie If @yhuang0 confirms there's a fix, could it be implemented?

**Comment by xdrie** [comment]
here are some relevant links from the MonoGame repo:
- https://github.com/MonoGame/MonoGame/issues/6619#issuecomment-451286471
- https://github.com/MonoGame/MonoGame/pull/6780
- https://github.com/rds1983/MonoGame/commit/ce488de243860a2a8e06e3ff74acba03cbbcf4f2

**Comment by xdrie** [comment]
Okay, I can confirm that setting `PreferHalfPixelOffset` to `true` in the creation of the `GraphicsDeviceManager` in `Core` resolves this issue.
However, it looks like this issue is primarily present in .NET Core, so we might want to set this flag via reflection or conditional compilation. Thoughts? @prime31

**Comment by xdrie** [comment]
here is an example fix. make sure MonoGame is updated to v3.8 in your Nez project.

https://github.com/xdrie/Nez/commit/582cccb42caa6243e144749ca1eff23c85ff1609

**Comment by CipherLab** [comment]
@xdrie confirmed that worked... tyvm.

**Comment by prime31** [comment]
Oh fantastic! The age old half pixel offset strikes again. If there is a compiler define for Core that could be used but first it would have to be confirmed to be an issue on linux and macos as well as Windows. I'm going to venture a guess they will probably work fine.

**Comment by xdrie** [comment]
I have tested on Linux and macOS, and this fix does seem to solve it!

**Comment by CipherLab** [comment]
To get it to compile I had to change a few Vector2.Round() because it returns void in Core?

**Comment by jamsilva** [comment]
This issue is happening to me with .Net 5.0 on Linux. A different fix that works for me on Linux using either FNA or MonoGame is adding this line to `Initialize` on the class that derives `Core`:
```
Batcher.UseFnaHalfPixelMatrix = true;
```
