### ISSUE TITLE
LayerDepth for individual tiles

### ISSUE THREAD

**Issue by DrGurka** [prime31/Nez#572]
Hey, i've been lurking around the issues here to find a solution to my problem but i can't seem to find anything up to date and don't know where else to post this.

I have an isometric tile map which i want to simulate depth onto.
My first thought was to just set every tiles layerDepth to 0-1 depending on where on the y axis it was and do the same for all my entities.
But for some reason it wasnt working, as soon as i updated the entities layerDepth they dissapeard behind the tile map almost like the whole tilemap was on just on the layerDepth float.

I found out this is because Nez sorts every RenderableComponent in a list for its draw order.
Both the entity and tilemap is on the same RenderLayer, i've read about the custom sorting but i don't see how that would work with the tilemap since the whole map is one RenderComponent altogether which would not enable every tile to have individual depth, right?

Could anyone help me with how i am supposed to solve this?
Do i need to make my own TileRenderer, i've already changed it so it can draw Isometric maps from Tiled tmx files since i couldn't find if it was already implemented.

**Comment by prime31** [comment]
Tiles arent drawn individually so they do not have their own layer depth by default. you would need to make your own tile renderer that sorts and draws however you need. By default, all tiles are drawn in a single batch.
