### ISSUE TITLE
pixel art scaling artifacts with ShowAllPixelPerfect

### ISSUE THREAD

**Issue by xdrie** [prime31/Nez#574]
```cs
var resolutionPolicy = Scene.SceneResolutionPolicy.ShowAllPixelPerfect;
// resolution is the variable passed to Core constructor
Scene.SetDefaultDesignResolution(resolution.X, resolution.Y, resolutionPolicy);
```

there are significant pixel art scaling artifacts with both `ShowAllPixelPerfect` and `BestFit`.
i tried applying `PointClamp`, which did not really help with the issue.
```
DefaultSamplerState = SamplerState.PointClamp;
```
this creates scaling artifacts in fonts and in the entire screen, causing tearing that looks like it's due to downscaling.
However, `Core` is initialized with the exact same `resolution`, so no scaling needs to be done; the resolution policy simply should ensure that scaling is pixel-perfect.

am i using the api's wrong? i feel like i'm missing something.

**Comment by prime31** [comment]
When you choose a pixel perfect variant scaling will always be an int. Try out the examples in the Sample repo. There are several pixel perfect examples that show how to set things up and that scale with your window size changes.

**Comment by xdrie** [comment]
I did try those examples, but I'm still getting artifacts that look like this:
![image](https://user-images.githubusercontent.com/54390138/80178590-7235f380-85b3-11ea-9f0b-63dd8cd7bee9.png)

Here is all the source I am using:

`TestGame.cs`
```csharp
    public class TestGame : Core {
        public TestGame() : base(960, 540) { }

        protected override void Initialize() {
            base.Initialize();

            Scene = new TestScene();
        }
    }
```

`TestScene.cs`
```csharp
    public class TestScene : Scene {
        public override void Initialize() {
            base.Initialize();

            ClearColor = Color.RosyBrown;
            SetDesignResolution(960, 540, SceneResolutionPolicy.ShowAllPixelPerfect);
            Screen.SetSize(960, 540);
        }

        public override void OnStart() {
            base.OnStart();

            // test text
            var ui = CreateEntity("ui");
            ui.AddComponent(new TextComponent(Graphics.Instance.BitmapFont,
                $"test text! this is running v0.7.19\nabcdefghijklmnopqrstuvwxyz0123456789", new Vector2(20, 20),
                Color.White));
        }
    }
```

**Comment by prime31** [comment]
Those aren’t scaling artifacts at all. That looks like you are using Net Core and not Net 471

**Comment by xdrie** [comment]
I am using .Net Core, how does this affect rendering/cause this issue? is there a bug thread anywhere I can look at?

Thanks.

**Comment by prime31** [comment]
There is no official MG Net Core release and FNA strongly warns against using Net Core. I personally dont touch it so you are on your own trying to find the bugs it introduces.
