### ISSUE TITLE
Triggers not returning true when pressed

### ISSUE THREAD

**Issue by Saliken** [prime31/Nez#58]
When using Input.gamePads[0]isButtonDown(Buttons.LeftTrigger) the return value is always false. Initially I was using the VirtualButton setup and found that my triggers were never returning true. Then I tested just the basic isButtonDown and found that to also never return true. I then went to a pure monogame project and tried isButtonDown and it worked fine.

I tried setting a breakpoint right after the call to Monogame's isButtonDown and checking the value and it is returning false. I did the same in my own project and it returned true. 

Also the same problem exists for the other checks (isButtonPressed, etc).

**Comment by prime31** [comment]
I'm not sure what to tell you here. Nez doesn't actually provide anything other than a wrapper around MonoGames input. The raw data all comes from the standard MonoGame input methods. Perhaps ensure you have the same MonoGame DLL version in both projects. You can also do some testing by unplugging then replugging your controller, access the plain MonoGame input methods directly, check to see if MonoGame thinks the controller is connected, etc.

**Comment by Saliken** [comment]
Alright after much debugging I found that the culprit was indeed the monogame dll used in the Nez project. I substituted it for a DLL built from a separate project and the triggers began working again. Not sure why the first DLL didn't work but I'm glad this other one does.

**Comment by Saliken** [comment]
Alright, after a whole lot of debugging it turns out that the bug is in the CrossPlatform project specifically. When using the CrossPlatform version the triggers will not register as having been pressed on the isButtonDown() method. They still return a value from 0 - 1 though so I'll find a way of working with that in my Nez project for the time being.

**Comment by prime31** [comment]
That's an odd one! Make sure you report it on the MonoGame issue tracker. They are getting real close to the next release and a big like that isn't a good way to release.
