### ISSUE TITLE
Content Importer not working

### ISSUE THREAD

**Issue by bayganik** [prime31/Nez#583]
downloaded this repository 4/27/2020 
It broke all my apps, since it no longer imports any Texture2D or fonts or ….
Content.Load<Texture2D> complains that xnb file does not exist.  This was not the behavior before.  Did you make a change?

**Comment by xdrie** [comment]
see [this release](https://github.com/prime31/Nez/releases/tag/0.10.0):

the pipeline importer loaders were removed in favor of runtime loaders. use the new methods in `NezContentManager` to load your assets, such as `LoadTexture` and `LoadBitmapFont`.

**Comment by bayganik** [comment]
That did the trick.  Thank you for the reply.  I had not downloaded the repository for a few months.

**Comment by xdrie** [comment]
Great! Glad to hear that it worked okay.

**Comment by dericatienza** [comment]
Does this mean we don't need to build our assets into XNB files anymore with MGCB? We just need to set them to copy on build?
