### ISSUE TITLE
File path for tileset source image embedded in .tsx is incorrect when .tsx file is not in the same folder as .tmx

### ISSUE THREAD

**Issue by hershicon** [prime31/Nez#585]
When using `Content.LoadTiledMap()` a runtime error occurs when the tileset file (.tsx) and tileset source image (.png) are not in the same folder as the tile map (.tmx file).  An example Content folder that fails:

Content/tile-maps/
__tilemap.tmx
__tiles/
____tileset.tsx
____tileset.png

This error occurs here:
https://github.com/prime31/Nez/blob/6dd216b12846e4ad4a1d3f5ed852231c74e2d0c7/Nez.Portable/Assets/Tiled/Runtime/TiledMapLoader.cs#L161

 The tmx folder path is being passed (tmxDir) when the tileset image location is actually relative to the tsx file.  So that line should be replaced with:

`string tsxDir = Path.GetDirectoryName(source);`
`var tileset = new TmxTileset().LoadTmxTileset(map, xDocTileset.Element("tileset"), firstGid, tsxDir);`

I have made this change in my code and it works.  I can make a pull request for this change if that is helpful, just keep me updated!

**Comment by xdrie** [comment]
Yes, please submit a PR so the change can be reviewed.
