### ISSUE TITLE
Runtime Inspector not removing components.

### ISSUE THREAD

**Issue by vicdotexe** [prime31/Nez#586]
If I add a component to an entity during runtime, the inspector updates and will add it to the observable list, which is great. However, when I remove the component, it lingers in the inspector even though the component has been removed from the entity.

**Comment by prime31** [comment]
This is by design. Inspectors are loaded and cached so that they dont have to constantly poll all the components on an Entity just for a debug inspection utility. You could make it poll if you prefer so that it can catch adds and removes but it would be at the expense of performance.

**Comment by vicdotexe** [comment]
Oh, that makes sense. Thank you for replying. Sent from Mail for Windows 10 From: prime31Sent: Wednesday, May 6, 2020 1:58 PMTo: prime31/NezCc: vicdotexe; AuthorSubject: Re: [prime31/Nez] Runtime Inspector not removing components. (#586) This is by design. Inspectors are loaded and cached so that they dont have to constantly poll all the components on an Entity just for a debug inspection utility. You could make it poll if you prefer so that it can catch adds and removes but it would be at the expense of performance.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
