### ISSUE TITLE
tooltip has a problem

### ISSUE THREAD

**Issue by esengine** [prime31/Nez#587]
When I used ToolTip to bind to the Window control, I noticed that dragging the Window would cause the ToolTip to appear incorrectly. The coordinate position should have changed but the conversion was incorrect

**Comment by esengine** [comment]
![GIF](https://user-images.githubusercontent.com/18465053/81544594-50f24700-93aa-11ea-8fac-e2e34449363e.gif)

Another question I have is how can I have only one tooltip, as you can see in my gifs with multiple tooltips blocking each other

**Comment by sachdevs** [comment]
Looks to me like this was not set correctly on your canvas. https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Renderables/UICanvas.cs#L22

2. Take a look at tooltip manager https://github.com/prime31/Nez/blob/master/Nez.Portable/UI/Utils/TooltipManager.cs#L221

**Comment by esengine** [comment]
@sachdevs 
Yes, I did. Thank you
