### ISSUE TITLE
Add method to set the collision layer in the TiledMapMover

### ISSUE THREAD

**Issue by wacharlb** [prime31/Nez#591]
Currently there isn't a way to set the CollisionLayer in the TiledMapMover once it's created. Also, using the default constructor would create a TiledMapMover without a CollisionLayer being set, and this could not be changed since the CollisionLayer field is readonly. This PR is to request a method be added to the TiledMapMover to set the CollisionLayer after the TiledMapMover component has been created. This is will allow the ability to set the CollisionLayer if the TiledMap changes rather than removing and adding a new TiledMapMover component. Also, this would be solve the problem of loading a new TileMap with a CollisionLayer having different name than the previous TiledMap.

**Comment by xdrie** [comment]
This is now fixed in #595.
