### ISSUE TITLE
TiledMapRenderer has large performance dip when SetLayersToRender isn't used

### ISSUE THREAD

**Issue by hershicon** [prime31/Nez#594]
For some reason, frame rate drops by a large amount when SetLayersToRender isn't explicity called.

For example:
             `TiledMapRenderer tiledMapComponent = new TiledMapRenderer(tiledMap, "ground");`

Has large performance issues while
            `TiledMapRenderer tiledMapComponent = new TiledMapRenderer(tiledMap, "ground");
            tiledMapComponent.SetLayersToRender("ground");`

runs well, even though the tile map only has 1 layer.

**Comment by prime31** [comment]
the only difference between the two code paths is that all layers are looped over vs just the layers you specify. You'll need to profile to see where your slowdown is coming from.

```
		public override void Render(Batcher batcher, Camera camera)
		{
			if (LayerIndicesToRender == null)
			{
				TiledRendering.RenderMap(TiledMap, batcher, Entity.Transform.Position + _localOffset, Transform.Scale, LayerDepth);
			}
			else
			{
				for (var i = 0; i < TiledMap.Layers.Count; i++)
				{
					if (TiledMap.Layers[i].Visible && LayerIndicesToRender.Contains(i))
						TiledRendering.RenderLayer(TiledMap.Layers[i], batcher, Entity.Transform.Position + _localOffset, Transform.Scale, LayerDepth, camera.Bounds);
				}
			}
		}
```

**Comment by hershicon** [comment]
I found the issue, the 2 paths are not exactly the same because if LayerIndicesToRender is null, the camera.Bounds are not passed into RenderMap (like it is in RenderLayer) , and thus they aren't used. I assume the function that is eventually called without the camera.Bounds will try to render the whole map, not just the part in view of the camera, causing the slowdown.  I've have tested it on my end, and fixed it, I will create a PR sometime today or tomorrow!
