### ISSUE TITLE
BoxCollider constructor not setting local offset length

### ISSUE THREAD

**Issue by samfemboeck** [prime31/Nez#597]
This is not a showstopper since you can SetLocalOffset() to calculate the offset length. It did cost me a significant amount of time to figure out the problem though. The BoxCollider constructor only sets the offset without calculating the offset length:

`public BoxCollider(float x, float y, float width, float height)
		{
			_localOffset = new Vector2(x + width / 2, y + height / 2);
			Shape = new Box(width, height);
		}
`

When not explicitly calling SetLocalOffset() the offset calculation is wrong after rotation.

**Comment by xdrie** [comment]
I'm not understanding exactly what you mean. Could you give more context on how you're calling the constructor and how the behavior differs from what you expect?  Sample code would be excellent.
