### ISSUE TITLE
TextField Text Font Size

### ISSUE THREAD

**Issue by JPisaBrony** [prime31/Nez#600]
Is it possible to set the size of the text in the TextField?

creating a TextField like so
```
var table = Stage.AddElement(new Table());
table.Defaults().SetMinWidth(300).SetMinHeight(100);
table.SetFillParent(true).Center().Top().PadTop(10);
var skin = Skin.CreateDefaultSkin();
var text_box = new TextField("test", skin);
table.Add(text_box);
```
will create a TextField with small text
![box](https://user-images.githubusercontent.com/3083689/83855179-5313a100-a6dd-11ea-88ed-9d844e5d48b4.png)

I have tried setting the FontSize like so
```
TextFieldStyle style = skin.Get<TextFieldStyle>();
style.Font.FontSize = 100;
var text_box = new TextField("test", style); 
```
or
```
text_box.GetStyle().Font.FontSize = 100;
```
but neither seem to change the size of the text inside the TextField

**Comment by AnotherEpigone** [comment]
A similar (but easier to fix) issue seems to exist with TextButton/ImageTextButton. No apparent way to set the font scale on the label inside.

The buttons are easy to fix by adding a scale to the button styles. TextField though doesn't seem to have font scaling.
