### ISSUE TITLE
Using Tiled Isometric Maps

### ISSUE THREAD

**Issue by newtonrd** [prime31/Nez#602]
I've been struggling with trying to get Tiled maps in an isometric view to display correctly. The TiledMap itself is easy enough to render using 

```csharp
var tiledMapEntity = CreateEntity("tiled-map-entity");
var tiledMapRenderComponent = tiledMapEntity.AddComponent(new TiledMapRenderer(map));
```
But when viewing this as part of the scene with the default camera, it's drawing the map in the cartesian place. Is this fixed by updating the camera of the scene or something else?

How the map is drawn:
<img width="564" alt="Screen Shot 2020-06-08 at 11 49 13 AM" src="https://user-images.githubusercontent.com/1395943/84057940-15817300-a97e-11ea-8e04-56941f1396a1.png">

How the map should appear:
<img width="771" alt="Screen Shot 2020-06-08 at 11 50 14 AM" src="https://user-images.githubusercontent.com/1395943/84058098-5aa5a500-a97e-11ea-8bba-213359a3bb94.png">

Thanks!

**Comment by prime31** [comment]
By default, Tiled maps are rendered top-left to bottom-right. If you need custom sorting for your rendering you have to do the rendering yourself in your own component.

**Comment by tobischw** [comment]
I am confused... I thought this was addressed in a PR a long time ago? https://github.com/prime31/Nez/issues/124 I am running into the same issue and wondering if there's an existing solution before I write my own.

**Comment by dericatienza** [comment]
Hi @prime31. Can confirm that isometric tiles are indeed not supported at the moment? Cause I'm thinking of implementing it myself if that's the case and maybe raise a pull request if it works out.
