### ISSUE TITLE
Camera not correctly culling scaled up TiledMap

### ISSUE THREAD

**Issue by frzyc** [prime31/Nez#603]
![unknown](https://user-images.githubusercontent.com/1754901/84580784-1bc18600-ada8-11ea-844d-119872dbdd67.png)
I have a scaled up TiledMap `tiledMapRenderer.Transform.Scale = new Vector2(5);`
with a `FollowCamera`.  The tiles are culled assuming the unscaled dimensions of the TiledMap.

I quickly remedied this issue by adding an override to`Nez.Tiled.TmxMap.WorldToTilePositionX`:
```
public int WorldToTilePositionX(float x, float scaleX, bool clampToTilemapBounds = true)
{
	var tileX = Mathf.FastFloorToInt(x / (TileWidth* scaleX));
	if (!clampToTilemapBounds)
		return tileX;
	return Mathf.Clamp(tileX, 0, Width - 1);
}
```

**Comment by frzyc** [comment]
This also means that any of the `WorldToTilePosition` or `TileToWorldPosition` would be wrong as well, since it does not consider the transformation in terms of Scale nor Position

**Comment by prime31** [comment]
Scaling a tilemap isnt a very "general purpose" strategy. I would suggest adding your own extension methods that accept scale parameters to cover your use case. The tiled map classes have no concept of presentation scale so it doesnt feel right to shoehorn them in.

**Comment by witlock** [comment]
I do it too!

**Comment by prime31** [comment]
Well then let’s whip up some extension methods and get a PR in if there are more than one of you!

**Comment by frzyc** [comment]
I guess the initial reason why I raised this was that this feature partially works. We can use transform on the `TiledMapRenderer` to scale up the tile map, the collision and the tiles are scaled/transformed properly. The issue is that most of the translations between world and tile position are not considerate of the transform.  It seems weird to allow us to transform the tilemap, but then the system around it don't translate it properly. Would mislead a lot of new developers like me to vigorously checking their own code in confusion.

**Comment by frzyc** [comment]
Guess I'll get started on a PR, since I've already looked at the code in the area. Things get really weird when rotation is added to the mix:
![image](https://user-images.githubusercontent.com/1754901/84696954-4aac3900-af1b-11ea-8d94-8b2475761e3d.png)
