### ISSUE TITLE
Null error in EffectResources.cs

### ISSUE THREAD

**Issue by RastaCow** [prime31/Nez#61]
Started a new project and started following your Getting Started video on your YouTube channel. At the point where you remove all the default stuff in Monogame such as the LoadContent and such. I run the project and I get a Null error in line 79 of EffectResources.cs  Just wondering what the fix was. Here is where the error is.

```c#
internal static byte[] getMonoGameEmbeddedResourceBytes( string name )
		{
			#if FNA
			name = name.Replace( ".ogl.mgfxo", ".fxb" );
			#endif

			var assembly = ReflectionUtils.getAssembly( typeof( MathHelper ) );
			using( var stream = assembly.GetManifestResourceStream( name ) )
			{
				using( var ms = new MemoryStream() )
				{
                     ///here
					stream.CopyTo( ms );
					return ms.ToArray();
				}
			}
		}
```

**Comment by prime31** [comment]
Stick a breakpoint in the method and see which shader it is trying to load. You will want to make sure that you add that shader in your projects Content/nez/effects folder. All the compiled shaders are available in the DefaultContent folder at the root of the repo. 



On Jul 11, 2016, at 7:10 PM, RastaCow <notifications@github.com> wrote:

Started a new project and started following your Getting Started video on your YouTube channel. At the point where you remove all the default stuff in Monogame such as the LoadContent and such. I run the project and I get a Null error in line 79 of EffectResources.cs Just wondering what the fix was. Here is the error
`internal static byte[] getMonoGameEmbeddedResourceBytes( string name )
{
#if FNA
name = name.Replace( ".ogl.mgfxo", ".fxb" );
#endif

        var assembly = ReflectionUtils.getAssembly( typeof( MathHelper ) );
        using( var stream = assembly.GetManifestResourceStream( name ) )
        {
            using( var ms = new MemoryStream() )
            {
                stream.CopyTo( ms );
                return ms.ToArray();
            }
        }
    }`

**Comment by RastaCow** [comment]
It says it is looking for "Microsoft.Xna.Framework.Graphics.Effect.Resources.SpriteEffect.ogl.mgfxo"

I don't think that is part of Nez?

**Comment by prime31** [comment]
That is not part of Nez. That is the built-in MonoGame SpriteEffect. That is very, very odd that it is not present. Is your MonoGame install up to date?

One thing you can do to check to make sure the SpriteEffect exists in the MonoGame assembly is to stick the following right before the first using statement:

```csharp
foreach( var r in assembly.GetManifestResourceNames() )
      Debug.log( "resource name: {0}", r );
```

Let me know what the output of that is and it may have a clue.

**Comment by RastaCow** [comment]
```
Log: resource name: Microsoft.Xna.Framework.Graphics.Effect.Resources.AlphaTestEffect.dx11.mgfxo
Log: resource name: Microsoft.Xna.Framework.Graphics.Effect.Resources.BasicEffect.dx11.mgfxo
Log: resource name: Microsoft.Xna.Framework.Graphics.Effect.Resources.DualTextureEffect.dx11.mgfxo
Log: resource name: Microsoft.Xna.Framework.Graphics.Effect.Resources.EnvironmentMapEffect.dx11.mgfxo
Log: resource name: Microsoft.Xna.Framework.Graphics.Effect.Resources.SkinnedEffect.dx11.mgfxo
Log: resource name: Microsoft.Xna.Framework.Graphics.Effect.Resources.SpriteEffect.dx11.mgfxo
```


Im 99% sure I have the latest version of Monogame. I will update then get back to you

**Comment by prime31** [comment]
You have the DirectX version of the MonoGame SDK! If you start with the DesktopGL template it will give you the OpenGL version, which is what Nez requires.

**Comment by RastaCow** [comment]
That did it! Thank you very much!

**Comment by jbhaywood** [comment]
I ran into this exact error. Maybe the documentation can be more clear? Right now it says, "...the platform of your project doesnt matter.", which doesn't appear to be true.  I had started with a "MonoGame Window Project", but it sounds like Nez doesn't work with that template. You need to use "MonoGame Cross Platform Desktop Project".
