### ISSUE TITLE
Entity to Json outdated/broken?

### ISSUE THREAD

**Issue by MythicalMarsh** [prime31/Nez#616]
I might be missing something but, writing an entity to json and then trying to re-create the entity breaks even if it doesn't have any components, am I doing it wrong? 
![2020-07-30 12_48_03-Window](https://user-images.githubusercontent.com/63443278/88944384-0a9edc80-d263-11ea-99af-da7d2dc5e924.png)
![2020-07-30 12_48_19-Window](https://user-images.githubusercontent.com/63443278/88944385-0b377300-d263-11ea-8c9f-365470d37b60.png)
![2020-07-30 12_50_19-Window](https://user-images.githubusercontent.com/63443278/88944597-4d60b480-d263-11ea-9298-edbe8b63ab49.png)
this gave me the same error, I know it has to do with the transform but seems like it should work out of the box considering its one of the things shown in the JSON Read-me but help would be appreciated on how to serialize an entity with its components and de-serializing it.

**Comment by xdrie** [comment]
Could you provide a sample project or source to reproduce? I could look at it for you.
