### ISSUE TITLE
Tilemap rendering artifacts

### ISSUE THREAD

**Issue by thetestgame** [prime31/Nez#618]
The tiled map renderer is introducing weird extra pixels on the sides of certain tiles and outright not rendering some on others. Here is a side by side from Tiled to Nez

**Tiled**
<img src="https://i.gyazo.com/df6c8f3ae3f9b31c0d40fd55af80f836.png" width="400">

**Nez**
<img src="https://i.gyazo.com/dc552972cd115afe4fb13e7b0e72b219.png" width="400">

It seems to only effect the second tile map layer as well. If I isolate out to just that layer you can see it more clearly
<img src="https://i.gyazo.com/d4a500bc1ddc86bc429eb6a8a7f6c329.png" width="400">

Is this a known issue and if so what is the current work around?

**Comment by prime31** [comment]
That looks like pretty standard texture bleed. Give your tilemap at least a 1 pixel margin and it usually solves that.

**Comment by thetestgame** [comment]
I ended up downgrading the version of monogame I was using and it fixed its self. I'll try that if I need to go need to go back to the latest.

**Comment by MPWrobel** [comment]
To fix this issue you just need to set PreferHalfPixelOffset to true for XNA compatibility
[https://docs.monogame.net/api/Microsoft.Xna.Framework.GraphicsDeviceManager.html#Microsoft_Xna_Framework_GraphicsDeviceManager_PreferHalfPixelOffset](url)

**Comment by MPWrobel** [comment]
Or even better solution would be to change one line in Batcher.cs `PrepRenderState() `function from `#if FNA` to `#if FNA || MONOGAME3_8` and than adding `MONOGAME3_8` symbol to defined symbols in `Nez.csproj` project settings

**Comment by prime31** [comment]
> Or even better solution would be to change one line in Batcher.cs `PrepRenderState() `function from `#if FNA` to `#if FNA || MONOGAME3_8` and than adding `MONOGAME3_8` symbol to defined symbols in `Nez.csproj` project settings

Nez doesn’t jump on new MonoGame releases right away. They come once every 3 years, are often buggy and don’t offer anything new/exciting so Nez waits for things to stabilize before bothering. 

Besides, we have FNA support which has completely solid monthly releases and never required any odd hacks to get working.
