### ISSUE TITLE
GStreamer based Video rendering as IDrawable

### ISSUE THREAD

**Issue by CAMongrel** [prime31/Nez#624]
Hi and thanks for your great library!

I've implemented simple video playback using gstreamer-sharp with custom pipelines outputting raw pixel data which I write to Texture2Ds. 
I only need it in Nez.UI for a fullscreen video player, but I still wanted to be as flexible as possible, so my original idea was to create a GstreamerDrawable derived from IDrawable and use the Batcher to efficiently draw the textures on screen. This would allow me to place the video on basically everything.
This actually worked great until I realized that IDrawables have no lifecycle and thus don't know when to release the underlying gstreamer resources.

What would be your suggestion for a better alternative that is equally flexible as an IDrawable? Or is there none?
Creating a new UI element seems a bit overkill, but would probably solve the lifecycle issues.

Thanks for your suggestions and keep up the good work.

**Comment by prime31** [comment]
I personally would just use FNA's video player. It is already pretty well battle tested and works quite well.

**Comment by CAMongrel** [comment]
Thanks for your suggestion, but that wouldn't really solve the problem of the lifecycle with regards to Nez.UI, would it?

I can't find any kind of event or method that gets invoked when a UI element is no longer visible on screen, regardless where it is located in the view hierarchy. I guess I could just roll my own event that is propagated through the hierarchy when any parent above is removed, I just don't want to reinvent anything.
