### ISSUE TITLE
Nez not compile due to call in Matcher to "componentBits" which does not exist

### ISSUE THREAD

**Issue by bayganik** [prime31/Nez#628]
public bool IsInterested(Entity e)
		{
			return IsInterested(e.componentBits);
		}

Matcher has the above method with ref to a field that does not exist in Entity and has incorrect case spelling.  This causes the DLL not to compile.  Can you fix?  There are 2 references to it.

**Comment by prime31** [comment]
Matcher and the old ECS don’t exist anymore in Nez. They were removed a couple months back.
