### ISSUE TITLE
Link to Monocle Engine in readme is dead

### ISSUE THREAD

**Issue by MrCull** [prime31/Nez#637]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://bitbucket.org/MattThorson/monocle-engine

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by xdrie** [comment]
Unfortunately it looks like all the author's old links to that repo are dead. Mirrors do exist but the original seems to be gone. we should probably just change the link to text.
