### ISSUE TITLE
Raycasts not colliding correctly when inside bounding box of non-rectangular shape

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#64]
Hi,
I've found what appears to be a bug in how raycasts collide with non-rectangular shapes.  I have prepared a gist of my example [here](https://gist.github.com/piedoom/828fef9f8662c8ac62c8ba3c7295e916).

I'm drawing a raycast at the bottom of a box as an example.  As the picture illustrates, the distance between this raycast and the rectangular collider is 31 pixels, which looks correct.

![image](https://cloud.githubusercontent.com/assets/8846211/16849749/f394f5b8-49c9-11e6-939c-358cdb9f3f43.png)

If we move our raycast to a non-rectangular shape, the distance is once again correct.  However, this only works when the raycast origin begins outside of the bounding box for the non-rectangular collider.

![image](https://cloud.githubusercontent.com/assets/8846211/16849786/268db54a-49ca-11e6-8cd3-c7be5a1e0f83.png)

Once we get inside of the bounding box, the distance no longer updates because the raycast is not sensing any collisions.  This final picture shows our raycast distance that should be no longer than a few pixels stuck at 39.5.

![image](https://cloud.githubusercontent.com/assets/8846211/16849838/52d7d5e0-49ca-11e6-8419-523e45fa5063.png)

The same effect is true for the circle collider.

I am using the version as of commit c559d766cd48c10507a480e92213f4a73fbaae28

**Comment by prime31** [comment]
So, this is technically correct behavior but now that I think about it some more it probably shouldn't be. There is a settings `Physics.raycastsStartInColliders` that in it's current state when false (the default) if a linecast starts in the colliders bounds it will disregard the collider as a collision candidate. It makes a lot more sense for that check to not be on the Colliders _bounds_ but instead be on the _actual Collider_ itself. The downside to that is that a point-in-polygon test is way more expensive than a point-in-box test.

**Comment by piedoom** [comment]
Thanks for the info - I'm curious - is there a similar setting for doing a `boxcastBroadphase`?  I'm having an issue on slopes with it (that I'm pretty sure is my error) but before I continue I just wanted to make sure I wasn't missing something important.
