### ISSUE TITLE
Aliasing/jitter on moving sprite with follow camera

### ISSUE THREAD

**Issue by dresswithpockets** [prime31/Nez#643]
Hey, I've got an animated sprite thats moving across the screen and the camera is following it. I have a fixed timestep, I'm using a subpixel remainder for both the player (that moving sprite) and the camera, and I'm using the default material (which uses PointClamp by default, right?). I'm also using a ShowAllPixelPerfect screen resolution policy. I believe I've accurately followed the advice of various other posts here, like from https://github.com/prime31/Nez/issues/142#issuecomment-258731168

Applying the player movement with that subpixel remainder:

```cs
var motion = velocity * Time.DeltaTime;
velocityRemainder.Update(ref motion);
collider.CollidesWithAny(ref motion, out _);

Position += motion;
```

and the camera:

```cs
if (cameraShouldFollowPlayer)
{
    var camMotion = (Position - Scene.Camera.Position) * (1f - Mathf.Pow(0.01f, Time.DeltaTime));
    cameraMotionRemainder.Update(ref camMotion);
    Scene.Camera.Position += camMotion;
}
```

and an example of this happening:

![example](https://i.imgur.com/040EEHm.gif)

The jitter of course isnt present if i lock the camera directly to the player with no motion smoothing - however, the sprite is still not correct - so this may be more than one problem:

```cs
Scene.Camera.Position = Position;
```

in-game:

![image](https://user-images.githubusercontent.com/4009005/100530100-1071e380-31ab-11eb-8e26-07d29b781502.png)

what its supposed to look like:

![image](https://user-images.githubusercontent.com/4009005/100530144-778f9800-31ab-11eb-923e-5d2438663556.png)

Anything to point me in the right direction here would be much appreciated.

**Comment by xdrie** [comment]
See this patch:

https://github.com/prime31/Nez/issues/571#issuecomment-619464856

If you're using .NET 5, this is also needed. In that case I would just remove that check for ".NET Core" and always set it to true. Let me know if that solves your problem.

**Comment by Nyaaboron** [comment]
I had the same problem but I fixed mine by increasing the resolution and then zooming in the Camera:

First, I increased my resolution from 400x240 to 800x480 in the Game1 constructor.
`Scene.SetDefaultDesignResolution(800, 480, policy);`

Since increasing the resolution makes the pixel art small, you can increase back the size by zooming in the camera using `Camera.SetZoom()`

**Comment by dresswithpockets** [comment]
> 
> 
> See this patch:
> 
> [#571 (comment)](https://github.com/prime31/Nez/issues/571#issuecomment-619464856)
> 
> If you're using .NET 5, this is also needed. In that case I would just remove that check for ".NET Core" and always set it to true. Let me know if that solves your problem.

Sorry for taking so long to get back. This is what solved my problem.
