### ISSUE TITLE
Why does LoadSpriteAtlas only work with uncompiled png's?

### ISSUE THREAD

**Issue by phxvyper** [prime31/Nez#644]
`NezContentManager.LoadSpriteAtlas` expects a texture adjacent to the sprite atlas, and it must be a png. Why doesnt it use the content manager for this and just get the texture with the same asset name? The justification for this isnt immediately obvious to me.

I've accomplished this in a hacky and naive way, but it works: https://github.com/phxvyper/Nez/blob/master/Nez.Portable/Assets/NezContentManager.cs#L176

```cs
public SpriteAtlas LoadSpriteAtlas(string name, bool premultiplyAlpha = false)
{
	// ...
	var atlasData = SpriteAtlasLoader.ParseSpriteAtlasData($"Content/{name}.atlas");
	var atlas = atlasData.AsSpriteAtlas(ReadAsset<Texture2D>(name, null));
	// ...
	return atlas;
}
```

**Comment by prime31** [comment]
Nez dumped all support for the pipeline tool. It serves no useful purpose and is just a legacy artifact of XNA.

**Comment by phxvyper** [comment]
I don't think that's true though. Pre-processing and compiling textures, audio, level data, etc, is extremely useful and reduces the responsibility of the game at runtime, and even better: load times. Why would you drop support for this all-together? I must be missing something; I don't consider this feature legacy at all.

**Comment by prime31** [comment]
For the types of games being made with MonoGame there is no point to prebaking data. In most cases it increases file sizes significantly all to gain an unmeasurably small increase in load time and the quality loss that comes with lossy compression.

**Comment by phxvyper** [comment]
That really seems unfounded. What kinds of games are you talking about? And, yes, the file sizes will increase as a result of doing some form of prepossessing half of the time, that's kind of the point so that you have that data cached on the first go in exactly the format you want. Also, I never mentioned lossy compression. Pre-processing data just means that I'm manipulating it in some way that makes my interaction with the data on first-run at runtime more pleasant.

I think the disconnect here is about the justification to intentionally stop supporting Content Pipeline all together, even though you still integrate with it directly, and having to completely stop supporting it is *more of a headache* than supporting it. Like, no one is forcing you to use the specific features in Content Pipeline that enable preprocessing, in fact - supporting this feature wouldn't mean that everyone would have to use Content Pipeline; but having that option available to developers without any hassle really is a no brainer. Functionally, `LoadSpriteAtlas`, and others, would work identically to how they does now, except it wouldn't require the adjacent file to be a PNG, and it would be process-agnostic.

Removing support for a future that developers use and have a genuine justifiable use for seems really unfounded, especially if the only justification is a biased expectation about the "kinds of games" made in MonoGame.

I'd be happy to PR plain old support for Content Pipeline into the rest of the helper functions for loading content in the `NezContentManager`, and anywhere else thats key.

**Comment by prime31** [comment]
If you really want to use the content pipeline I would recommend just subclassing ContentManager. Nez itself has moved away from it and will continue to move further away from it in the future so that it will be able to work with a couple up-and-coming MG/FNA successors which both drop the content system entirely.

Pre-processing data is a perfectly fine thing to do, but it most definitely does not need to use the horrible Pipeline Tool or the ancient `xnb` file types to do so.

**Comment by dresswithpockets** [comment]
Alright, then.

Though, to be clear, I'm not advocating for the use of the Pipeline UI tool - which i agree is absolutely awful. There are tools like Nopipeline that remedy working with ContentPipeline without that awful UI.

**Comment by prime31** [comment]
I just can't come up with any reason at all to use xnb files. The entire system top to bottom is steeped in XNA legacy and was never fully fleshed out even back when it was fresh. The file format and included legacy XNA reader/writer API has no advantages at all compared to just having a 100% separate asset backing system. A simple Makefile and custom file readers is a far better solution imo.

**Comment by dresswithpockets** [comment]
You don't need to use the default processors, though; Like, the file type isnt really correlated to the ContentPipeline, it just so happens that those types are shipped with XNA et al. I can make my own Texture2D importer & processor if i so desire, and when i need that to happen i will do that - but for now the defaults work fine.

As for advantages; the advantage is that its already there and you don't have to make it yourself. No need to reinvent the wheel if you cant necessitate a that new wheel. A makefile that processes the images for me is not much different from having an NPL config and an mgcp target that results in the same desired output. Makefiles are overkill when the alternative does exactly what you want with less effort.

**Comment by prime31** [comment]
To each their own. After having written a dozen or so processors using the XNA API and maintaining them for 5+ years it was a massive relief to fall back to a makefile and just load my data without going through `Content` class at all.

**Comment by xdrie** [comment]
@dresswithpockets if you really want to use the old pipeline loaders, you can grab them from the commit history, they'll in all likelihood continue to work just fine. I was using them in my fork of Bed recently with no issues.
