### ISSUE TITLE
Nez Tiled with MonoGame 3.8

### ISSUE THREAD

**Issue by martinmaxk** [prime31/Nez#647]
I recently upgraded my project to MonoGame 3.8.
When I try to build my tiled maps (.tmx files) I get an error
"Could not load file or assembly System.Drawing.Common, Version=4.0.0.1"

This is inside TiledMapProcessor.cs. It seems .Net Core doesn't play nice with System.Drawing. 

I have installed Microsoft.Windows.Compatibility package in both the pipeline tool and my project. It does not work. I have tried creating a new pipeline v. 3.8 for tiled and build a new .dll, doesn't work. Have you experienced this before? Do you have any idea how to resolve this?

Seems similar to this issue:
https://community.monogame.net/t/upgrading-a-3-7-pipeline-extension-to-3-8-some-issues/12811/2

**Comment by prime31** [comment]
Nez dropped all Pipeline extensions over a year ago. Tiled maps are now loaded at runtime.

**Comment by dericatienza** [comment]
Correct me if I'm wrong, but wouldn't that mean the TMX files would be editable after build? What does this mean for the release build in terms of other assets? Will our PNG files be exposed?

**Comment by prime31** [comment]
All of your files are shipping with your game. It doesn’t matter what format they are in. If a user really wants to edit them they most certainly can.

**Comment by redthing1** [comment]
@dericatienza What prime said above me, and in addition it is quite trivial to "decompile" XNB assets. There's no point worrying about "protecting" data. Embrace it as a feature.

**Comment by dericatienza** [comment]
Yeah I believe you are right. Other than that though, is there a reason that Nez now encourages reading in raw TMX files, or any other asset files for that matter, and not XNB files?

**Comment by redthing1** [comment]
The pipeline is old, the pipeline tool sucks, and is a hassle. It's just simpler and easier to not rely on them.
