### ISSUE TITLE
Problems with ImGui initialization

### ISSUE THREAD

**Issue by NavanBethrax** [prime31/Nez#659]
First of all it won't be easy to recreate this error.
I'am using VisualStudio 2017, the NuGet packet for MonoGame.Framework.DesktopGL and a copy of Nez, Nez.ImGui and Nez.Persistence. 

The Monogame project itself is in vb.net but that shouldn't be the source of the problem.
I had to set all projects to .Net Framework 4.7.2 and add a line to the Nez.ImGui.cs file for version missmatch reasons.

`<ItemGroup> 
	    <Reference Include="netstandard" /> 
	</ItemGroup>`

After that Nez worked as intended but if i try to initialize ImGui using:

```
Dim imGuiManager = New ImGuiManager
Core.RegisterGlobalManager(imGuiManager)
```

I get a System.TypeLoadException:

```
System.TypeLoadException ist aufgetreten.
  
HResult=0x80131522
  
Nachricht = Der Typ "Microsoft.Xna.Framework.TextInputEventArgs" in der Assembly "Nez.ImGui, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" konnte aufgrund eines Werttypenkonflikts nicht geladen werden.
  
Quelle = Nez.ImGui
  
Stapelüberwachung:
at Nez.ImGuiTools.ImGuiRenderer.SetupInput() in J:\Users\Username\Documents\Visual Studio 2017\Projects\NEZTemplate\Nez-master\Nez-master\Nez.ImGui\Core\ImGuiRenderer.cs:line 224
at Nez.ImGuiTools.ImGuiRenderer..ctor(Game game) in J:\Users\Username\Documents\Visual Studio 2017\Projects\NEZTemplate\Nez-master\Nez-master\Nez.ImGui\Core\ImGuiRenderer.cs:line 77
at Nez.ImGuiTools.ImGuiManager..ctor(ImGuiOptions options) in J:\Users\Username\Documents\Visual Studio 2017\Projects\NEZTemplate\Nez-master\Nez-master\Nez.ImGui\Core\ImGuiManager.cs:line 57
at NEZTemplate.Game.Initialize() in J:\Users\Username\Documents\Visual Studio 2017\Projects\NEZTemplate\NEZTemplate\Monogame\Game\Game.vb:line 22
at Microsoft.Xna.Framework.Game.DoInitialize()
at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
at Microsoft.Xna.Framework.Game.Run()
at NEZTemplate.Program.Main() in J:\Users\Username\Documents\Visual Studio 2017\Projects\NEZTemplate\NEZTemplate\Monogame\Game\Program.vb:line 8
```

The line that throws the exception is the SetupInput(); call inside ImGuiRenderer(Game game)
The program runs and ImGui gets rendered if i comment out that line. 

![Working without Keyboard Input](https://i.imgur.com/6BMFXtK.png)

Only problem is no keyboard input in ImGui.

**Comment by NavanBethrax** [comment]
Ok i should've waited before posting this issue. Already fixxed it myself. Turns out the newest version of Monogame broke ImGui.
Downgrading to Monogame 3.7.1 fixed the problem.

**Comment by alberteddu** [comment]
@NavanBethrax how did you downgrade? I'm having the same problem, but downgrading to 3.7.1 causes 

>  Object reference not set to an instance of an object. at Nez.Portable/Core.cs:line 157

`Window` is null. I have the feeling I'm missing a step.

**Comment by Tobi-Mob** [comment]
@alberteddu make sure you create the ImGuiManager AFTER the `base.Initialize()`has been called in your Game class.
That should help.

```
    public class Game1 : Nez.Core 
    {
        protected override void Initialize()
        {
            // This will crash
            //var manager = new ImGuiManager();
            //Core.RegisterGlobalManager(manager);
            
            base.Initialize();

            Scene = new DefaultScene();

            // This should work
            var manager = new ImGuiManager();
            Core.RegisterGlobalManager(manager);
        }
    }
```

**Comment by alberteddu** [comment]
@Tobi-Mob thanks, I will try that! At some point I switched to the FNA-nez template which helped, but it's good to know how to solve my original problem.

**Comment by alberteddu** [comment]
@Tobi-Mob unfortunately your suggestion didn't work, although that's probably because I'm doing something else wrong :)

My method looks like this:

```
protected override void Initialize()
        {
            base.Initialize();

            Scene = new EmptyScene();
            
#if DEBUG
            ImGuiManager imGuiManager = new();
            RegisterGlobalManager(imGuiManager);
            imGuiManager.SetEnabled(false);
#endif
        }
```

With monogame.framework.desktopgl/3.7.1.189, it fails with a null `Window` at "Nez/Nez.Portable/Core.cs:line 157". With monogame.framework.desktopgl/3.8.0.1641, it fails with

```
System.TypeLoadException: Could not load type 'Microsoft.Xna.Framework.TextInputEventArgs' from assembly 'Nez.ImGui, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.
   at Nez.ImGuiTools.ImGuiRenderer.SetupInput()
```

I'm not quite sure how to debug this. It's true that the FNA template does work for me, but I really wanted to make this work with monogame.

**Comment by Tobi-Mob** [comment]
@alberteddu 
(Sadly) I am unable to reproduce or find a reason for this error. That "due to value type mismatch"-TypeLoadException also keeps me puzzled, I didn't find any clear explanation when this error is thrown.

I threw a small project together which runs with MonoGame 3.8 / .net 471 and Nez-master-branch.
That just works on my Linux machine.

Here is the project: [ImGuiTest.zip](https://github.com/prime31/Nez/files/7456049/ImGuiTest.zip)
Hope it also works on your machine and helps you to solve this.

![image](https://user-images.githubusercontent.com/69400800/139739745-8b6b2c0a-bc5b-46ef-9e0a-ce6f86017482.png)

**Comment by alberteddu** [comment]
@Tobi-Mob thank you for going out of your way to solve my problem. I really appreciate it.

After seeing your template, I switched all Nez.* references in my project to Nez.MG38.* and it builds successfully now. I'm not quite sure why, but I'm glad it works now! Thanks again.
