### ISSUE TITLE
Bitmapfonts with Nez.

### ISSUE THREAD

**Issue by NullsByte** [prime31/Nez#667]
What tool Does Nez use to create Bitmap fonts and what importer / processor should I use in the mgcb editor?
Can't seem to find any info on the topic.  I use bmfont with extended to generate the font assets.

Any insight is appreciated - Thanks.

**Comment by prime31** [comment]
Nez doesnt use MGCB at all. You can use any program at all that generates bitmap font, that is entirely up to you.

**Comment by xdrie** [comment]
> What tool Does Nez use to create Bitmap fonts and what importer / processor should I use in the mgcb editor?
> Can't seem to find any info on the topic. I use bmfont with extended to generate the font assets.
> 
> Any insight is appreciated - Thanks.

If you’re generating bitmapfonts with BMFont, you can load them at runtime with the `Content.LoadBitmapFont` call.

**Comment by nightblade9** [comment]
For anyone looking for detailed instructions, here's what worked for me:

1) Download BMFont by AngelCode. Yes, it's ancient. It still works. Open it up.
2) Options > Font > Size, set to something like 36, click OK
3) From the check-boxes on the side, select everything from Latin to Latin-Extended-B
4) Options > Save bitmap font as ... > Save it somewhere with a .fnt extension
5) Copy the .fnt file, and the .tga files, somewhere where your Nez code can get it. I don't use the content pipeline, but still put all my game assets in a `Content` directory. In this case, I'd use `Content/Fonts`
6) In your code, call `Nez.Core.Content.LoadBitmapFont("Content/Fonts/Arial-36.fnt")` (or whatever you called it). This returns a bitmap font object, which you can apply to your text, a la `new TextComponent(newFontGoesHere, ...)`
7) Profit
