### ISSUE TITLE
Failed to Create Importer 'TiledMapImporter'

### ISSUE THREAD

**Issue by Aeirex** [prime31/Nez#67]
I have followed the instructions, the references are all set in the Pipeline Tool.
`Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\Seth\Documents\GitHub\Arcane-Engine\Arcane Client\Content\Content.mgcb" /platform:DesktopGL /outputDir:"C:\Users\Seth\Documents\GitHub\Arcane-Engine\Arcane Client\Content\bin\DesktopGL" /intermediateDir:"C:\Users\Seth\Documents\GitHub\Arcane-Engine\Arcane Client\Content\obj\DesktopGL" /quiet" exited with code 4.	Arcane Client`

This errors happen in the Nez Samples too, if the formats are configured to ship to allow us to see a working sample that is not really working either.

**Comment by prime31** [comment]
The error seems to indicate that MGCB can't create the importer which is usually just a case of not having built the Nez.sln to generate the DLL.

What happens when you open the Pipeline Tool and build the Tiled map from there? Often after setting the references you have to close and reopen the Pipeline tool to get it working.

The steps I just followed to test:
- clone --recursive Nez.Samples repo
- open Nez.sln and build it
- open Nez.Samples solution and run the demos

**Comment by Aeirex** [comment]
It is probably a mistake on my part, but it shows the  Tilemap Importer as missing and fails to build them.
![image](https://cloud.githubusercontent.com/assets/1341321/16898834/88537070-4bb0-11e6-9801-15413cd3099d.png)

**Comment by Aeirex** [comment]
I have tried it in Nez Samples and checked Git for any modified files and shows none. What exactly is the TileMapImporter and how do I get it installed? I see it in Nez source-code, but I am not sure how to make it work within the MonoGame Pipeline Tool. The references do not seem to work. Do they have to be fully compiled .DLL and not debug?

**Comment by prime31** [comment]
The TiledMapImporter is in the Nez.Pipeline.dll. It doesn't matter if you use the debug or release DLL. It looks like the Pipeline tool isn't finding it for some reason. Did you try closing then reopening the Pipeline tool? That usually fixes the reference for me with the current released version of the Pipeline tool. Occasionally you have to click the Impoter box and deselect the TiledMapImpoter as well. See if that clears it up.

**Comment by Aeirex** [comment]
Thanks, it is a bug with the Pipeline software and not your code.
