### ISSUE TITLE
Tile collision using polygon colliders made with Tiled's Tile Collision Editor.

### ISSUE THREAD

**Issue by Nyaaboron** [prime31/Nez#675]
Hello, I am making a platformer using Nez. I used a TiledMapMover component to move the player, which allowed the player to collide with tiles in a tilemap layer (and it worked really well). But the problem is that when a player tries to collide with a tile, it collides with the tile itself instead of the tile's polygon collider. 

Here are some pictures to help better understand the problem:

This is how I made the colliders (I emphasized the shape of the colliders with a red pen):
 - Ground Tile
![0](https://user-images.githubusercontent.com/63294460/116960011-3d03bd00-ac6d-11eb-9fcd-6e311678054f.PNG)
 - Ground Tile Left Corner
![4](https://user-images.githubusercontent.com/63294460/116960043-48ef7f00-ac6d-11eb-8340-e3eb91a5c414.PNG)
 - Ground Tile Right Corner
![5](https://user-images.githubusercontent.com/63294460/116960065-5573d780-ac6d-11eb-94aa-81979f9bc6c6.PNG)

 - The TileMap
![1](https://user-images.githubusercontent.com/63294460/116960151-9370fb80-ac6d-11eb-8ada-875f129127ce.PNG)

But this is how the player ended up colliding with the map:
![3](https://user-images.githubusercontent.com/63294460/116960191-ad124300-ac6d-11eb-8f04-716bebc27fc4.PNG)

I digged through the source code for like an hour but I couldn't find anything that would help with this problem.
Though I found this interesting pdf on the internet about [polygon intersections](https://www.bowdoin.edu/~ltoma/teaching/cs3250-CompGeom/spring17/Lectures/cg-convexintersection.pdf) but I can't think of a way to use this to make TiledMapMover.Move() check for tile polygon collisions. pls help ;-;

**Comment by prime31** [comment]
Nez doesn’t support Tiled collusion shapes. The TiledMapMover works only with full tiles and slopes for very fast and efficient collisions. If you want to add support for Tiled’s collision shapes you would need to do that manually.
