### ISSUE TITLE
Thank you for your contribution. I translated it into typescript project

### ISSUE THREAD

**Issue by esengine** [prime31/Nez#684]
It took me nearly half a year to transplant the library to typescript and mark that the project was transplanted from Nez library. But I still want your permission, if you don't, I will turn off the visibility of the project.

I promise to keep open source and follow your license agreement.

https://github.com/esengine/ecs-framework

**Comment by prime31** [comment]
By all means you have my permission. That's a ton of work you did! Well done!

**Comment by xdrie** [comment]
Wow @esengine that actually looks really awesome! Is there some documentation for it?

**Comment by esengine** [comment]
> Wow @esengine that actually looks really awesome! Is there some documentation for it?

In addition to some differences in the initialization of the framework, other methods are kept in sync with NEZ. Most of the methods have the same name. You can use the framework in NEZ way.
