### ISSUE TITLE
Duplicate TargetFrameworkAttribute attribute when using VS Code template

### ISSUE THREAD

**Issue by alberteddu** [prime31/Nez#685]
Hello,
I have been trying to use [the FNA VSCode template](https://github.com/prime31/FNA-VSCode-Template), but I am getting an error:

> Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute

I am following the steps as indicated in the README. The above error happens with the command that is saved on the clipboard (after running `./getFNA.sh`) on MacOS (`nuget restore Nez/Nez.sln && msbuild Nez/Nez.sln && msbuild /t:restore ...`.

It seems no one on the internet is having this problem (with Nez). I am probably forgetting something but I can't find out what.

Thank you for your help.

**Comment by prime31** [comment]
Delete the generated obj folders to clear out the duplicates.

**Comment by alberteddu** [comment]
Thank you for your answer. I have tried what you say (deleted a total of 6 obj folders). I am assuming I have to run the command again, but it fails for the same reason (the obj folders are generated by this command, I suppose).

Possibly the command given by the script is not correct?

> nuget restore Nez/Nez.sln && msbuild Nez/Nez.sln && msbuild /t:restore ProjectName && msbuild ProjectName.sln

**Comment by alberteddu** [comment]
I have tried a few combinations of the command above plus deleting some obj folders, but it failed for a reason or another.
It seems this works:
> nuget restore && msbuild ProjectName.sln

I am getting
> The "MonoGame.Build.Tasks.CollectContentReferences" task could not be loaded from the assembly /Library/Frameworks/MonoGame.framework/v3.0/MonoGame.Build.Tasks.dll.

But at least I am making some progress. :)
Thank you for your help.

**Comment by prime31** [comment]
`MonoGame.Build.Tasks.CollectContentReferences` comes from the MonoGame pipeline tool. if you do not have it installed you can just delete the task entirely from the csproj file

**Comment by alberteddu** [comment]
I see. I really appreciate the time you took for supporting me. Thanks!
