### ISSUE TITLE
ContentGenerator.tt errors

### ISSUE THREAD

**Issue by magruder85** [prime31/Nez#704]
Hello,

I was playing around with the ContentGenerator.tt template and was finding that all of my strings were getting truncated. For example, if my sourceFolders  was "Content/assets", my strings would come out looking like this:

`	public const string Player = @"tent/assets/characters/player.png";
`
I looked at the template and traced it down to this line. 
https://github.com/prime31/Nez/blob/fb93e936d4ba964469c1b7d01124716ffdb9e33d/T4Templates/ContentPathGenerator.tt#L95

It seems that when creating the finalPath, the substring retrieved was 3 characters past my folder. When I changed the code to this:
`
var finalPath = file.Substring( file.IndexOf( sourceFolder ) );
`

My templates were created correctly. I tested this on Windows and Mac, I'd be happy to submit a PR but wanted to verify if this substring shift was intentional before I did so. Let me know. Thank you.

**Comment by Tobi-Mob** [comment]
I think this +3 was used to remove the "..\" for the samples repo.
https://github.com/prime31/Nez-Samples/blob/390fc3ac21636200515ff4a6e42512209edc14b0/Nez.Samples/Shared/ContentPathGenerator.tt#L12

The sample repo has the Generator in a Subfolder, but the recommendet way is the root folder.

So: What you propose seems correct to me.
Your change also works on my linux machine.

**Comment by Tobi-Mob** [comment]
I took you fix and put it into a PR: #706 
Hope you don't mind

**Comment by magruder85** [comment]
Not at all, I appreciate the fix however it comes. Thank you.
