### ISSUE TITLE
Any normal camera demonstration is missing.

### ISSUE THREAD

**Issue by Gavolot** [prime31/Nez#705]
Any normal camera demonstration is missing.

In all other demos, it is simply broken. Whatever I personally try to do with the camera, it doesn't work.

And I just can't solve it, I'm not a graphic engineer.

**Comment by Tobi-Mob** [comment]
There was a discussion on Discord regarding this.
I took an empty Nez/FNA Projekt, slapped the classes from the affected example in there and it looks pretty fine.

https://user-images.githubusercontent.com/69400800/140463378-1f25ea9d-0da1-4053-a122-371bcdb2d6f1.mp4

Here is the whole project which works for me. Maybe that helps:
If you are running on windows, you may have to copy the content of "fnalibs/x64" or " fnalibs/x86" into the output folder to the .exe files
[MyNezFNA.zip](https://github.com/prime31/Nez/files/7480816/MyNezFNA.zip)

**Comment by Gavolot** [comment]
Yes, this works with FNA! Thank you very much! You are my savior!
