### ISSUE TITLE
Console cutting off letters

### ISSUE THREAD

**Issue by sponge** [prime31/Nez#711]
Hi all!

I'm just following the instructions to setup an empty Nez game based on the Monogame template. I had to remove some code for setting up graphics manager in the template, but after removing that the example game compiled successfully and ran. However, the output looked like this:
![image](https://user-images.githubusercontent.com/342347/153773979-b97b2476-97ed-4dcc-b0cc-60a334ab36aa.png)

It looks like the UVs aren't wide enough, and letters like "l" completely disappear. The effect stayed whether I raised the resolution or kept it default. I'm on an GTX 3080TI, driver version 511.65, Windows 11, 1440p display, no DPI scaling or anything like that.

Has anyone else ran into this?

**Comment by prime31** [comment]
That is the typical half pixel offset. Make sure you use the correct csproj file. There is one for MG37, one for MG38, one for FNA and one for FNA with dotnet core.

**Comment by sponge** [comment]
Thanks, that was definitely it! I saw those other projects but just didn't put two and two together with the MG38 solution.
