### ISSUE TITLE
Where is the importers for bitmap font (generated with BMFont)?

### ISSUE THREAD

**Issue by davidgd72k** [prime31/Nez#714]
Hello:

I have a problem: I need load a Bitmap Font generated with BMFont (with your .fnt and .png), but MGCB-Editor say need a default importer to load this file. The problem is that I can't find the .dll for the MGCB-Editor, as it causes the error shown in the image.

![image](https://user-images.githubusercontent.com/59517993/161425572-840c8551-0a0f-403b-917f-31c93669c6f7.png)

Beforehand, thanks.

**Comment by optimo** [comment]
Nez does not use the pipeline - not in a few years. MGCB is used to manage assets to be loaded through the pipeline, but now Nez uses direct loading of asset files.

There are no .dll files here to help with that. If you want to use latest Nez I suggest abandon MGCB and move to direct-loading.

If you search the issues for pipeline you will see some similar questions answered, such as: https://github.com/prime31/Nez/issues/583

And you can see the timeline and how it was removed:
https://github.com/prime31/Nez/search?q=pipeline&type=commits

**Comment by prime31** [comment]
Importers were all nuked many years ago. Everything has been switched to runtime to avoid the pipeline tool entirely.
