### ISSUE TITLE
Is there a roadmap for updating MonoGame 3.8 to 3.8.1?

### ISSUE THREAD

**Issue by willowell** [prime31/Nez#725]
Hello,

MonoGame just released 3.8.1 (https://github.com/MonoGame/MonoGame/releases/tag/v3.8.1, community post: https://community.monogame.net/t/monogame-3-8-1/17786).

Is there a plan / roadmap for updating Nez and the Nez samples to support MonoGame 3.8.1?

Is there anything I can do to help with this update?

**Comment by prime31** [comment]
Is there even anything that needs to get updated? If so and you use MG then feel free to send in a PR. I personally use FNA so I avoid new MG releases like the plague.
