### ISSUE TITLE
Incompatibility for MonoGame and Nez

### ISSUE THREAD

**Issue by TokyoSU** [prime31/Nez#726]
I've followed the tutorial, i need to create a monogame desktop project which is now NET6 but Nez is compiled using NetFramework4.8
(NetFramework 4.7.X for Nez.FNA) im currently weirdedout about why Nez dont follow monogame ?
Well im saying incompatibility but it's only a warning about using netframework with net6.

**Comment by prime31** [comment]
Nez has several csproj files all with different .NET versions. It is also raw source code so you can change the target framework to whatever you want.
