### ISSUE TITLE
[UI] FontScale, Image Scale and size

### ISSUE THREAD

**Issue by witlock** [prime31/Nez#76]
Why does scaling font/image cause an overflow in the parent container?
Everything is shown nicely until I decide to scale the font by **setFontScale** (wrap enabled) which causes the font to wrap in the wrong place and the text goes outside the bounds. Is it intentional that scaling has no effect on the width of the element?
Same thing for image elements. The cell the image is in doesn't care if it's scaled or not it will still act as if the image is the original size.

Is there an extra step I'm missing?

**Comment by prime31** [comment]
Do you have a simple bit of example code that illustrates what you are referring to?

**Comment by witlock** [comment]
`var stack2 = new Stack();
stack2.fillParent = true;

var aTable = new Table();
aTable.setFillParent(true);
aTable.setBackground(new PrimitiveDrawable(Color.Red));

var desc = new Label(item.Description).setFontColor(Color.FromNonPremultiplied(131, 95, 51, 255));
desc.fillParent = true;
desc.setWrap(true);
desc.setAlignment(Align.topLeft);
desc.setFontScale(3);
aTable.add(desc).setAlign(Align.topLeft).setFillX();
stack2.add(aTable).top().left();`

![wrapscale](https://cloud.githubusercontent.com/assets/8792184/17079755/58d6b9c0-5122-11e6-92e3-83a4041a76ca.jpg)

**Comment by witlock** [comment]
Apparently it turns out I should blame the stack?

**Comment by prime31** [comment]
There are definitely some TODO's still present in a couple parts of the UI stuff. This was one of them and it looks like the scale just wasnt taken into account when measuring the string
