### ISSUE TITLE
Any reason Emitter uses a List instead of Delegate.Combine?

### ISSUE THREAD

**Issue by fabienbrooke** [prime31/Nez#78]
https://github.com/prime31/Nez/blob/master/Nez-PCL/Utils/Emitter.cs

**Comment by prime31** [comment]
Why would it use Delegate.Combine? What are the advantages vs the speed and simplicity of managing the delegates manually with a List?

**Comment by fabienbrooke** [comment]
Yeah that's my question. Is it faster to use a list?

On 24/07/2016 1:03 PM, "Mike" <notifications@github.com> wrote:

Why would it use Delegate.Combine? What are the advantages vs the speed and
simplicity of managing the delegates manually with a List?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prime31/Nez/issues/78#issuecomment-234798758>, or mute
the thread

**Comment by prime31** [comment]
Delegate.Combine is a pretty big chunk of code where as List.Add is tiny. For something like this it wouldn't matter too much performance-wise since objects usually only add/remove listeners at their birth/death.
