### ISSUE TITLE
Huge performance decrease

### ISSUE THREAD

**Issue by witlock** [prime31/Nez#80]
All I did was update the version of Nez I was using and now I get ~45FPS with 7 drawcalls with
just a tilemapcomponent and 18 FPS with everything I have enabled.

I can't imagine what I'm doing wrong.
Tried two computers, debug and release builds, different tile maps etc.

After downgrading to a version from earlier this month I'm back to 150 FPS which is much better than 18 FPS.

Am I the only one?
 
![lowfps](https://cloud.githubusercontent.com/assets/8792184/17146856/b35e36be-5368-11e6-862a-ce1ea2733360.PNG)

**Comment by piedoom** [comment]
I just tested on my machine with 27915ae602cacca9dc45bd0dce62a798c7102896 and it's still running smoothly.

**Comment by witlock** [comment]
public override void initialize()
        {
            base.initialize();
            var tiledEntity = createEntity("tiled-map-entity");
            var tiledmap = contentManager.Load<TiledMap>("Maps/demomap");
            var tiledMapDetailsComp = tiledEntity.addComponent(new TiledMapComponent(tiledmap));
            tiledMapDetailsComp.setLayersToRender("grass");
            addRenderer(new DefaultRenderer());
        }

**41 FPS**

**Comment by prime31** [comment]
Oddly enough there were performance *improvements* in the recent commits (albeit minor ones). All performance critical Lists were changed to arrays and the 12 float MonoGame Matrix was replaced by a custom 6 float, 2D version.

**Comment by witlock** [comment]
I should mention the Ninja example runs at 450 FPS and I tried using the same DLL's the example was.

**Comment by witlock** [comment]
I created a new project and tried a map of size 50x50 tiles at 16px, all filled.
I created a 300x300 map of 16px tiles all filled.

**New Nez**

Default window size
300x300 map is 8 drawcalls (2 unique tiles), 64 FPS on weaker PC, 86 FPS on main
50x50 map is 3 drawcalls (1 unique tile), 450 FPS on weaker, 1200 on mainˇ

**Old Nez**

Default window size
300x300 map is 3 drawcalls, 750 FPS on main PC
50x50 map is 3 drawcalls, 1200 FPS on main PC

Has to have something to do with GetTile or tileToWorldPos imo.

**Comment by prime31** [comment]
tileToWorldPos is just a single multiply and hasnt changed. getTile is just a single-dimensional array lookup. Those shouldnt affect anything performance wise.

I just tried running the samples on Windows and everything is looking fine there. I was running Windows in a virtual machine on a computer with only integrated graphics and even when zooming the camera out to get the entire tile map in view and a debug build its still 120+ fps.

<img width="1535" alt="screenshot" src="https://cloud.githubusercontent.com/assets/60377/17151670/41cd1d88-5329-11e6-9c3e-190fa4c45e81.png">


What is the old commit hash that you were using?

**Comment by witlock** [comment]
by getTile and tileToWorldPos I pretty much meant anything related to the map size.
The ninja demo is even smaller than 50x50.
I tried the ninja demo map with the older dll I have and it reaches 1200 FPS by showing the whole map, which is twice what I got on the new version by just downloading and running the new samples (600 FPS).
I'm not entirely sure which commit it could be because everything's a mess on my side and I just took the dll from one of my tests, but if I were to guess I'd say somewhere around **429df9bbaf92202ed064007cebffdf8429c56f79**

**Comment by prime31** [comment]
This is definitely an odd one. On Windows I ran a tiled map scene on HEAD and on commit 429df9bbaf92202ed064007cebffdf8429c56f79. I am seeing a slight fps *increase* in HEAD vs the older commit.

**Comment by witlock** [comment]
After reinstalling everything including MonoGame and using the Cross Platform Desktop Template get around 20 FPS using my own map and debug build, but release runs at 200FPS which is pretty good.
I tested the ninja map in my new project and it runs at 1000 FPS in debug and 2300 FPS in release.

I hope this means my issue is resolved.

**Comment by witlock** [comment]
What I don't really understand though is that why the maps size is so crucial.
I have a map of size 400x400 and I just placed one single 16x16 tile and I only get 300 FPS in debug, while  the demo gets triple the amount with much more tiles, but a smaller map.

**Comment by witlock** [comment]
I'm pretty sure this is where my problems are from..

![largesttile](https://cloud.githubusercontent.com/assets/8792184/17172095/379c623c-53fc-11e6-8eb8-1da403556000.PNG)

It looks like the map writer is failing on my end.

**Comment by prime31** [comment]
Holy crap! That will do it and it clearly explains why map size matters. In a functional build a 10x10 map should draw exactly as fast as a 10000x10000 map. Unless the large tile alarm is set which would mean extra culling is happening that doesn't need to on the entire map.

**Comment by xdrie** [comment]
It might be useful to note in the FAQs that culling is only enabled if `LayerIndicesToRender` is set. If I have time I will try to submit some documentation for Tiled maps.
