### ISSUE TITLE
Make Screen._graphicsManager public

### ISSUE THREAD

**Issue by galennare** [prime31/Nez#816]
`Nez.Screen._graphicsManager` is currently an internal field.

This makes it impossble for developers to tweak settings for their game such as `PreferMultiSampling`.

Please make this a public field, or expose properties that developers can access through the Nez namespace.

**Comment by optimo** [comment]
That would need to go into , e.g. https://github.com/prime31/Nez/blob/HEAD/Nez.Portable/Utils/Screen.cs
Which you're free to tinker with - you didn't mention if you're on monogame or FNA, but I did see that there may be some flags not shared by both. Whether it's exposed on your setup I can't say. But you could in theory easily extend that class - if it works we could probably accept a pull-request of the changes too.

Is there something you want to get from using that mode; I'm not familiar with its usage? Seems you may be the first to ask about it also so I wonder what exactly you're looking to do with it. Just to say if you're looking to make your 2d textures sharper or blurrier, there may be SamplerState options to try out first. It sounds like something that may be interesting to a 2d project with high-resolution artwork. I hope you can say more.

**Comment by prime31** [comment]
[made ](https://github.com/prime31/Nez/commit/e1a33d5b55bb29e79541b1ac24e5842fc68eb9f4)
