### ISSUE TITLE
Discord Link Expired

### ISSUE THREAD

**Issue by Viv-0** [prime31/Nez#835]
This is a super "nothing" Issue, but I was wondering if the Discord was still active/available to enter?  The link to the discord has expired in the README. Sorry if this is the wrong place to put this.

**Comment by Viv-0** [comment]
![image](https://github.com/user-attachments/assets/e97d3235-e548-4a2f-92b4-0b42757d2390)

**Comment by prime31** [comment]
I just regenerated the invite link. See if this works: https://discord.gg/uFtGHNv

**Comment by prime31** [comment]
Actually, it looks like the newly generated link is the same 🤔 so that prolly won't work but perhaps just refreshing it changed something.

**Comment by prime31** [comment]
Every time i generate a link with no expiry it is the same link. Try [this one](https://discord.gg/uf25nydE), which is valid for just 1 day (and is definitely different).

**Comment by Viv-0** [comment]
This one worked, ty!
