### ISSUE TITLE
VirtualAxis returning integer and not float

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#86]
As per documentation, `VirtualAxis` is supposed to return a float from -1 to 1.  However, I am only getting values of -1, 0, or 1 - (So it's acting like a VirtualAxisInteger).

Here's a quick replication of the issue - 

```
public class TestScene : Scene
    {
        public override void initialize()
        {
            base.initialize();
            addRenderer(new DefaultRenderer());

            var ent = createEntity("input");
            ent.addComponent(new InputTest());
        }
    }

    public class InputTest : Component, IUpdatable
    {
        VirtualAxis InputX;

        public override void onAddedToEntity()
        {
            base.onAddedToEntity();

            InputX = new VirtualAxis();
            InputX.nodes.Add(new VirtualAxis.GamePadLeftStickX());
        }

        public void update()
        {
            Debug.log(InputX.value);
        }
    }
```

Tested with two different controllers - I tried setting deadzone to 0 as well just in case.  Am I missing something?

**Comment by prime31** [comment]
Step through in the debugger and see where the value is coming from. There are only a maximum of 3 - 4 lines of code for any of the VirtualAxis classes that are relevent. For example, this particular case is a single line of code that gets the value directly:

    Mathf.signThreshold( Input.gamePads[gamepadIndex].getLeftStick( deadzone ).X, deadzone );

Stick a breakpoint on it and see what the value is.

**Comment by piedoom** [comment]
The above works correctly.  Since I do want to use the manager system you've devised so I can accept keyboard / d-pad inputs as well, how might I transfer this to the system above?  I apologize if I'm being dim but I still can't figure out why it wasn't working in the first place.

**Comment by prime31** [comment]
GamePadLeftStickX will always return 1, 0 or -1. signThreshold keeps it at that so that it mimics a game pade. If you want the float version you can use VirtualJoystick or you can make your own VirtualFloatAxis that just skips the signThreshold.
