### ISSUE TITLE
Best way to check for collision with a Tiledmap (without a collision layer)

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#89]
It'd be great to have a tutorial on how to properly use TiledMaps.  I'm using your `TiledController` for player movement.  Since the map doesn't have colliders, and instead checks the tiled map itself, what is the simplest way to check if an object is colliding with the map (a simple `true` or `false` when updating).  What's the best way to check the angle of the hit?

I'm looking through the TiledController source, but it would be great to have some more docs on using TiledMap data in general!  Thanks.

**Comment by prime31** [comment]
The [TiledMapMover](https://github.com/prime31/Nez/blob/master/Nez-PCL/ECS/Components/Physics/TiledMapMover.cs) is still WIP so it won't be documented until it is totally done. That being said, it covers the most difficult aspects of tilemap collision including slopes and doing everything in a very optimized fashion. Pretty much anything at all you would want to do with a tilemap and collision can be done by just extracting the code from that class that you need.

If all you are looking for is if a collision happened the easiest thing to do is just grab the intersecting tiles and if one of them isnt null than you have a collision. The [getTilesIntersectingBounds](https://github.com/prime31/Nez/blob/master/Nez-PCL/PipelineRuntime/Tiled/TiledTileLayer.cs#L328) method will assist with that.
