### ISSUE TITLE
System.StackOverflowException in msCorlib -> on loading tileset texture in TiledMapReader.cs

### ISSUE THREAD

**Issue by Trebor777** [prime31/Nez#9]
Hello, 
I'm quite new to monogame and Nez, and thanks for the hard work your doing with this framework; 
I'm might be doing something wrong :p but when i'm starting my prototype to load a tiledMap I get this issue.

line 35: `var texture = reader.ContentManager.Load<Texture2D>( textureAssetName );`

textureAssetName is correct (I get the filename for the png "GameData/Maps/AbandonedMine"), the png file is in the same directory as the tmx file.

Here's the code i'm using in my Game.Initialize():

`var MapEntity = scene.createEntity("map");`
`var TiledMap = scene.contentManager.Load<TiledMap>("GameData/Maps/AbandonedMine");`
`MapEntity.addComponent(new TiledMapComponent(TiledMap));`

**Comment by Trebor777** [comment]
After a little test (because it's saying i'm might be overlooping too much, I thought: 
'is it because the png and the tmx have the same name?'

So I tried and renamed the png, and it worked perfectly. My bad. 
-> Having a warning in the content pipeline could help prevent this issue. But that's more of a monogame issue I think.

**Comment by prime31** [comment]
Aha! Yup. MonoGame has just one file extension for built assets (xnb) so you always have to name things explicitly. It would be nice if they had different extensions for different types.

**Comment by craftworkgames** [comment]
Yeah this is annoying. It's been that way since XNA though. It would be nice if MonoGame produced a more sensible error in this case.

One idea to break up assets by type is store different types in different folders. Not ideal though.
