### ISSUE TITLE
Spriter support

### ISSUE THREAD

**Issue by Blucky87** [prime31/Nez#97]
I have been working on making Spriter animations work with Nez. I can get them to show by adding the files from the https://github.com/loodakrawa/SpriterDotNet to the Nez PCL and pipeline projects and then rigging up a renderable component to display it. 

Although the sprite shows and the animation plays, just dropping in the files brings up some issues. Like the outline box from debug-render not covering the sprite. Also the custom box I make in Spriter does not behave correctly when transferred over to Nez. 

Have you tried to add Spriter animations? I read that your overlap2d import does not work with spriter correctly. Maybe we can try and get all the spriter features into Nez. The difficult part seems to be matching up the Nez way of handling sprites (creating outlines, flipping vert/horizontal, AABB physic boxes) to the SpriterDotNet way.  

https://github.com/Blucky87/Nez is my fork with just the SpriterDotNet stuff added. 
https://www.dropbox.com/sh/efi5hn7ui3lzql9/AACZmsIo8Vhtq3DVhggf9AYKa?dl=0 is the animation with a custom box (all of it is in the .7z file)
place the GreyGuy folder in your content folder

then add 
```
  var myScene = Scene.createWithDefaultRenderer(Color.CornflowerBlue);
  string scmlpath = "GreyGuy/player";
  Config config = new Config();
  DefaultProviderFactory<Sprite, SoundEffect> factory = new DefaultProviderFactory<Sprite, SoundEffect>(config, true);
  
  Entity entity = myScene.createEntity("Entity1");
  entity.transform.position = new Vector2( 300, 300 );
 
  SpriterContentLoader loader = new SpriterContentLoader(myScene.content, scmlpath);
  loader.Fill(factory);
  
  entity.addComponent(new SpriterAnimator(loader.Spriter.Entities[0], factory));
  Core.scene = myScene;
```

The Sprite for the factory is Nez.SpriterAnimator.Sprite not the renderable component sprite.

**Comment by prime31** [comment]
I do not use Spriter so I am not too familiar with it. The Overlap2D importer is indeed just for Overlap stuff. It doesn't touch Overlap animations, UI or Spriter. The implementation Overlap has for all that is just a bit too messy.

I just gave the SpriterDotNet code a quick look and it doesn't look like it should be too tricky to get it at least rendering along with Nez (I didn't look into Spriters physics/audio features at all). The MonoGameAnimator class seems to be the main interface to it and it fairly closely resembles a Nez RenderableComponent. Sticking a MonoGameAnimator in a RenderableComponent subclass would probably be a good way to do it. Something like this (TOTALLY untested):

```cs
public class SpriterThing : RenderableComponent, IUpdateable
{
    MonoGameAnimator _animator;

    public SpriterThing( MonoGameAnimator animator )
    {
        _animator = animator;
    }


    void IUpdateable.Update()
    {
        _animator.Update( Time.deltaTime );
    }


    public void render( Graphics graphics, Camera camera )
    {
        _animator.Draw( graphics.batcher ); // animator would just need this method added
    }
}
```


That would cover most of rendering but then you would need a way to get a bounding box for culling (overriding RenderableComponent.width/RenderableComponent.height and providing the actual width/height).

Again, I don't know Spriter but I assume you could just check the RenderableComponent.SpriteEffects and apply that to Spriters DrawInfo though that might not be totally correct as I am not sure where Spriter's ApplySpriteTransform actually gets called from.

**Comment by yaegerbomb** [comment]
I am using Spriter with my MonoGame / Nez project. This is what I did to get the Animator working (just the animator at the moment - I will be using entity systems to create triggers and bounding boxes at the appropriate moments of the animation I think):

First Create a new draw method in your MonoGameAnimator class that you can import from the [SpriterDotNet project](https://github.com/loodakrawa/SpriterDotNet):

```csharp
//MonoGameAnimator.cs new draw method
public virtual void Draw(Batcher batch) //using nez
{
	for (int i = 0; i < DrawInfos.Count; ++i)
	{
		DrawInfo di = DrawInfos[i];
		Sprite sprite = di.Sprite;
                //nez batch draw method
		batch.draw(sprite.Texture, di.Position, sprite.SourceRectangle, di.Color, di.Rotation, di.Origin, di.Scale, di.Effects, di.Depth);
		DrawInfoPool.Push(di);
	}
}
```

Next you'll want to create some type of Animator Component to add to your entities. Mine looks like this (rough non refactored right now)

```csharp
 public class AnimatorComponent : RenderableComponent, IUpdatable
{
	private IList<MonoGameAnimator> animators;
	private MonoGameAnimator currentAnimator;
	private SpriteBatch spriteBatch;
	private float spriteWidth;
	private float spriteHeight;
	private string animationPath;

	//constructor
	//we need to know the sprites with and height for the bounds getter - may
	//be able to be a bit more clever then just passing in the numbers but this works
	//for now
	public AnimatorComponent(float width, float height, string animationPath)
	{
		this.spriteWidth = width;
		this.spriteHeight = height;
		this.animationPath = animationPath;
	}

	//just like the Sprite class in Nez - we need to be able to get the bounds for our animation to render
	public override RectangleF bounds
	{
		get
		{
			if (_areBoundsDirty)
			{
				_bounds.calculateBounds(entity.transform.position, _localOffset, Vector2.Zero, entity.transform.scale, entity.transform.rotation, spriteWidth, spriteHeight); //our width and height
				_areBoundsDirty = false;
			}

			return _bounds;
		}
	}

	//general init method
	public override void initialize()
	{
		setUpAnimator();
	}
	
	//we need to update our animation's position every frame
	public void update()
	{
		//TODO: refactor this
		var center = new Vector2(entity.position.X, entity.position.Y + (spriteHeight / 2));
		currentAnimator.Position = center;
		
		//Nez timer functions are in seconds - looking at the spriter monogame example we need it to be
		//in milliseconds so we will do a conversion
		currentAnimator.Update(Time.deltaTime * 1000);
	}

	//TODO: general list of enums here and such...
	public void PlayAnimation(string AnimationName)
	{
		currentAnimator.Play(AnimationName)
	}

	//override the render method - call our animator and pass in our graphics batcher
	public override void render(Graphics graphics, Camera camera)
	{
		currentAnimator.Draw(graphics.batcher);
	}

	//basically taken from the SpriterDotNet monogame example
	private void setUpAnimator()
	{
		var config = new Config();
		DefaultProviderFactory<SpriterDotNet.MonoGame.Sprite, SoundEffect> factory = new DefaultProviderFactory<SpriterDotNet.MonoGame.Sprite, SoundEffect>(config, true);

		SpriterContentLoader loader = new SpriterContentLoader(Core.content, animationPath);

		loader.Fill(factory);

		animators = new List<MonoGameAnimator>();


		spriteBatch = new SpriteBatch(Core.graphicsDevice);

		foreach (SpriterEntity e in loader.Spriter.Entities)
		{
			var animator = new MonoGameAnimator(e, factory);
			animators.Add(animator);
			var center = new Vector2(entity.position.X, entity.position.Y + (spriteHeight / 2));
			animator.Position = center;
		}

		//TODO: refactor
		//or whatever pass in a param for default animation to play
		//a system will ideally handle this
		currentAnimator = animators.First();
		currentAnimator.Play("walk");
	}
}
```

Make sure you have your .scml file imported just like your other assets and the right path. Then you can do something like this:
```csharp
//someData.TexturePath = "Sprites/Animations/SomeCreature" <- imported through the conent pipeline
//see the SpriterDotNet project and use that dll as a reference to import .scml files correctly
someEntity.addComponent(new AnimatorComponent(someData.Width, someData.Height, someData.TexturePath));

```
