### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by aloisdeniel** [prime31/Nez#99]
I wonder : why are'nt C# naming conventions used for the project (PascalCase for method & property names instead of camelCase) ?

**Comment by prime31** [comment]
For a variety of reasons the main being it is the authors preference. There are countless reasons to choose one style over another and I personally prefer camel case for easily distinguishing types from variables especially when new to a codebase amongst other things. Additionally, it makes it clear where the .NET framework/MonoGame code is and where Nez code is.
